content/src/content/jcr_root/apps/core/wcm/components/image/v1/image/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/image/v1/image/_cq_editConfig.xml
=> Restrict image component to rasterized images

extension/contentfragment/content/pom.xml
=> #74 - Content Fragment Sandbox extension pointing to wrong dependencies versions

extension/contentfragment/bundle/pom.xml, extension/contentfragment/content/pom.xml, extension/pom.xml, pom.xml
* Updated reactor
* Updated extension modules versions and parent pom dependencies
(fixes #132)
=> [Maven] Include extension modules in main build

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServlet.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Image.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/package-info.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/AbstractImageTest.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServletTest.java, bundles/core/src/test/resources/image/test-content.json
* added backend support for rendering flipped images; the flipping transformation is performed last, with the horizontal flip having priority over the vertical one
=> [Image] Enable the Image Flip support and processing (#140)

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/PageImpl.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/PageImplTest.java
* get the page model for the structured resources returned by the template manager
* unit tests
(fixes #134)
=> [Page] Expose components from Template in Page Model

all/pom.xml, bundles/core/pom.xml, config/pom.xml, content/pom.xml, extension/contentfragment/bundle/pom.xml, extension/contentfragment/content/pom.xml, extension/pom.xml, parent/pom.xml, pom.xml, testing/it/ui-js/pom.xml, testing/junit/core/pom.xml
* Switched to released parent pom
=> [Maven] Development branch uses different artifacts and versions than master, #130

extension/contentfragment/content/src/content/META-INF/vault/filter.xml, extension/contentfragment/content/src/content/jcr_root/apps/core/wcm/config/com.adobe.cq.dam.cfm.impl.component.ComponentConfigImpl-core-comp-v1.config
* Added OSGi configuration
(fixes #136)
=> [CF] Provide Content Fragment configuration for resource types from Core Components

bundles/core/src/test/resources/page/test-conf.json, bundles/core/src/test/resources/page/test-content.json, bundles/core/src/test/resources/page/v2/test-conf.json, bundles/core/src/test/resources/page/v2/test-content.json, testing/it/ui-js/src/content/jcr_root/conf/core-components/settings/wcm/templates/core-components/structure/.content.xml
=> Update references to /etc/mobile

content/src/content/jcr_root/apps/core/wcm/components/form/options/v1/options/options.html, content/src/content/jcr_root/apps/core/wcm/components/form/options/v2/options/README.md, content/src/content/jcr_root/apps/core/wcm/components/form/options/v2/options/options.html, testing/it/ui-js/src/content/jcr_root/apps/core/wcm/tests/test-cases/FormOptions/v1/FormOptions.js, testing/it/ui-js/src/content/jcr_root/apps/core/wcm/tests/test-suites/FormOptions/v1/FormOptions.js, testing/it/ui-js/src/content/jcr_root/apps/core/wcm/tests/test-suites/FormOptions/v2/FormOptions.js
* wraps text and adds appropriate BEM class
=> Options component: Wrap labels of checkbox/radio in <span> #95

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v2/PageImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Page.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v2/PageImplTest.java, content/src/content/jcr_root/apps/core/wcm/components/page/v2/page/footer.html, content/src/content/jcr_root/apps/core/wcm/components/page/v2/page/head.html, content/src/content/jcr_root/apps/core/wcm/components/page/v2/page/headlibs.html, testing/junit/core/pom.xml, testing/junit/core/src/main/java/com/adobe/cq/wcm/core/components/testing/MockProductInfo.java, testing/junit/core/src/main/java/com/adobe/cq/wcm/core/components/testing/MockProductInfoProvider.java
* Conditionally including the cloudconfig script tags
(fixes #102)
=> Resource `cq/cloudconfig/components/scripttags/header` missing

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/PageImpl.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/PageImplTest.java
This reverts commit 77b49217fff24ecb178afa43a7922f0a21a4ce70.
=> Revert "[Page] Expose components from Template in Page Model (#135)"

all/pom.xml, bundles/core/pom.xml, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/SearchImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/SearchResultServlet.java, config/pom.xml, content/pom.xml, extension/contentfragment/bundle/pom.xml, extension/contentfragment/content/pom.xml, extension/pom.xml, parent/pom.xml, pom.xml, testing/it/ui-js/pom.xml, testing/junit/core/pom.xml, testing/junit/core/src/main/java/com/adobe/cq/wcm/core/components/testing/MockHtmlLibraryManager.java, testing/junit/core/src/main/java/com/adobe/cq/wcm/core/components/testing/MockLanguageManager.java
* Updated uber-jar version
* Updated testing mocks
(fixes #152)
=> [Maven] Update AEM uber-jar dependency

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/sandbox/internal/models/v1/TeaserImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/sandbox/models/Teaser.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/sandbox/internal/models/v1/TeaserImplTest.java, bundles/core/src/test/resources/teaser/test-content.json, content/src/content/jcr_root/apps/core/wcm/components/commons/v1/clientlibs/editor/checkboxTextfieldTuple/checkboxTextfieldTuple.js, content/src/content/jcr_root/apps/core/wcm/sandbox/components/teaser/v1/teaser/_cq_design_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/sandbox/components/teaser/v1/teaser/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/sandbox/components/teaser/v1/teaser/clientlibs/design/.content.xml, content/src/content/jcr_root/apps/core/wcm/sandbox/components/teaser/v1/teaser/clientlibs/design/js.txt, content/src/content/jcr_root/apps/core/wcm/sandbox/components/teaser/v1/teaser/clientlibs/design/js/teaser.js, content/src/content/jcr_root/apps/core/wcm/sandbox/components/teaser/v1/teaser/clientlibs/editor/js/teaser.js, content/src/content/jcr_root/apps/core/wcm/sandbox/components/teaser/v1/teaser/teaser.html
Initial proposal for multiple CTAs implementation
=> [Teaser] Add support for multiple call to action (CTA) (#155)

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/sandbox/internal/models/v1/TeaserImpl.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/sandbox/internal/models/v1/TeaserImplTest.java, bundles/core/src/test/resources/teaser/exporter-teaser9.json, content/src/content/jcr_root/apps/core/wcm/sandbox/components/teaser/v1/teaser/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/sandbox/components/teaser/v1/teaser/clientlibs/editor/js/teaser.js, content/src/content/jcr_root/apps/core/wcm/sandbox/components/teaser/v1/teaser/clientlibs/editor/less/teaser.less
* Split edit dialog content into tabs
* Added fixed column layout for edit dialog
* Updated logic to uncheck "Actions enabled" when removing all actions
* Updated implementation to remove the link URL when using actions
=> [Review][Teaser] Promote Teaser component from sandbox #190

content/src/content/jcr_root/apps/core/wcm/components/image/v1/image/README.md, content/src/content/jcr_root/apps/core/wcm/components/image/v2/image/README.md
| Fixed Issues?            | `Fixes #199` 
| Documentation Provided   | Yes
Add documentation in component README.md for SVG support.
=> [Image] Document the SVG behavior

content/src/content/jcr_root/apps/core/wcm/components/teaser/v1/teaser/_cq_dialog/.content.xml
- updates dialog descriptions to accurately describe CTA behavior
=> CQ-4240123: [Teaser] Implement multiple CTA's

content/src/content/jcr_root/apps/core/wcm/components/breadcrumb/v2/breadcrumb/breadcrumb.html
=> added schema.org microdata according to http://schema.org/BreadcrumbList

content/src/content/jcr_root/apps/core/wcm/components/text/v1/text/_cq_design_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/text/v1/text/_cq_editConfig.xml, content/src/content/jcr_root/apps/core/wcm/components/text/v2/text/_cq_design_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/text/v2/text/_cq_editConfig.xml, content/src/content/jcr_root/apps/core/wcm/components/text/v2/text/text.html
| Fixed Issues?            | Fixes #236
Added new RTE enhancements:
Enhance the RTE to have more default/optional configurations:
- **Undo/Redo** and **Image** functionality on v2 (optional - on design dialog)
- Add `<hr>` element to **paraformat** on v2 (default - on edit config)
- **Undo/Redo** functionality on v1 (optional - on design dialog)
- Add `<hr>` element to **paraformat** on v1 (default - on edit config)
=> Issue #236 [Text] RTE enhancements.

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/TitleImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Title.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/TitleImplTest.java, bundles/core/src/test/resources/title/exporter-title-jcr-title-link-v2.json, bundles/core/src/test/resources/title/exporter-title-jcr-title-type.json, bundles/core/src/test/resources/title/exporter-title-jcr-title-v2.json, bundles/core/src/test/resources/title/exporter-title-jcr-title.json, bundles/core/src/test/resources/title/exporter-title-linkdisabled.json, bundles/core/src/test/resources/title/exporter-title-noprops.json, bundles/core/src/test/resources/title/exporter-title-wrongtype.json, bundles/core/src/test/resources/title/test-content.json, content/src/content/jcr_root/apps/core/wcm/components/title/v2/title/README.md, content/src/content/jcr_root/apps/core/wcm/components/title/v2/title/_cq_design_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/title/v2/title/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/title/v2/title/title.html
| Fixed Issues?            | #211 
| Patch: Bug Fix?          | 
| Documentation Provided   | Yes (code comments and markdown)
=> Issue #211 [Title] Support links for titles.

content/src/content/jcr_root/apps/core/wcm/components/form/hidden/v1/hidden/hidden.html, content/src/content/jcr_root/apps/core/wcm/components/form/hidden/v2/hidden/hidden.html
| Fixed Issues?            | Fixes #240 
| Documentation Provided   | No - edit mode UI change only
=> Issue #240 [Form-Hidden] edit mode UI enhancement.

content/src/content/jcr_root/apps/core/wcm/components/page/v1/page/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/page/v2/page/_cq_dialog/.content.xml
adding cq.siteadmin.admin.properties clientlib to extraClientLibs of page dialog
fixes #261
=> [Page] Using sling:hideResource causes inheritance lock to disappear

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/ImageImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v2/ImageImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServlet.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Image.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/package-info.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/AbstractImageTest.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/ImageImplTest.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v2/ImageImplTest.java, bundles/core/src/test/resources/image/exporter-image3.json, bundles/core/src/test/resources/image/v2/exporter-image0.json, bundles/core/src/test/resources/image/v2/exporter-image18.json, bundles/core/src/test/resources/image/v2/exporter-image3-with-policy-delegate.json, bundles/core/src/test/resources/image/v2/exporter-image3.json, bundles/core/src/test/resources/image/v2/exporter-image_template.json, content/src/content/jcr_root/apps/core/wcm/components/image/v1/image/README.md, content/src/content/jcr_root/apps/core/wcm/components/image/v1/image/_cq_design_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/image/v2/image/README.md, content/src/content/jcr_root/apps/core/wcm/components/image/v2/image/_cq_design_dialog/.content.xml
| Fixed Issues?            | Fixes #254
=> Kwin feature/configurable image qualities

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/jackson/DefaultMethodSkippingModuleProvider.java, parent/pom.xml
- updates jackson dependency version -> 2.9.5
- don’t filter out default method implementations
| Fixed Issues?            | Fixes #277 
=> Jackson 2.9.* QS updates remove model JSON output properties

bundles/core/pom.xml, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/context/CoreComponentTestContext.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/PageImplTest.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/form/ContainerImplTest.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v2/PageImplTest.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServletMappingConfigurationConsumerTest.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/servlets/CoreFormHandlingServletTest.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/sandbox/internal/servlets/ChildrenEditorServletTest.java, bundles/core/src/test/resources/list/test-content.json, bundles/core/src/test/resources/list/v2/test-content.json, extension/contentfragment/bundle/pom.xml, parent/pom.xml
- Updated test dependencies
- Updated tests and test content
=> @releng: Update aem-mock and sling-mock versions.

content/src/content/jcr_root/apps/core/wcm/components/page/v2/page/_cq_design_dialog/.content.xml
- further clarity in the description of the head clientlib JS dialog field
=> [Page] Support loading configurable JS ClientLib in page head element

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/sandbox/internal/servlets/ContainerServlet.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/sandbox/internal/servlets/ContainerServletTest.java, content/src/content/jcr_root/apps/core/wcm/sandbox/commons/ui/clientlibs/panelcontainer/js/PanelContainer.js, content/src/content/jcr_root/apps/core/wcm/sandbox/commons/ui/components/childreneditor/clientlibs/js/childreneditor.js
- refactor the name, selector and parameters of the ChildrenEditorServlet servlet
- handle exception for the delete operation
=> GH-307 - [Carousel][Tabs] Refactor ChildrenEditorServlet

content/pom.xml, extension/contentfragment/content/pom.xml, parent/pom.xml
* updated HTL Maven Plugin to version 1.2.0-1.4.0
| Fixed Issues?            | Fixes #302
| Patch: Bug Fix?          | ✅
| Tests Added + Pass?      | No tests added 
| Any Dependency Changes?  | Updated HTL Maven Plugin to version 1.2.0-1.4.0
=> Update HTL Maven Plugin (#302)

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/sandbox/internal/models/AbstractContainerImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/sandbox/internal/models/TabsImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/sandbox/models/Tabs.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/sandbox/internal/models/TabsImplTest.java, bundles/core/src/test/resources/tabs/exporter-tabs1.json, bundles/core/src/test/resources/tabs/test-content.json, content/src/content/jcr_root/apps/core/wcm/sandbox/commons/ui/components/childreneditor/childreneditor.html, content/src/content/jcr_root/apps/core/wcm/sandbox/commons/ui/components/childreneditor/clientlibs/js/childreneditor.js, content/src/content/jcr_root/apps/core/wcm/sandbox/components/tabs/v1/tabs/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/sandbox/components/tabs/v1/tabs/clientlibs/editor/.content.xml, content/src/content/jcr_root/apps/core/wcm/sandbox/components/tabs/v1/tabs/clientlibs/editor/js.txt, content/src/content/jcr_root/apps/core/wcm/sandbox/components/tabs/v1/tabs/clientlibs/editor/js/tabs.js, content/src/content/jcr_root/apps/core/wcm/sandbox/components/tabs/v1/tabs/clientlibs/site/js/tabs.js, content/src/content/jcr_root/apps/core/wcm/sandbox/components/tabs/v1/tabs/tabs.html, testing/it/ui-js/src/content/jcr_root/apps/core/wcm/sandbox/tests/test-cases/Tabs/v1/Tabs.js, testing/it/ui-js/src/content/jcr_root/apps/core/wcm/sandbox/tests/test-suites/Tabs/v1/Tabs.js
* Added option to select default active item/tab
* Updated unit tests and test content
* Added integration test
* Fixes #316
=> [Tabs] Allow authors to specify a default selected item #316

content/src/content/jcr_root/apps/core/wcm/components/carousel/v1/carousel/clientlibs/site/js/carousel.js, content/src/content/jcr_root/apps/core/wcm/components/tabs/v1/tabs/clientlibs/site/js/tabs.js
| Fixed Issues?            | `Fixes #343` 
=> #343 [Carousel][Tabs] JS console error missing Granite object on publish

content/src/content/jcr_root/apps/core/wcm/components/commons/editor/clientlibs/panelcontainer/v1/js/panelContainerUtils.js
| Fixed Issues?            | `Fixes #353` 
| Documentation Provided   |  (code comments and or markdown)
=> #353 [PanelContainer] Selector lookup should be against all children

content/src/content/jcr_root/apps/core/wcm/components/image/v2/image/_cq_editConfig.xml
| Fixed Issues?            | #258 
* removed image/gif from cq:inplaceEditing plugins
=> Disable all image modification features for GIF images

.circleci/config.yml, parent/pom.xml
* Updated Java options to prevent Circle CI failures
=> Update Circle CI config

.circleci/config.yml, .github/pull_request_template.md, CONTRIBUTING.md, VERSIONS.md, all/pom.xml, all/src/content/META-INF/vault/definition/.content.xml, bundles/core/pom.xml, ci/deploy_snapshots.js, ci/release.js, ci/settings.xml, ci/tools.js, config/pom.xml, config/src/content/META-INF/vault/definition/.content.xml, content/package-lock.json, content/package.json, content/pom.xml, content/src/content/META-INF/vault/definition/.content.xml, extension/contentfragment/bundle/pom.xml, extension/contentfragment/content/pom.xml, extension/contentfragment/content/src/content/META-INF/vault/definition/.content.xml, extension/pom.xml, parent/pom.xml, pom.xml, testing/it/ui-js/package-lock.json, testing/it/ui-js/package.json, testing/it/ui-js/pom.xml, testing/it/ui-js/src/content/META-INF/vault/definition/.content.xml, testing/junit/core/pom.xml
* Cleanup pom.xml files
* Updated repo URLs after moving to Adobe org on github.com
* Added OSSRH settings
=> [releng] Release artifacts to Maven Central #356

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServlet.java
* Updated check, was preventing reading the component properties for unauthenticated users
Fixes #375
=> [Teaser] - adaptive width images don't render for anonymous user #375

parent/pom.xml, pom.xml
=> [releng] Release artifacts to Maven Central #356 (#362)

parent/pom.xml
suggestions to set the java version in the parent pom (avoid building code to wrong version of java, better IDE integration)
=> specify what version of java to compile with

ci/release.js, content/package.json, content/pom.xml, parent/pom.xml, testing/it/ui-js/package-lock.json, testing/it/ui-js/package.json, testing/it/ui-js/pom.xml
* Updated node and npm to latest LTS versions
* Removed duplicate properties for frontend-maven-plugin, node and npm versions
=> [releng] Prepare v2.2.2

content/src/content/jcr_root/apps/core/wcm/components/carousel/v1/carousel/clientlibs/site/js/carousel.js
- adds parent element check
| Fixed Issues?            | `Fixes #429 ` 
| Documentation Provided   |
=> [Carousel] JS error for a detached autoplaying Carousel

examples/content/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-base/.content.xml, examples/content/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-site/js.txt, examples/content/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-site/scripts/demo.js, examples/content/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-site/scripts/vendor/promise-polyfill.js
- Added Promise polyfill
- Added promisified getJSON()
=> @refactor Remove jQuery dependency

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/TeaserImpl.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/TeaserImplTest.java, bundles/core/src/test/resources/teaser/exporter-teaser12.json, bundles/core/src/test/resources/teaser/test-content.json
=> #440 [Teaser] The link is broken when there is no image

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/ImageImpl.java, content/src/content/jcr_root/apps/core/wcm/components/separator/v1/separator/README.md
Reviews documentation for the upcoming [2.3.0 release](https://github.com/adobe/aem-core-wcm-components/milestone/10).
=> [Releng] Review documentation

examples/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-site/styles/structure/grid-base.less, examples/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-site/styles/structure/grid.less, examples/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-site/styles/structure/index.less
- adds grid-base.less locally as its location is unstable between AEM versions.
=> [Library] Create a basic CSS style for the Library

examples/src/content/jcr_root/apps/core-components-examples/components/page/.content.xml, examples/src/content/jcr_root/apps/core-components-examples/components/page/head.html, examples/src/content/jcr_root/conf/core-components-examples/settings/wcm/policies/.content.xml, examples/src/content/jcr_root/conf/core-components-examples/settings/wcm/template-types/empty-page/initial/.content.xml, examples/src/content/jcr_root/conf/core-components-examples/settings/wcm/template-types/empty-page/structure/.content.xml, examples/src/content/jcr_root/conf/core-components-examples/settings/wcm/templates/content-page/initial/.content.xml, examples/src/content/jcr_root/conf/core-components-examples/settings/wcm/templates/content-page/policies/.content.xml, examples/src/content/jcr_root/conf/core-components-examples/settings/wcm/templates/content-page/structure/.content.xml
- proxies the v2 page component and adds viewport meta tag via a `head.html` override.
=> [Library] General improvements

index.html
- use JavaScript redirect
- http meta refresh as fallback
=> [Library] Redirect from index.html -> library.html

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/SeparatorImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Separator.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/package-info.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/SeparatorImplTest.java, bundles/core/src/test/resources/separator/exporter-separator1.json, bundles/core/src/test/resources/separator/test-content.json
=> [Separator] the JSON export fails

content/src/content/jcr_root/apps/core/wcm/components/breadcrumb/v1/breadcrumb/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/breadcrumb/v2/breadcrumb/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/carousel/v1/carousel/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/form/button/v1/button/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/form/button/v2/button/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/form/container/v1/container/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/form/container/v2/container/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/form/hidden/v1/hidden/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/form/hidden/v2/hidden/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/form/options/v1/options/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/form/options/v2/options/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/form/text/v1/text/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/form/text/v2/text/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/image/v1/image/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/image/v2/image/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/languagenavigation/v1/languagenavigation/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/list/v1/list/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/list/v2/list/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/navigation/v1/navigation/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/page/v1/page/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/page/v2/page/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/search/v1/search/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/tabs/v1/tabs/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/teaser/v1/teaser/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/text/v2/text/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/title/v1/title/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/title/v2/title/_cq_dialog/.content.xml, extension/contentfragment/content/src/content/jcr_root/apps/core/wcm/extension/components/contentfragment/v1/contentfragment/_cq_dialog/.content.xml
=> Add trackingFeature property to component dialog definitions

examples/src/content/jcr_root/conf/core-components-examples/settings/wcm/templates/content-page/structure/.content.xml, examples/src/content/jcr_root/content/core-components-examples/library/.content.xml
Updates library version links for the 2.3.2 release
=> [Library] update library version and milestone links

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/contentfragment/ContentFragmentListImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/contentfragment/AbstractContentFragmentDataSourceServlet.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/contentfragment/AbstractDataSourceServlet.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/contentfragment/ElementsDataSourceServlet.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/contentfragment/ModelDataSourceServlet.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/contentfragment/ModelElementsDataSourceServlet.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/contentfragment/VariationsDataSourceServlet.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/contentfragment/ContentFragmentList.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/contentfragment/ContentFragmentListImplTest.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/servlets/contentfragment/AbstractContentFragmentDataSourceServletTest.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/servlets/contentfragment/AbstractDataSourceServletTest.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/servlets/contentfragment/ElementsDataSourceServletTest.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/servlets/contentfragment/ModelDataSourceServletTest.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/servlets/contentfragment/ModelElementsDataSourceServletTest.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/servlets/contentfragment/VariationsDataSourceServletTest.java, bundles/core/src/test/resources/com/adobe/cq/wcm/core/components/internal/servlets/contentfragment/test-content.json, bundles/core/src/test/resources/contentfragmentlist/test-content.json, content/src/content/jcr_root/apps/core/wcm/components/contentfragment/v1/contentfragment/element.html, content/src/content/jcr_root/apps/core/wcm/components/contentfragment/v1/contentfragment/templates.html, content/src/content/jcr_root/apps/core/wcm/components/contentfragmentlist/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/contentfragmentlist/v1/contentfragmentlist/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/contentfragmentlist/v1/contentfragmentlist/_cq_design_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/contentfragmentlist/v1/contentfragmentlist/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/contentfragmentlist/v1/contentfragmentlist/clientlibs/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/contentfragmentlist/v1/contentfragmentlist/clientlibs/dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/contentfragmentlist/v1/contentfragmentlist/clientlibs/dialog/js.txt, content/src/content/jcr_root/apps/core/wcm/components/contentfragmentlist/v1/contentfragmentlist/clientlibs/dialog/js/editDialog.js, content/src/content/jcr_root/apps/core/wcm/components/contentfragmentlist/v1/contentfragmentlist/contentfragmentlist.html
This PR is based on PRs https://github.com/adobe/aem-core-wcm-components/pull/499 and https://github.com/adobe/aem-core-wcm-components/pull/498
It adds/fixes feature #340 
Todos:
=> [ContentFragment] Add content fragment list component (#340)

README.md, content/src/content/jcr_root/apps/core/wcm/components/carousel/v1/carousel/README.md, content/src/content/jcr_root/apps/core/wcm/components/contentfragment/v1/contentfragment/README.md, content/src/content/jcr_root/apps/core/wcm/components/image/v2/image/README.md, content/src/content/jcr_root/apps/core/wcm/components/list/v2/list/README.md, content/src/content/jcr_root/apps/core/wcm/components/separator/v1/separator/README.md, content/src/content/jcr_root/apps/core/wcm/components/sharing/v1/sharing/README.md, content/src/content/jcr_root/apps/core/wcm/components/tabs/v1/tabs/README.md, content/src/content/jcr_root/apps/core/wcm/components/tabs/v1/tabs/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/teaser/v1/teaser/README.md, content/src/content/jcr_root/apps/core/wcm/components/text/v2/text/README.md, content/src/content/jcr_root/apps/core/wcm/components/title/v2/title/README.md, examples/src/content/jcr_root/content/core-components-examples/library/carousel/.content.xml, examples/src/content/jcr_root/content/core-components-examples/library/content-fragment/.content.xml, examples/src/content/jcr_root/content/core-components-examples/library/image/.content.xml, examples/src/content/jcr_root/content/core-components-examples/library/list/.content.xml, examples/src/content/jcr_root/content/core-components-examples/library/separator/.content.xml, examples/src/content/jcr_root/content/core-components-examples/library/social-sharing/.content.xml, examples/src/content/jcr_root/content/core-components-examples/library/tabs/.content.xml, examples/src/content/jcr_root/content/core-components-examples/library/teaser/.content.xml, examples/src/content/jcr_root/content/core-components-examples/library/text/.content.xml, examples/src/content/jcr_root/content/core-components-examples/library/title/.content.xml
- uses Go URL for Component Library Home
- uses Go URLs for Component Library component pages
- uses Go URLs for component technical documentation
=> [Library] Core Components Documentation GO URLs

README.md, content/src/content/jcr_root/apps/core/wcm/components/contentfragment/v1/contentfragment/README.md, content/src/content/jcr_root/apps/core/wcm/components/contentfragment/v1/contentfragment/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/contentfragment/v1/contentfragment/clientlibs/editor/dialog/js/editDialog.js, testing/it/ui-js/src/content/jcr_root/apps/core/wcm/tests/common/commons.js, testing/it/ui-js/src/content/jcr_root/apps/core/wcm/tests/test-cases/ContentFragment/v1/.content.xml, testing/it/ui-js/src/content/jcr_root/apps/core/wcm/tests/test-cases/ContentFragment/v1/ContentFragment.js, testing/it/ui-js/src/content/jcr_root/apps/core/wcm/tests/test-cases/ContentFragment/v1/js.txt, testing/it/ui-js/src/content/jcr_root/apps/core/wcm/tests/test-cases/ContentFragment/v1/ns.js, testing/it/ui-js/src/content/jcr_root/apps/core/wcm/tests/test-suites/ContentFragment/v1/.content.xml, testing/it/ui-js/src/content/jcr_root/apps/core/wcm/tests/test-suites/ContentFragment/v1/ContentFragment.js, testing/it/ui-js/src/content/jcr_root/apps/core/wcm/tests/test-suites/ContentFragment/v1/js.txt, testing/it/ui-js/src/content/jcr_root/content/dam/core-components/contentfragments-tests/simple-fragment/_jcr_content/renditions/short
Create UI tests for the content fragment component.
Fixes the issue: https://github.com/adobe/aem-core-wcm-components/issues/524
This PR also:
- replaces: cmp-contentfragment__edit-dialog -> cmp-contentfragment__editor
- adds the missing BEM classes to the README
- adds a link to the content fragment list in the main README
=> [ContentFragment] Add UI tests

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/contentfragment/ContentFragmentListImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/contentfragment/ContentFragmentList.java
- Match CF List property names to keys
=> [Releng] 2.4.0 Pre-release

README.md, VERSIONS.md, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/contentfragment/ContentFragmentListImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/contentfragment/ContentFragment.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/contentfragment/ContentFragmentList.java, content/src/content/jcr_root/apps/core/wcm/components/contentfragmentlist/v1/contentfragmentlist/clientlibs/editor/js/contentfragmentlist.js, content/src/content/jcr_root/apps/core/wcm/components/form/options/v1/options/README.md, content/src/content/jcr_root/apps/core/wcm/components/form/options/v2/options/README.md, examples/src/content/jcr_root/conf/core-components-examples/settings/wcm/templates/content-page/structure/.content.xml, examples/src/content/jcr_root/content/core-components-examples/library/.content.xml
- aligns CF List property keys with value naming
- updates JavaDocs
- updates JSDocs
- updates component documentation
- updates library version
- updates README.md and VERSIONS.md
=> [Releng] 2.4.0 Pre-release - Update documentation

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/AccordionImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/ContainerServlet.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Accordion.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Container.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/package-info.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/AccordionImplTest.java, bundles/core/src/test/resources/accordion/exporter-accordion1.json, bundles/core/src/test/resources/accordion/exporter-accordion2.json, bundles/core/src/test/resources/accordion/test-apps.json, bundles/core/src/test/resources/accordion/test-content.json, content/src/content/jcr_root/apps/core/wcm/components/accordion/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion/README.md, content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion/_cq_design_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion/_cq_editConfig.xml, content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion/accordion.html, content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion/clientlibs/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion/clientlibs/editor/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion/clientlibs/editor/js.txt, content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion/clientlibs/editor/js/accordion.js, content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion/clientlibs/editorhook/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion/clientlibs/editorhook/js.txt, content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion/clientlibs/editorhook/js/panelcontainer.js, content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion/clientlibs/site/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion/clientlibs/site/css.txt, content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion/clientlibs/site/css/accordion.less, content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion/clientlibs/site/js.txt, content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion/clientlibs/site/js/accordion.js
| Fixed Issues?            | N/A 
| Patch: Bug Fix?          | N/A
| Minor: New Feature?      | New component
Added a new Accordion component using the PanelContainer similar to the Carousel and the Tabs components.
Here is an animated gif demoing keyboard and mouse functionality (tab, up, down, left, right, home, end, space & enter):
=> [Accordion] Create accordion component

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/DownloadImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Download.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/DownloadImplTest.java, bundles/core/src/test/resources/download/exporter-download-fully-configured-file.json, bundles/core/src/test/resources/download/exporter-download-fully-configured.json, bundles/core/src/test/resources/download/exporter-download-with-action-text-from-style.json, bundles/core/src/test/resources/download/exporter-download-with-dam-properties.json, bundles/core/src/test/resources/download/exporter-download-with-title-type.json, content/src/content/jcr_root/apps/core/wcm/components/download/v1/download/_cq_design_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/download/v1/download/download.html
* removed design setting to show / hide the image preview
* removed imagePath field
* fixed issue with wrong download url
=> Remove image preview in download component

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/AllowedHeadingElementsDataSourceServlet.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/TextValueDataResourceSource.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/servlets/AllowedHeadingElementsDataSourceServletTest.java
- extend TextValueDataResourceSource with selected property
- add default type to data source servlet for allowed headings
fixes #629
=> [Title] Default heading size option is not reflected in dialog

README.md, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/AbstractComponentImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/AbstractContainerImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Component.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Container.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/LayoutContainerImplTest.java, bundles/core/src/test/resources/container/exporter-container1.json, content/src/content/jcr_root/apps/core/wcm/components/container/v1/container/responsiveGrid.html, content/src/content/jcr_root/apps/core/wcm/components/container/v1/container/simple.html
* Removed currently unused classes and attributes properties
* Moved background style constants and getter to Container
Fixes #644
=> [Component] Address base component interface feedback #644

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/ButtonImpl.java, content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion/clientlibs/site/js.txt, content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion/clientlibs/site/js/polyfills.js, examples/src/content/jcr_root/content/core-components-examples/library/button/.content.xml
- Button - handle content page links as well as external
- Button - use content page in library example
- Accordion - add matches and closest polypill for IE11
=> @releng - 2.5.0 Pre-release - Test

content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion/README.md, content/src/content/jcr_root/apps/core/wcm/components/button/v1/button/README.md, content/src/content/jcr_root/apps/core/wcm/components/container/v1/container/README.md, content/src/content/jcr_root/apps/core/wcm/components/download/v1/download/README.md
- adds author credits to newly introduced components.
=> @releng - 2.5.0 Pre-Release - documentation

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/DownloadServlet.java
=> Updated DownloadServlet.java

bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/PageImplTest.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v2/PageImplTest.java
=> [Download][Page] Locale issues when parsing dates in Java test cases

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/DownloadServlet.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/servlets/DownloadServletTest.java, bundles/core/src/test/resources/download/test-content.json
=> [Download] Improved memory usage

content/src/content/jcr_root/apps/core/wcm/components/commons/v1/clientlibs/editor/checkboxTextfieldTuple/checkboxTextfieldTuple.js, content/src/content/jcr_root/apps/core/wcm/components/teaser/v1/teaser/clientlibs/editor/js/teaser.js, testing/it/ui-js/src/content/jcr_root/apps/core/wcm/tests/test-cases/Teaser/v1/Teaser.js, testing/it/ui-js/src/content/jcr_root/apps/core/wcm/tests/test-suites/Teaser/v1/Teaser.js
- update the data attribute for the previous text value after text get changed by the author
fixes #719
=> [Teaser] Title changes reset after adding a link

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/contentfragment/ContentFragmentListImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/contentfragment/ModelElementsDataSourceServlet.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/contentfragment/ContentFragmentList.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/contentfragment/package-info.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/contentfragment/ContentFragmentListImplTest.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/servlets/contentfragment/ModelElementsDataSourceServletTest.java, bundles/core/src/test/resources/contentfragmentlist/test-content.json, content/src/content/jcr_root/apps/core/wcm/components/contentfragmentlist/v1/contentfragmentlist/_cq_dialog/.content.xml
- add order by and sort order drop down to cfm list component
- enhance data source servlet to populate list for order by drop down
- enhance cfm list model to create additional predicate if order by and sort oder property is set
- adapt unit tests
fixes #698
=> [Content Fragment List] Display in a specific order

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
- adds hint to create a pull request for bug reports.
- replace PR acronym in feature request report template.
=> [Documentation] Pull Request hint in issue creation

config/src/content/jcr_root/apps/core/wcm/config/com.adobe.cq.wcm.core.components.internal.services.embed.OEmbedClientImplConfigurationFactory-twitter.config
* Updated Twitter scheme to be more generic to also allow timelines and moments
Fixes #747
=> [Embed] Add Twitter feed embed type #747

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/contentfragment/ModelDataSourceServlet.java
- add p.limit parameter to querybuilder
fixes #758
=> [ContentFragment ] List to show more than 10 models in dialog

content/src/content/jcr_root/apps/core/wcm/components/container/v1/container/allowedcomponents.html, content/src/content/jcr_root/apps/core/wcm/components/container/v1/container/simple.html
- add allowedcomponents template file to keep backward compatibility
fixes #766
=> [Container] Throws exception in structure mode on 6.3

content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion/clientlibs/site/js/accordion.js
=> [Accordion] function `onDocumentReady` called before `DOMContentLoaded`

content/src/content/jcr_root/apps/core/wcm/components/carousel/v1/carousel/carousel.html
| Fixed Issues?            | Fixes #783 
| Major: Breaking Change?  | No 
=> Removed role="button" from buttons.

content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion/clientlibs/site/js/accordion.js, testing/it/ui-js/src/content/jcr_root/apps/core/wcm/tests/test-suites/Embed/v1/Embed.js
| Fixed Issues?            | An indexOf or lastIndexOf call with a single letter String
An indexOf or lastIndexOf call with a single letter String can be made more performant by switching to a call with a char argument.
=> An indexOf or lastIndexOf call with a single letter String

CONTRIBUTING.md, README.md, content/src/content/jcr_root/apps/core/wcm/components/navigation/v1/navigation/README.md, content/src/content/jcr_root/apps/core/wcm/components/page/v2/page/README.md, content/src/content/jcr_root/apps/core/wcm/components/search/v1/search/README.md
Fixed some typos in  readme.md and contributing.md.
=> Fixed Some typos.

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/ContainerServlet.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/SearchResultServlet.java
| Fixed Issues?            | (none)
| Patch: Bug Fix?          | make explicitly clear that the stacktrace is written
| Minor: New Feature?      | (none)
| Major: Breaking Change?  | (none)
| Tests Added + Pass?      | (none affected)
| Documentation Provided   | (none)
| Any Dependency Changes?  | (none)
Change a few log statements to make it directly visible that the stacktrace is written (and not ``exception.toString()`` is invoked.
(now rebased and PR against development, closes #799 )
=> Feature/improve exception handling (2nd)

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/AllowedHeadingElementsDataSourceServlet.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/servlets/AllowedHeadingElementsDataSourceServletTest.java, bundles/core/src/test/resources/title/datasource/allowedheadingelements/test-content.json
| Fixed Issues?            | https://github.com/adobe/aem-core-wcm-components/issues/791
| Documentation Provided   | NA
Resolved a NPE error when using a title component
=> [Title] Null pointer exception #791

content/src/content/jcr_root/apps/core/wcm/components/image/v1/image/_cq_editConfig.xml, content/src/content/jcr_root/apps/core/wcm/components/image/v2/image/_cq_editConfig.xml
- accepts expects a regex, escape the +
=> [Image] Drag & drop SVG on image component not working

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/AbstractContainerImpl.java
Updates AbstractContainer such that children items are read from the effective resource instead of the current resource. This has the advantage that it allows the component to be defined in the template structure while allowing the component to be editable.
Fixes #655
=> Updates AbstractContainer such that children items are read from the effective resource 

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/TeaserImpl.java
- exclude unused action properties from the JSON rendering
=> GH-431 - [Teaser] UOE is thrown during json serialization

content/src/content/jcr_root/apps/core/wcm/components/teaser/v1/teaser/clientlibs/editor/js/teaser.js
- wraps initial handling in an editing start callback for the description field rich text editor.
=> [Teaser] Description is editable even though "Get description from linked page" is checked

content/src/content/jcr_root/apps/core/wcm/components/embed/v1/embed/embeddable/youtube/youtube.html
- support full screen mode
| Fixed Issues?            | Fixes #843
=> Youtube Embeddable doesn't support full screen

content/src/content/jcr_root/apps/core/wcm/components/embed/v1/embed/_cq_design_dialog/.content.xml
| Fixed Issues?            | Fixes #846 
=> [Embed] Add a style tab to the Embed component

CONTRIBUTING.md
| Fixed Issues?            | #853
| Patch: Bug Fix?          | n/a
| Minor: New Feature?      | n/a
| Major: Breaking Change?  | n/a
* restructured the guidelines to emphasize code contributions over requests
* added information about the contrib repository in the "Submitting Feature" section
=> Refine contribution guidelines #853

README.md
=> Update compatibility with cloud

content/src/content/jcr_root/apps/core/wcm/components/commons/editor/dialog/childreneditor/v1/childreneditor/childreneditor.html
=> Make item title required for all panel based components

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v2/ImageImpl.java
=> Fix breaking image output for model.json if image is empty

bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/services/embed/OEmbedClientImplTest.java
* Improved mocking of HTTP client
(Fixes #895)
=> OEmbedClientImplTest is failing in both local and CircleCI builds #895

content/src/content/jcr_root/apps/core/wcm/components/embed/v1/embed/embeddable/youtube/youtube.html
- adds generic aria label to the YouTube embeddable iframe.
=> [Embed] Accessibility issues flagged for Youtube

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/AbstractComponentImpl.java
- minor improvements to the auto ID implementation docs.
=> Configurable IDs for all components

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/embed/AllowedEmbeddablesDataSourceServlet.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/embed/EmbeddableOptionsDataSourceServlet.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/servlets/embed/AllowedEmbeddablesDataSourceServletTest.java, bundles/core/src/test/resources/embed/v1/datasources/allowedembeddables/test-content.json
- add support for Design Mode in DataSource Servlet
- adapt unit tests
fixes #931
=> [Embed] Allowed Embeddables are not supported in Design Mode

content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion/accordion.html, content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion/clientlibs/site/js/accordion.js
| Fixed Issues?            | Fixes https://github.com/adobe/aem-core-wcm-components/issues/942
| Patch: Bug Fix?          | Feature enhancement
| Tests Added + Pass?      | No Tests added
Deep linking capability for accordion
Generating item id with component-id and item-name instead of item index
Moved id attribute from inner div to the wrapper dive of each item
=> Deep-linking capability on Accordion component #942

content/src/content/jcr_root/apps/core/wcm/components/image/v2/image/clientlibs/site/js/image.js
| Q |  A
| Fixed Issues?            | Fixes #966 
| Tests Added + Pass?      | 👎
| Documentation Provided   | 👎
| Any Dependency Changes?  | 👎
Add additional event listener to check if image should be loaded
=> Image lazy loading not working correctly with Panel Containers

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/Utils.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/AbstractComponentImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/AbstractImageDelegatingModel.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/AbstractListItemImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/TeaserImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/SearchResultServlet.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/CarouselImplTest.java, content/src/content/jcr_root/apps/core/wcm/components/carousel/v1/carousel/carousel.html
[DataLayer] Refactor ID generation for container items (accordion, carousel, tabs, teaser cta and search)
=> [DataLayer] Refactor ID generation for container items (accordion, carousel, tabs, teaser cta and search)

bundles/core/pom.xml, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/jackson/DataLayerSerializer.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/AbstractComponentImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/CarouselImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/DataLayerImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/TabsImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Component.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/DataLayer.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/jackson/DataLayerSerializerTest.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/CarouselImplTest.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/DataLayerImplTest.java, bundles/core/src/test/resources/progressbar/exporter-progressbar-1.json, bundles/core/src/test/resources/title/exporter-title-jcr-title-nodatalayer.json, content/src/content/jcr_root/apps/core/wcm/components/breadcrumb/v2/breadcrumb/breadcrumb.html, content/src/content/jcr_root/apps/core/wcm/components/button/v1/button/button.html, content/src/content/jcr_root/apps/core/wcm/components/image/v2/image/image.html, content/src/content/jcr_root/apps/core/wcm/components/languagenavigation/v1/languagenavigation/itemContent.html, content/src/content/jcr_root/apps/core/wcm/components/list/v2/list/item.html, content/src/content/jcr_root/apps/core/wcm/components/navigation/v1/navigation/itemContent.html, content/src/content/jcr_root/apps/core/wcm/components/teaser/v1/teaser/action.html, content/src/content/jcr_root/apps/core/wcm/components/teaser/v1/teaser/title.html, content/src/content/jcr_root/apps/core/wcm/components/title/v2/title/title.html, examples/ui.content/src/content/jcr_root/content/core-components-examples/library/page-authoring/title/.content.xml, parent/pom.xml
- remove data attributes from HTL output in case the data layer is disabled
- make getString return empty string in case data layer is disabled
- fix broken link in title example content
- adapt unit test to test getString output
=> Remove data attributes from components

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/TabsImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Tabs.java, bundles/core/src/test/resources/tabs/exporter-tabs1.json, bundles/core/src/test/resources/tabs/exporter-tabs2.json, bundles/core/src/test/resources/tabs/exporter-tabs3.json, extensions/amp/content/src/content/jcr_root/apps/core/wcm/extensions/amp/components/tabs/v1/tabs/amp.html
Fixes #1014:
- Remove Tabs#getTabsId
- use the component ID that was introduced lately
=> [Tabs] Remove Tabs#getTabsId

content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion/README.md, content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion/clientlibs/site/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion/clientlibs/site/js/accordion.js, content/src/content/jcr_root/apps/core/wcm/components/commons/site/clientlibs/container/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/commons/site/clientlibs/container/js.txt, content/src/content/jcr_root/apps/core/wcm/components/commons/site/clientlibs/container/js/containerUtils.js, content/src/content/jcr_root/apps/core/wcm/components/tabs/v1/tabs/README.md, content/src/content/jcr_root/apps/core/wcm/components/tabs/v1/tabs/clientlibs/site/js/tabs.js
- refactored existing PRs as specific item ID was introduced for Tabs and Accordion:
https://github.com/adobe/aem-core-wcm-components/pull/946
https://github.com/adobe/aem-core-wcm-components/pull/960
=> Deep-linking capability on Accordion and Tabs components

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/ListItem.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Page.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Teaser.java
=> Added default return values for new methods

examples/ui.content/src/content/jcr_root/content/core-components-examples/library/container/carousel/.content.xml, examples/ui.content/src/content/jcr_root/content/core-components-examples/library/page-authoring/image/.content.xml
=> Fixes #1048 fix invalid links in examples content

extensions/amp/bundle/pom.xml, extensions/amp/bundle/src/main/java/com/adobe/cq/wcm/core/extensions/amp/internal/AmpUtil.java, extensions/amp/bundle/src/main/java/com/adobe/cq/wcm/core/extensions/amp/internal/models/v1/AmpPageImpl.java, extensions/amp/bundle/src/test/java/com/adobe/cq/wcm/core/extensions/amp/internal/AmpUtilTest.java, extensions/amp/bundle/src/test/resources/amp-util/test-content.json, extensions/amp/content/src/content/jcr_root/apps/core/wcm/extensions/amp/components/search/v1/search/amp.html
Add support for AMP clientlib aggregation for experience fragments
=> Add support for clientlib aggregation for experience fragments

content/src/content/jcr_root/apps/core/wcm/components/embed/v1/embed/README.md
| Fixed Issues?            | Fixes #1056  
Updated the documentation around creating a custom embeddable fragment for the embed component. 
References [issue 1056](https://github.com/adobe/aem-core-wcm-components/issues/1056)
=> update instructions around Embed/Custom embeddable (issue 1056)

examples/ui.apps/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-themes/core-components-clean/styles/components/form/base.less
Basic styling for form elements in components library.
=> form elements styling in components library

content/src/content/jcr_root/apps/core/wcm/components/commons/v1/clientlibs/editor/checkboxTextfieldTuple/checkboxTextfieldTuple.js
| Fixed Issues?            | Fixes #1088 
Make use of RTE API for event listener and updates to the text value
=> Teaser can not save all links

content/clientlib.config.js
=> Fixes #1092 explicitly define min:gcc for datalayer client library

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/TabsImpl.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/TabsImplTest.java, bundles/core/src/test/resources/tabs/exporter-tabs0.json
=> Fixes #1086 do not throw error when tabs component has not items

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/LayoutContainerImpl.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/LayoutContainerImplTest.java, bundles/core/src/test/resources/container/exporter-container2.json, content/src/content/jcr_root/apps/core/wcm/components/container/v1/container/README.md, content/src/content/jcr_root/apps/core/wcm/components/container/v1/container/_cq_design_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/container/v1/container/_cq_dialog/.content.xml
Set container layout type via content policy
Allow to disable layout type selection in edit dialog via content policy
=> Fixes #1094 [Container] Control Container Layout via Content Policy

content/package-lock.json, content/package.json
Updated Adobe Client Data Layer version from `1.0.2` to `1.1.0`
=> Adobe Client Data Layer version 1.1.0

content/src/content/jcr_root/apps/core/wcm/components/button/v1/button/button.html
https://github.com/adobe/aem-core-wcm-components/issues/1166
| Fixed Issues?            | Fixes #1166
=> Fix for issue - 1166

.github/workflows/deploy-to-library.yml
Requires few secrets to be set
| Fixed Issues?            | `Fixes #1169` 
Adding a Github action that pushes content of `development` branch to Core Components' library repository.
=> #1169 - Setup Github action for deploying to Core Components Library

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v2/PageImpl.java
This fixes #1172
| Fixed Issues?            | #1172 
=> Do not consider transitive libraries for calculating the "appResourcePath"

content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion/clientlibs/site/js/accordion.js, content/src/content/jcr_root/apps/core/wcm/components/carousel/v1/carousel/clientlibs/site/js/carousel.js, content/src/content/jcr_root/apps/core/wcm/components/tabs/v1/tabs/clientlibs/site/js/tabs.js, content/src/scripts/datalayer/v1/datalayer.js
- make sure document.body is available
| Fixed Issues?            | Fixes #1205 
| Documentation Provided   | NA
=> GH-1205 [DataLayer] document.body is null

content/package-lock.json, content/package.json
Updated Adobe Client Data Layer version from 1.1.0 to 1.1.1
=> Adobe Client Data Layer version 1.1.1

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/datalayer/AssetDataImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/datalayer/ComponentDataImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/datalayer/ContainerDataImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/datalayer/ImageDataImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/datalayer/PageDataImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/datalayer/builder/DataLayerSupplierImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/datalayer/builder/AssetDataBuilder.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/datalayer/builder/ComponentDataBuilder.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/datalayer/builder/ContainerDataBuilder.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/datalayer/builder/DataLayerBuilder.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/datalayer/builder/DataLayerSupplier.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/datalayer/builder/GenericComponentDataBuilder.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/datalayer/builder/GenericDataBuilder.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/datalayer/builder/ImageComponentDataBuilder.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/datalayer/builder/PageDataBuilder.java, content/package-lock.json, extensions/amp/content/package-lock.json, testing/junit/core/src/main/java/com/adobe/cq/wcm/core/components/testing/AbstractModelTest.java
| Fixed Issues?            | Fixes #1219 
=> Bundle exports DataLayerSupplier

content/package-lock.json, content/package.json
Updated Adobe Client Data Layer version from 1.1.1 to 1.1.2
=> Feature/adobe client data layer version 1.1.2

content/src/content/jcr_root/apps/core/wcm/components/carousel/v1/carousel/clientlibs/site/js/carousel.js, testing/it/ui-js/src/content/jcr_root/apps/core/wcm/tests/test-cases/Embed/v1/Embed.js, testing/it/ui-js/src/content/jcr_root/apps/core/wcm/tests/test-suites/Embed/v1/Embed.js
- add namespace for carousel component
- remove Facebook and Instagram test because of #1225
=> Fix failing hobbes test

content/package-lock.json, content/package.json
Updated Adobe Client Data Layer version from 1.1.2 to 1.1.3
=> Feature/adobe client data layer version 1.1.3

content/src/content/jcr_root/apps/core/wcm/components/image/v2/image/clientlibs/site/.content.xml
=> Enable ES6 for image client library

README.md, VERSIONS.md, content/package-lock.json, content/package.json, examples/ui.content/src/content/jcr_root/conf/core-components-examples/settings/wcm/templates/content-page/structure/.content.xml, examples/ui.content/src/content/jcr_root/content/core-components-examples/library/.content.xml, extensions/amp/content/package-lock.json, extensions/amp/content/package.json, testing/it/ui-js/package-lock.json, testing/it/ui-js/package.json
preparation work for next patch release 2.12.1
=> Update, README, Versions, Core Comp Library and npm version for next release

.github/workflows/maven-test-cloud.yml, .github/workflows/maven-test.yml, all/pom.xml, content/pom.xml, extensions/amp/content/pom.xml, parent/pom.xml
=> Simplify re-deploying `cloud` artifacts to a running AEM instance that already includes them #1262

content/pom.xml
=> Unhide component group for cloud/AEMaaCS artifacts

.github/workflows/maven-test.yml, BUILDING.md, README.md, content/package-lock.json, content/package.json, content/pom.xml, extensions/amp/content/package-lock.json, extensions/amp/content/package.json, extensions/amp/content/pom.xml, parent/pom.xml, testing/it/ui-js/package-lock.json, testing/it/ui-js/package.json, testing/it/ui-js/pom.xml
=> Added sync-pom-version-to-package

examples/ui.apps/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-base-amp/styles/base/text.less, examples/ui.apps/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-site/styles/components/text.less, examples/ui.content/pom.xml, examples/ui.content/src/content/jcr_root/conf/core-components-examples/settings/wcm/templates/content-page/structure/.content.xml, examples/ui.content/src/content/jcr_root/content/core-components-examples/library/.content.xml
* Updated version to pick up maven project version
* Updated CSS to allow for longer names (for snapshot versions)
Fixes #1320
=> [Library] Auto update Core Components version #1320

content/src/content/jcr_root/apps/core/wcm/components/page/v2/page/_cq_dialog/.content.xml
Move PWA tab to be included in properties only for supported page component
=> Add PWA tab for supported page component

examples/ui.apps/src/content/jcr_root/apps/core-components-examples/components/page/clientlibs/.content.xml, examples/ui.apps/src/content/jcr_root/apps/core-components-examples/components/page/clientlibs/amp/.content.xml, examples/ui.apps/src/content/jcr_root/apps/core-components-examples/components/page/clientlibs/amp/css.txt, examples/ui.apps/src/content/jcr_root/apps/core-components-examples/components/page/clientlibs/amp/css/page.less
| Fixed Issues?            | Fixes #1116 
* Switched from loading the base CSS via a new <style amp-custom> tag to embedding it in the page's AMP CSS
=> [AMP] Multiple style amp-custom elements per page #1116

testing/it/e2e/test-module/package-lock.json, testing/it/e2e/test-module/package.json
| Fixed Issues?            | Fixes #1356 
add missing node dependencies to package.json
=> wdio tests failed with node v13.13.0

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/TabsImpl.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/TabsImplTest.java
=>  Remove unused code, add more unit tests (#1096)

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/ContentFragmentUtils.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/ExperienceFragmentImpl.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/ExperienceFragmentImplTest.java, bundles/core/src/test/resources/experiencefragment/exporter-xf70.json
=> [Experience Fragment] Method getExportedItemsOrder order is incorrect

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/LocalizationUtils.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/NavigationImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/SearchImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/SearchResultServlet.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Search.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/SearchImplTest.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/servlets/SearchResultServletTest.java, bundles/core/src/test/resources/search/exporter-search.json, bundles/core/src/test/resources/search/exporter-search2.json, bundles/core/src/test/resources/search/test-conf.json, bundles/core/src/test/resources/search/test-content.json, content/src/content/jcr_root/apps/core/wcm/components/search/v1/search/search.html
Adds to PR #1253
Fixes #1249
Also adds to PR #1348
which fixes #835
=> [search] refactor the search logic

bundles/core/pom.xml, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/embeddable/YouTubeImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/embed/EmbedDesignTabsDataSourceServlet.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/embed/EmbeddablesDataSourceServlet.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/embeddable/YouTube.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/embeddable/package-info.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/embeddable/YouTubeImplTest.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/servlets/embed/EmbedDesignTabsDataSourceServletTest.java, bundles/core/src/test/resources/embed/embeddable/youtube/test-content.json, bundles/core/src/test/resources/embed/v1/datasources/embeddesigntabs/test-content.json, content/src/content/jcr_root/apps/core/wcm/components/embed/v1/embed/README.md, content/src/content/jcr_root/apps/core/wcm/components/embed/v1/embed/_cq_design_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/embed/v1/embed/clientlibs/editor/js/embed.js, content/src/content/jcr_root/apps/core/wcm/components/embed/v1/embed/embeddable/youtube/README.md, content/src/content/jcr_root/apps/core/wcm/components/embed/v1/embed/embeddable/youtube/_cq_design_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/embed/v1/embed/embeddable/youtube/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/embed/v1/embed/embeddable/youtube/youtube.html
| Fixed Issues?            | Fixes #1288
=> Enable configuration of YouTube Player parameters

content/src/content/jcr_root/apps/core/wcm/components/contentfragmentlist/v1/contentfragmentlist/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/image/v1/image/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/image/v2/image/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/pdfviewer/v1/pdfviewer/_cq_dialog/.content.xml
=> [dialog pickers] use specific node types

content/package-lock.json, content/package.json
Updated Adobe Client Data Layer version from 1.1.3 to 1.1.5
=> Adobe Client Data Layer version 1.1.5

content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion/clientlibs/site/js/accordion.js, content/src/content/jcr_root/apps/core/wcm/components/carousel/v1/carousel/clientlibs/site/js/carousel.js, content/src/content/jcr_root/apps/core/wcm/components/tabs/v1/tabs/clientlibs/site/js/tabs.js
=> Carousel throws JS error after first panel is added, required reload to work #1386

parent/pom.xml
Updates validator plugins to benefit from additional checks (https://github.com/Netcentric/aem-cloud-validator/issues?q=is%3Aissue+milestone%3A1.1+is%3Aclosed)
| Fixed Issues?            |  None
=> Update validator plugins

content/src/content/jcr_root/apps/core/wcm/components/teaser/v1/teaser/clientlibs/editor/js/teaser.js
* Moved input toggling to the end so that the actions checkbox is initialized and actions state computed
Fixes #1402
=> [Teaser] Actions multi-field of Teaser is not enabled on first access #1402

content/package.json, extensions/amp/content/package-lock.json
| Fixed Issues?            | Fixes #1405
=> [DataLayer] Add data layer v2.0.0 to the Core Components

examples/ui.content/src/content/jcr_root/conf/core-components-examples/settings/wcm/policies/.content.xml, examples/ui.content/src/content/jcr_root/conf/core-components-examples/settings/wcm/templates/content-page/policies/.content.xml
- Fix the style issue of the search box  on aemcomponents.dev.
Fixes #1442
=> Fix the style for the aemcomponents.dev search box (#1442)

content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion/clientlibs/site/js/accordion.js, content/src/content/jcr_root/apps/core/wcm/components/commons/site/clientlibs/container/js/containerUtils.js, content/src/content/jcr_root/apps/core/wcm/components/tabs/v1/tabs/clientlibs/site/js/tabs.js
=> Fix the issue with Deep Linking for Tabs and Accordion components (#1432)

content/src/content/jcr_root/apps/core/wcm/components/commons/editor/dialog/childreneditor/v1/childreneditor/childreneditor.html, content/src/content/jcr_root/apps/core/wcm/components/commons/editor/dialog/childreneditor/v1/childreneditor/clientlibs/js/childreneditor.js
- add copyFrom parameter when component is created via the children editor of a panel container
| Fixed Issues?            | Fixes #1463 
=> Consistent initialization of nested components

content/src/content/jcr_root/apps/core/wcm/components/search/v1/search/search.html
=> [Accessibility][Search] Clear button needs label for screen readers (#1433)

content/src/content/jcr_root/apps/core/wcm/components/image/v2/image/image.html
- always provide ALT attribute for image, in Image Component v2
Fixes #1467
=> [Accessibility][Image v2] Always provide the ALT attribute, even when empty (#1467)

content/src/content/jcr_root/apps/core/wcm/components/image/v2/image/image.html, content/src/content/jcr_root/apps/core/wcm/components/image/v3/image/image.html
- always provide ALT attribute for image, in the Image Component v3
Fixes #1467
=> [Accessibility][Image v3] Always provide the ALT attribute, even when empty (#1467)

content/src/content/jcr_root/apps/core/wcm/components/search/v1/search/clientlibs/site/js/search.js
=> [Accessibility][Search] Search component keyboard trap and tab navigation 

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/services/LatestVersionImplementationPicker.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/services/LatestVersionImplementationPickerTest.java, parent/pom.xml
- add implementation picker which returns the latest core component model if no resource type is matching
- add unit test
| Fixed Issues?            | Fixes #546 
=> Create latest version ImplementationPicker

content/src/content/jcr_root/apps/core/wcm/components/search/v1/search/clientlibs/site/js/search.js, content/src/content/jcr_root/apps/core/wcm/components/search/v1/search/itemTemplate.html, content/src/content/jcr_root/apps/core/wcm/components/search/v1/search/search.html
- added aria-expanded attribute on the search input
- added role and aria-selected attributes on the search results children
- added aria-label on the search results listbox
Fixes #1500
=> [Accessibility] [Search] Search component results listbox missing label and it's children missing required role

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/LayoutContainerImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/LayoutContainer.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/LayoutContainerImplTest.java, bundles/core/src/test/resources/container/exporter-container2.json, bundles/core/src/test/resources/container/test-content.json, content/src/content/jcr_root/apps/core/wcm/components/container/v1/container/README.md, content/src/content/jcr_root/apps/core/wcm/components/container/v1/container/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/container/v1/container/responsiveGrid.html, content/src/content/jcr_root/apps/core/wcm/components/container/v1/container/simple.html
Fixes the latest requirement from #1469
=> [Accessibility][Container] Allow authors to define role attribute on the container

examples/ui.apps/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-site/styles/components/progressbar.less, examples/ui.apps/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-themes/core-components-clean/styles/components/teaser/light.skin.less, examples/ui.apps/src/content/jcr_root/apps/core-components-examples/components/progressbar/clientlibs/amp/css/progressbar.less
- Improves the color contrast for Progressbar and Carousel on the on the AEM Components Library
Fixes #1475
=> [Accessibility] Insufficient color contrast

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/DMAssetPostProcessor.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/servlets/DMAssetPostProcessorTest.java, bundles/core/src/test/resources/image/v2/test-content.json
=> Support image drag-and-drop operation directly into the page

content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion/clientlibs/site/js/accordion.js
=> [Accessibility][Accordion]Single Item Expansion aria-expanded state not read properly in VO + Safari 

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/DownloadImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Download.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/DownloadImplTest.java, content/src/content/jcr_root/apps/core/wcm/components/download/v1/download/README.md, content/src/content/jcr_root/apps/core/wcm/components/download/v1/download/_cq_design_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/download/v1/download/download.html
* Added content policy option to remove title link
* Added accessibility attributes to links
* Updated README
* Added test
Fixes #737
=> [Download][Accessibility] Duplicate links, can't add additional information to link text #737

bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/NavigationImplTest.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v2/ListImplTest.java, bundles/core/src/test/resources/list/v2/exporter-staticWithVanityPaths.json, bundles/core/src/test/resources/list/v2/test-content.json, bundles/core/src/test/resources/navigation/exporter-navigation19.json, bundles/core/src/test/resources/navigation/test-content.json
* This is fixed by the new LinkHandler (#713), just adding specific tests
Closes #559
=> [Link Handling][List] Apply URL mapping and vanity URLs to list links

content/src/content/jcr_root/apps/core/wcm/components/embed/v1/embed/README.md, content/src/content/jcr_root/apps/core/wcm/components/embed/v1/embed/_cq_design_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/embed/v1/embed/clientlibs/editor/js/embed.js, content/src/content/jcr_root/apps/core/wcm/components/embed/v1/embed/embeddable/youtube/_cq_design_dialog/.content.xml
| Fixed Issues?            | Fixes #1481 
=> Fix Design Dialog for custom embeddable

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/jackson/LinkHtmlAttributesSerializer.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/link/LinkHandler.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/link/LinkImpl.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/link/LinkImplTest.java, bundles/core/src/test/resources/title/exporter-title-jcr-title-link-v2.json, bundles/core/src/test/resources/title/exporter-title-linkdisabled.json
- small code changes 
Fixes #668
=> [Title][Accessibility] Possibility of adding description related to link in Title component(small improvements)

examples/ui.content/src/content/META-INF/vault/filter.xml, examples/ui.content/src/content/jcr_root/conf/core-components-examples/settings/wcm/templates/content-page/structure/.content.xml, examples/ui.content/src/content/jcr_root/content/core-components-examples/library/.content.xml
@review @rismehta @vdua
| Fixed Issues?            |  Filter exclusion of forms components 
| Patch: Bug Fix?          |  Yes
| Minor: New Feature?      |  No
| Major: Breaking Change?  |  No
Add filters for excluding paths specific to aem-core-forms-components repository to prevent overwriting and maintain order when installing this repository's examples
Also mark the fore-mentioned components for default expansion in accordion
=> CQ-4305012 Filter exceptions for forms components

testing/it/http/src/test/java/com/adobe/cq/wcm/core/components/it/http/LinkHandlerIT.java, testing/it/ui-js/src/content/jcr_root/content/core-components/.content.xml, testing/it/ui-js/src/content/jcr_root/content/core-components/simple-page/.content.xml
- add IT for the LinkHandler based on a linked Title component
=> Add IT for LinkHandler

testing/it/e2e-selenium/pom.xml, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/AuthorBaseUITest.java, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/components/languagenavigation/v1/LanguageNavigation.java, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/components/navigation/v1/Navigation.java, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/components/search/SearchEditDialog.java, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/components/search/v1/Search.java, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/components/tabs/TabsEditDialog.java, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/components/tabs/v1/Tabs.java, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/accordion/v1/AccordionIT.java, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/breadcrumb/BreadcrumbTests.java, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/carousel/v1/CarouselIT.java, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/formhidden/v2/FormHiddenIT.java, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/image/ImageTests.java, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/image/v2/ImageIT.java, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/search/v1/SearchIT.java, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/tabs/v1/TabsIT.java, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/util/Commons.java
=> Hobbes to Selenium IT migration

content/src/content/jcr_root/apps/core/wcm/components/container/v1/container/simple.html
| Fixed Issues?            | Resolves https://github.com/adobe/aem-core-wcm-components/issues/1557 
| Documentation Provided   | No Change
=> container: Remove redundant data-sly-test

bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v2/ButtonImplTest.java, bundles/core/src/test/resources/button/v2/exporter-button1.json, bundles/core/src/test/resources/button/v2/test-content.json, content/src/content/jcr_root/apps/core/wcm/components/button/v2/button/README.md, content/src/content/jcr_root/apps/core/wcm/components/button/v2/button/_cq_dialog/.content.xml, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/components/button/ButtonEditDialog.java, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/components/button/v1/Button.java, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/button/v1/ButtonIT.java, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/button/v2/ButtonIT.java
- add checkbox to button dialog to set link target attribute
- add button e2e test to test new checkox
- update readme of button v2 component
- adapt unit test
| Fixed Issues?            | Fixes #1600 
| Patch: Bug Fix?          | 👎
| Minor: New Feature?      |  👍
=> [Button] Allow to open links in new tabs

testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/navigation/v1/NavigationIT.java
Adapts the new Selenium tests for the changes made in #1580.
=> Adapt Selenium Tests for Changes made in #1580

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/EnhancedRendition.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/servlets/EnhancedRenditionTest.java, parent/pom.xml, testing/junit/core/src/main/java/com/adobe/cq/wcm/core/components/testing/MockHtmlLibraryManager.java
- update uber-jar dependency to 6.4.8.4-1.0
- revert API changes to MockHtmlLibraryManager and EnhancedRendition
fixes #1612
| Fixed Issues?            | Fixes #1612 
| Patch: Bug Fix?          | 👎
| Tests Added + Pass?      | 👎
| Documentation Provided   | 👎
| Any Dependency Changes?  | 👍
=> [StyleSystem/SPAEditor] Update uber-jar to keep support for AEM 6.4

content/package.json
- add new released version of ACDL
| Fixed Issues?            | Fixes #1620
=> [DataLayer] Add ACDL v2.0.2 to the Core Components

content/src/content/jcr_root/apps/core/wcm/components/image/v2/image/clientlibs/site/js/image.js
| Fixed Issues?            | Fixes #1581
Moved check for case of empty IMG src attribute.
=> Moved check for empty src attribute

content/src/content/jcr_root/apps/core/wcm/components/image/v2/image/clientlibs/editor/js/image.js
| Fixed Issues?            | Fixes #1635 
| Any Dependency Changes?  | 👎
=> Fix JS error if asset tab is hidden

testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/commons/DataLayerIT.java
Adds Selenium test for DataLayer Integration #1649
=> Selenium test for DataLayer Integration

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServlet.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/EnhancedRendition.java
| Fixed Issues?            | Fixes #1627
=> Removing extension of Rendition from EnhancedRendition

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/LanguageNavigationImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/LanguageNavigation.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/package-info.java, content/src/content/jcr_root/apps/core/wcm/components/languagenavigation/v1/languagenavigation/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/languagenavigation/v1/languagenavigation/languagenavigation.html, content/src/content/jcr_root/apps/core/wcm/components/languagenavigation/v2/languagenavigation/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/languagenavigation/v2/languagenavigation/languagenavigation.html
- No label for Language Navigation
Fixes #1671
=> [Accessibility] [Language Navigation] No label for Language Navigation

content/src/content/jcr_root/apps/core/wcm/components/languagenavigation/v1/languagenavigation/itemContent.html, content/src/content/jcr_root/apps/core/wcm/components/languagenavigation/v2/languagenavigation/itemContent.html, content/src/content/jcr_root/apps/core/wcm/components/navigation/v1/navigation/itemContent.html, content/src/content/jcr_root/apps/core/wcm/components/navigation/v2/navigation/itemContent.html
- link text announced twice
Fixes #1670
=> [Accessibility][Navigation][Language Navigation] Link text announced twice

content/src/content/jcr_root/apps/core/wcm/components/navigation/v1/navigation/navigation.html, content/src/content/jcr_root/apps/core/wcm/components/navigation/v2/navigation/navigation.html
- nav element has unnecessary navigation role
Fixes #1669
=> [Accessibility] [Advisory] [Navigation] nav element has unnecessary navigation role

testing/it/http/src/test/java/com/adobe/cq/wcm/core/components/it/http/SeoIT.java
=> fix dynamic port issue on publisher

content/src/content/jcr_root/apps/core/wcm/components/list/v3/list/item.html
| Fixed Issues?            | `Fixes #627` 
| Major: Breaking Change?  | No as it's only applied in the new v3 version of the list component
=> [List] Remove article element (#627)

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/link/LinkHandler.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/BreadcrumbImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/BreadcrumbItemImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/LanguageNavigationImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/LanguageNavigationItemImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/NavigationImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/NavigationItemImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/PageListItemImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v2/LanguageNavigationImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v2/LanguageNavigationItemImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v2/ListImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v2/NavigationImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v2/NavigationItemImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v2/PageListItemImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v3/BreadcrumbImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v3/BreadcrumbItemImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v3/ListImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/SearchResultServlet.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/link/LinkTestUtils.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/NavigationImplTest.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v2/NavigationItemImplTest.java, bundles/core/src/test/resources/navigation/exporter-navigation16.json, bundles/core/src/test/resources/navigation/exporter-navigation17.json, bundles/core/src/test/resources/navigation/exporter-navigation9.json, bundles/core/src/test/resources/navigation/test-content.json, bundles/core/src/test/resources/navigation/v2/exporter-navigation16.json, bundles/core/src/test/resources/navigation/v2/exporter-navigation17.json, bundles/core/src/test/resources/navigation/v2/exporter-navigation9.json, bundles/core/src/test/resources/navigation/v2/test-content.json
* Resolve redirect chain in the link handler
=> [List][Navigation] Display external URL redirect targets (#1713)

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/link/LinkHandler.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/TitleImplTest.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v3/TitleImplTest.java, bundles/core/src/test/resources/title/exporter-title-v2-redirect-chain.json, bundles/core/src/test/resources/title/exporter-title-v2-redirect-external-url.json, bundles/core/src/test/resources/title/test-content.json, bundles/core/src/test/resources/title/v3/exporter-title-redirect-chain.json, bundles/core/src/test/resources/title/v3/exporter-title-redirect-external-url.json, bundles/core/src/test/resources/title/v3/test-content.json
- for resource links to pages, crawl redirect targets by delegating to getting a page link
- adds JUnit test cases in the title component
| Fixed Issues?            | `Fixes #1713` 
=> [LinkHandler] Display external URL redirect targets (#1713)

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServlet.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServletTest.java
* Best rendition should be picked by image type and width
Fixes #1659
=> Image Core Components - Rendition needs to be chosen by the width of the image and not by filesize

parent/pom.xml
updates com.fasterxml.jackson.core to version provided by AEM 6.4.8.4
=> SITES-2246 update com.fasterxml.jackson.core to 2.10.3

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/ContainerServlet.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/CarouselImplTest.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/servlets/ContainerServletTest.java, bundles/core/src/test/resources/carousel/exporter-carousel1.json, bundles/core/src/test/resources/carousel/exporter-carousel1a.json, bundles/core/src/test/resources/carousel/test-content.json
- replaces deleted items that have a live relationship, with a ghost
- adds test case
| Fixed Issues?            | fixes #1825 
=> [ContainerServlet] Deleting an item does not create a placeholder for a deleted inherited component

content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion/clientlibs/site/js/accordion.js, content/src/content/jcr_root/apps/core/wcm/components/tabs/v1/tabs/clientlibs/site/js/tabs.js
- adds checks for existence of utils namespace
| Fixed Issues?            | `Fixes #1833` 
=> [Tabs][Accordion] make container util usages more robust

.github/workflows/maven-deploy-it-content.yml
Updates internal AEMaaCS program so we can run IT HTTP tests against it.
=> Add GitHub Action to deploy to Test Env on AEMaaCS

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/EnhancedRendition.java
- avoid parsing a null object
| Fixed Issues?            | Fixes #1842 
=> GH-1842 - [image v3] logs flooded with parsing errors

examples/ui.content/src/content/jcr_root/conf/core-components-examples/settings/wcm/policies/.content.xml, examples/ui.content/src/content/jcr_root/conf/core-components-examples/settings/wcm/templates/content-page/policies/.content.xml
* Added content policy for the image component with allowed widths
Fixes #1886
=> [Library] Images in the Components Library should have allowed widths configured

examples/ui.content/src/content/jcr_root/content/core-components-examples/library/core-content/accordion/.content.xml
| Fixed Issues?            | Fixes #1784 
| Patch: Bug Fix?          | 👎 (minor improvement)
=> [Accessibility][Accordion] Configurable heading levels

testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/teaser/v2/TeaserIT.java
Solved a failing selenium test
=> [Accessibility][Teaser] Avoid duplicate links in teaser v3

content/src/content/jcr_root/apps/core/wcm/components/breadcrumb/v3/breadcrumb/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/breadcrumb/v3/breadcrumb/README.md, content/src/content/jcr_root/apps/core/wcm/components/button/v2/button/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/button/v2/button/README.md, content/src/content/jcr_root/apps/core/wcm/components/contentfragmentlist/v2/contentfragmentlist/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/contentfragmentlist/v2/contentfragmentlist/README.md, content/src/content/jcr_root/apps/core/wcm/components/download/v2/download/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/download/v2/download/README.md, content/src/content/jcr_root/apps/core/wcm/components/embed/v2/embed/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/embed/v2/embed/README.md, content/src/content/jcr_root/apps/core/wcm/components/experiencefragment/v2/experiencefragment/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/experiencefragment/v2/experiencefragment/README.md, content/src/content/jcr_root/apps/core/wcm/components/image/v3/image/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/image/v3/image/README.md, content/src/content/jcr_root/apps/core/wcm/components/languagenavigation/v2/languagenavigation/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/languagenavigation/v2/languagenavigation/README.md, content/src/content/jcr_root/apps/core/wcm/components/list/v3/list/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/list/v3/list/README.md, content/src/content/jcr_root/apps/core/wcm/components/navigation/v2/navigation/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/navigation/v2/navigation/README.md, content/src/content/jcr_root/apps/core/wcm/components/page/v3/page/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/page/v3/page/README.md, content/src/content/jcr_root/apps/core/wcm/components/teaser/v2/teaser/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/teaser/v2/teaser/README.md, content/src/content/jcr_root/apps/core/wcm/components/title/v3/title/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/title/v3/title/README.md
- replace the "work-in-progress" tag with "production-ready"
| Fixed Issues?            | Fixes #1980 
=> GH-1980 - Make the new components GA

content/src/content/jcr_root/apps/core/wcm/components/commons/editor/dialog/pageimagethumbnail/v1/pageimagethumbnail/pageimagethumbnail.html, content/src/content/jcr_root/apps/core/wcm/components/commons/v1/clientlibs/editor/checkboxTextfieldTuple/checkboxTextfieldTuple.js, content/src/content/jcr_root/apps/core/wcm/components/image/v3/image/clientlibs/editor/js/image.js
=> fix failing teaserITs

content/src/content/jcr_root/apps/core/wcm/components/navigation/v1/navigation/clientlibs/editor/js/navigation.js
=> [Nav V2] 'Structure Depth' editable after reopening Dialog after 'Collect all child pages' was checked

content/src/content/jcr_root/apps/core/wcm/components/teaser/v2/teaser/clientlibs/editor/css/teaser.less
=> [Teaser v2] Tooltip window for CTA checkbox way to small

examples/ui.apps/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-site/styles/components/teaser.less
=> SITES-5029 - [Component Library] Teaser Links to documentation, icons are wrong

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/TeaserImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v2/TeaserImpl.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/TeaserImplTest.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v2/TeaserImplTest.java, bundles/core/src/test/resources/teaser/v2/exporter-teaser10.json, bundles/core/src/test/resources/teaser/v2/exporter-teaser11.json, bundles/core/src/test/resources/teaser/v2/exporter-teaser21.json, bundles/core/src/test/resources/teaser/v2/exporter-teaser23.json, bundles/core/src/test/resources/teaser/v2/exporter-teaser23a.json, bundles/core/src/test/resources/teaser/v2/exporter-teaser25.json, bundles/core/src/test/resources/teaser/v2/exporter-teaser9.json, bundles/core/src/test/resources/teaser/v2/exporter-template_teaser1.json, bundles/core/src/test/resources/teaser/v2/exporter-template_teaser3.json, bundles/core/src/test/resources/teaser/v2/test-content.json, content/src/content/jcr_root/apps/core/wcm/components/teaser/v2/teaser/README.md, content/src/content/jcr_root/apps/core/wcm/components/teaser/v2/teaser/teaser.html, content/src/content/jcr_root/apps/core/wcm/components/teaser/v2/teaser/title.html, examples/ui.apps/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-base-amp/styles/base/teaser.less, examples/ui.apps/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-site/styles/components/teaser.less, testing/it/e2e-selenium-utils/src/main/java/com/adobe/cq/wcm/core/components/it/seljup/util/components/teaser/v1/Teaser.java, testing/it/e2e-selenium-utils/src/main/java/com/adobe/cq/wcm/core/components/it/seljup/util/components/teaser/v2/Teaser.java, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/teaser/v2/TeaserIT.java
-  decouple main link from CTA
- adapt unit tests
- link whole teaser if only main link without CTA is set
| Fixed Issues?            | Fixes #2018 
=> [Teaser-v2] main link not displayed when CTAs are defined

content/src/content/jcr_root/apps/core/wcm/components/page/v3/page/headlibs.html, testing/it/http/src/test/java/com/adobe/cq/wcm/core/components/it/http/page/v3/PageIT.java
- remove async attribute from script tag for shared libs
- append IT to verify result
#fixes 2040
| Fixed Issues?            | Fixes #2040 
=> CC 2.18 Page V3 jQuery is not defined, _g is not define

CONTRIBUTING.md
=> Update branch guideline

content/src/content/jcr_root/apps/core/wcm/components/commons/editor/clientlibs/panelselect/js/panelselect.js
- enable panel selector for panel container with only one element
fixes #2023
| Fixed Issues?            | Fixes #2023 
=> Accordion] Possibility to edit a single container

content/src/content/jcr_root/apps/core/wcm/components/commons/editor/dialog/childreneditor/v1/childreneditor/clientlibs/js/childreneditor.js
* Added localization for items in the elements selector
Fixes #2082
=> [Tabs][i18n] Some strings in the edit dialog of Tabs component are not localized. 

testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/AuthorBaseUITest.java, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/commons/DataLayerIT.java, testing/it/it.ui.apps/src/content/jcr_root/apps/core/wcm/tests/clientlibs/clientlib-base/.content.xml, testing/it/it.ui.content/src/content/jcr_root/conf/core-components/_rep_policy.xml
* Fix datalayer IT on 6.5.0
#2032
=> Make Core Component Selenium Tests run against AEMaaCS

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/ContentFragmentUtils.java, testing/it/http/src/test/java/com/adobe/cq/wcm/core/components/it/http/experiencefragment/v2/ExperienceFragmentIT.java, testing/it/http/src/test/resources/xf-page.model.json, testing/it/it.ui.apps/src/content/jcr_root/apps/core-component/components/experiencefragment-v2/.content.xml, testing/it/it.ui.apps/src/content/jcr_root/apps/core-component/components/xfpage/.content.xml, testing/it/it.ui.content/src/content/jcr_root/conf/core-components/settings/wcm/policies/.content.xml, testing/it/it.ui.content/src/content/jcr_root/conf/core-components/settings/wcm/template-types/empty-experience-fragment/.content.xml, testing/it/it.ui.content/src/content/jcr_root/conf/core-components/settings/wcm/template-types/empty-experience-fragment/initial/.content.xml, testing/it/it.ui.content/src/content/jcr_root/conf/core-components/settings/wcm/template-types/empty-experience-fragment/policies/.content.xml, testing/it/it.ui.content/src/content/jcr_root/conf/core-components/settings/wcm/template-types/empty-experience-fragment/structure/.content.xml, testing/it/it.ui.content/src/content/jcr_root/conf/core-components/settings/wcm/templates/experience-fragment-web-variation-template/.content.xml, testing/it/it.ui.content/src/content/jcr_root/conf/core-components/settings/wcm/templates/experience-fragment-web-variation-template/initial/.content.xml, testing/it/it.ui.content/src/content/jcr_root/conf/core-components/settings/wcm/templates/experience-fragment-web-variation-template/policies/.content.xml, testing/it/it.ui.content/src/content/jcr_root/conf/core-components/settings/wcm/templates/experience-fragment-web-variation-template/structure/.content.xml, testing/it/it.ui.content/src/content/jcr_root/conf/core-components/settings/wcm/templates/simple-template-v3/policies/.content.xml, testing/it/it.ui.content/src/content/jcr_root/content/core-components/.content.xml, testing/it/it.ui.content/src/content/jcr_root/content/core-components/simple-page/.content.xml, testing/it/it.ui.content/src/content/jcr_root/content/core-components/simple-page/test-page-xf-component/.content.xml, testing/it/it.ui.content/src/content/jcr_root/content/experience-fragments/core-components-test/.content.xml, testing/it/it.ui.content/src/content/jcr_root/content/experience-fragments/core-components-test/container-experience-fragment/.content.xml, testing/it/it.ui.content/src/content/jcr_root/content/experience-fragments/core-components-test/container-experience-fragment/master/.content.xml
- adapt xf page resource to TemplatedResource (if possible) which is aware of structure support
| Fixed Issues?            | Fixes #2112 
=> Style system not working for Container/Layout Container

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v2/ButtonImpl.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/ButtonImplTest.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v2/ButtonImplTest.java, bundles/core/src/test/resources/button/v2/exporter-button2.json, bundles/core/src/test/resources/button/v2/test-content.json, content/src/content/jcr_root/apps/core/wcm/components/button/v2/button/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/button/v2/button/clientlibs/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/button/v2/button/clientlibs/editor/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/button/v2/button/clientlibs/editor/js.txt, content/src/content/jcr_root/apps/core/wcm/components/button/v2/button/clientlibs/editor/js/button.js, testing/it/e2e-selenium-utils/src/main/java/com/adobe/cq/wcm/core/components/it/seljup/util/components/button/ButtonEditDialog.java, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/button/v2/ButtonIT.java
- make the link field display the linkURL property if it exists, otherwise the link property
- remove the link property from the JCR repository when submitting the button dialog
- add Junit and UI (Selenium) tests
| Fixed Issues?            | Fixes #2125 
=> [Button] Support both link and linkURL properties in Button v2

content/src/content/jcr_root/apps/core/wcm/components/title/v2/title/clientlibs/editor/js/title.js, testing/it/e2e-selenium-utils/src/main/java/com/adobe/cq/wcm/core/components/it/seljup/util/components/title/TitleEditDialog.java, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/title/v2/TitleIT.java
=> SITES-5721 [Title] - Policy Change should not reset default type

examples/ui.content/src/content/jcr_root/content/core-components-examples/library/core-content/.content.xml, examples/ui.content/src/content/jcr_root/content/core-components-examples/library/core-form/.content.xml, examples/ui.content/src/content/jcr_root/content/core-components-examples/library/core-structure/.content.xml, examples/ui.content/src/content/jcr_root/content/core-components-examples/library/core-structure/page/.content.xml
=> SITES-5486 - [Component Library] Add a page for the Page component

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/AllowedHeadingElementsDataSourceServlet.java, content/src/content/jcr_root/apps/core/wcm/components/teaser/v1/teaser/_cq_design_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/teaser/v1/teaser/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/teaser/v1/teaser/clientlibs/design/js/teaser.js, content/src/content/jcr_root/apps/core/wcm/components/teaser/v1/teaser/clientlibs/editor/js/teaser.js, content/src/content/jcr_root/apps/core/wcm/components/teaser/v2/teaser/_cq_design_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/teaser/v2/teaser/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/teaser/v2/teaser/clientlibs/editor/js/teaser.js, testing/it/e2e-selenium-utils/src/main/java/com/adobe/cq/wcm/core/components/it/seljup/util/components/teaser/v1/TeaserEditDialog.java, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/teaser/v1/TeaserIT.java
=> SITES-5872-[Teaser] Allow title heading levels to be restricted by policy

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/AllowedHeadingElementsDataSourceServlet.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/servlets/AllowedHeadingElementsDataSourceServletTest.java, content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion/_cq_design_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/teaser/v1/teaser/_cq_design_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/teaser/v2/teaser/_cq_design_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/title/v2/title/_cq_design_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/title/v2/title/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/title/v2/title/clientlibs/editor/js/title.js, content/src/content/jcr_root/apps/core/wcm/components/title/v3/title/_cq_design_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/title/v3/title/_cq_dialog/.content.xml, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/teaser/v1/TeaserIT.java, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/title/v1/TitleIT.java, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/title/v2/TitleIT.java
=> SITES-5925-[Title] Align size config with accordion

examples/ui.content/src/content/jcr_root/content/core-components-examples/library/core-content/.content.xml, examples/ui.content/src/content/jcr_root/content/core-components-examples/library/core-content/search/.content.xml
Quick Search Page introduced in the Components Library.
=> [library] Quick Search Page created.

content/src/content/jcr_root/apps/core/wcm/components/image/v2/image/clientlibs/editor/js/image.js, content/src/content/jcr_root/apps/core/wcm/components/image/v3/image/clientlibs/editor/js/image.js, testing/it/e2e-selenium-utils/src/main/java/com/adobe/cq/wcm/core/components/it/seljup/util/components/teaser/v1/TeaserEditDialog.java, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/teaser/v2/TeaserIT.java
=> Improve alt text validation for Image Component

content/src/content/jcr_root/apps/core/wcm/components/form/options/v1/options/options.html, content/src/content/jcr_root/apps/core/wcm/components/form/options/v2/options/options.html, content/src/content/jcr_root/apps/core/wcm/components/form/text/v1/text/text.html, content/src/content/jcr_root/apps/core/wcm/components/form/text/v2/text/text.html, testing/it/e2e-selenium-utils/src/main/java/com/adobe/cq/wcm/core/components/it/seljup/util/components/formoptions/BaseFormOptions.java, testing/it/e2e-selenium-utils/src/main/java/com/adobe/cq/wcm/core/components/it/seljup/util/components/formtext/BaseFormText.java, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/formoptions/v1/FormOptionsIT.java, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/formtext/FormTextTests.java, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/formtext/v1/FormTextIT.java
=> SITES-6343 [Accessibility][Forms Components] Help Message is not programmatically associated with the field

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/Utils.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/form/Field.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/form/package-info.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/servlets/FormActionRpcServletTest.java, bundles/core/src/test/resources/form/form-rpc-servlet/test-content.json
* Added filtering of field names before sending to the remote endpoint
Fixes #2093
=> Security Concern - AEM WCM Core Form RPC Submission #2093

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/ImageArea.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/TableOfContents.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/contentfragment/DAMContentFragment.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/services/embed/OEmbedResponse.java
=> @releng add missing javadoc

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServlet.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServletTest.java, testing/it/http/src/test/java/com/adobe/cq/wcm/core/components/it/http/AdaptiveImageServletIT.java, testing/it/it.ui.content/src/content/jcr_root/content/core-components/adaptive-image-servlet/.content.xml, testing/it/it.ui.content/src/content/jcr_root/content/core-components/adaptive-image-servlet/image-with-policy/.content.xml, testing/it/it.ui.content/src/content/jcr_root/content/core-components/adaptive-image-servlet/image-without-policy/.content.xml
This pull request:
- is based on pull request #2225 made by @rpapani 
- adds an HTTP test
| Fixed Issues?            | Fixes #2209 
=> AdaptiveImageServlet isn't respecting the contentPolicyDelegatePath

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServlet.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServletTest.java, parent/pom.xml, testing/it/e2e-selenium-utils/src/main/java/com/adobe/cq/wcm/core/components/it/seljup/util/components/download/DownloadEditDialog.java, testing/it/e2e-selenium-utils/src/main/java/com/adobe/cq/wcm/core/components/it/seljup/util/components/embed/UrlProcessors.java, testing/it/e2e-selenium-utils/src/main/java/com/adobe/cq/wcm/core/components/it/seljup/util/components/image/ImageEditDialog.java, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/accordion/v1/AccordionIT.java, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/image/ImageTests.java, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/page/PageTests.java, testing/it/http/src/test/java/com/adobe/cq/wcm/core/components/it/http/AdaptiveImageServletIT.java, testing/it/http/src/test/java/com/adobe/cq/wcm/core/components/it/http/experiencefragment/v2/ExperienceFragmentIT.java, testing/it/http/src/test/resources/simple-page.model.json
Updated ITs after `aem-selenium-it-base` bump in https://github.com/adobe/aem-core-wcm-components/pull/2241/files#diff-ca417a813458297fc1733e421ee5ed6870eb81b75b450af48007a153db4b9ad4L64
* AccordionIT
=> Updated ITs after `aem-selenium-it-base` bump

content/src/content/jcr_root/apps/core/wcm/components/image/v3/image/clientlibs/editor/js/image.js, content/src/content/jcr_root/apps/core/wcm/components/image/v3/image/clientlibs/site/js/image.js, content/src/content/jcr_root/apps/core/wcm/components/image/v3/image/image.html, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/image/ImageTests.java
- remove console.log form image.js
- remove auto sizes leftovers from the HTL script and content policy dialog
=> Add sizes capabilities to ImageV3 component (#2249)

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/contentfragment/ModelElementsDataSourceServlet.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/servlets/contentfragment/ModelElementsDataSourceServletTest.java
- extend datasource orderBy check with V2 component version
- add unit test for V2 datasource
fixes #2262
| Fixed Issues?            | Fixes #2262
=> [ContentFragmentList] Fix sortby

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v3/ImageImpl.java, bundles/core/src/test/resources/image/v3/exporter-image38-one-smart-size.json, bundles/core/src/test/resources/image/v3/exporter-image38-two-smart-sizes.json, content/src/content/jcr_root/apps/core/wcm/components/image/v3/image/clientlibs/site/js/image.js, content/src/content/jcr_root/apps/core/wcm/components/image/v3/image/image.html
- prevent race condition between imageV2 and imageV3
- return empty pixel for srcset attribute if image is dm and smart crop auto is activated
=> [ImageV3] Fix issues with DM after review

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/embed/EmbeddableOptionsDataSourceServlet.java
Fix possible NPE in EmbeddableOptionsDataSourceServlet
SITES-7039
=> fix NPE in EmbeddableOptionsDataSourceServlet

content/src/content/jcr_root/apps/core/wcm/components/commons/editor/clientlibs/panelselect/css/panelselector.less
=> Checkmark icon overlaying text when opening 'Select panel' dropdown

extensions/amp/bundle/src/main/java/com/adobe/cq/wcm/core/extensions/amp/internal/AmpModeForwardFilter.java, extensions/amp/bundle/src/test/java/com/adobe/cq/wcm/core/extensions/amp/internal/AmpModeForwardFilterTest.java
| Fixed Issues?            | Fixes #2338 
Allow to disable the AmpModeForwardFilter to reduce execution time.
=> #2338 allow to disable the AmpModeForwardFilter

bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/TeaserImplTest.java, bundles/core/src/test/resources/teaser/test-content.json, bundles/core/src/test/resources/teaser/v2/test-content.json
- add tests for Teaser v1 and v2
| Fixed Issues?            | Fixes #2335
=> [Teaser] Add tests for links with special character

extensions/amp/bundle/src/main/java/com/adobe/cq/wcm/core/extensions/amp/internal/AmpModeForwardFilter.java, extensions/amp/bundle/src/test/java/com/adobe/cq/wcm/core/extensions/amp/internal/AmpModeForwardFilterTest.java
| Fixed Issues?            | Fixes #2361
=> #2361 fix the AmpModeForwardFilter

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/contentfragment/ModelElementsDataSourceServlet.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/servlets/contentfragment/ModelElementsDataSourceServletTest.java
=> Allow to sort on date fields for content fragment lists

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/ImageImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v3/ImageImpl.java
Remove a few cases of redundant repository access.
| Fixed Issues?            |  -
| Patch: Bug Fix?          | Performance improvement
| Minor: New Feature?      | -
| Major: Breaking Change?  | -
| Tests Added + Pass?      | -
=> Remove redundant repository access in the ImageImpl

parent/pom.xml, testing/it/e2e-selenium-utils/pom.xml, testing/it/e2e-selenium-utils/src/main/java/com/adobe/cq/wcm/core/components/it/seljup/util/Commons.java, testing/it/e2e-selenium-utils/src/main/java/com/adobe/cq/wcm/core/components/it/seljup/util/components/button/ButtonEditDialog.java, testing/it/e2e-selenium-utils/src/main/java/com/adobe/cq/wcm/core/components/it/seljup/util/components/embed/EmbedEditDialog.java, testing/it/e2e-selenium-utils/src/main/java/com/adobe/cq/wcm/core/components/it/seljup/util/components/embed/UrlProcessors.java, testing/it/e2e-selenium-utils/src/main/java/com/adobe/cq/wcm/core/components/it/seljup/util/components/image/ImageEditDialog.java, testing/it/e2e-selenium-utils/src/main/java/com/adobe/cq/wcm/core/components/it/seljup/util/components/page/v1/Page.java, testing/it/e2e-selenium-utils/src/main/java/com/adobe/cq/wcm/core/components/it/seljup/util/components/title/TitleEditDialog.java, testing/it/e2e-selenium-utils/src/main/java/com/adobe/cq/wcm/core/components/it/seljup/util/constant/RequestConstants.java, testing/it/e2e-selenium/pom.xml, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/accordion/v1/AccordionIT.java, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/breadcrumb/BreadcrumbTests.java, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/button/v1/ButtonIT.java, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/carousel/v1/CarouselIT.java, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/formbutton/v1/FormButtonIT.java, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/tabs/v1/TabsIT.java
=> @releng: Update dependency to aem-selenium-it-base to latest version

.github/workflows/maven-deploy-it-content.yml, .github/workflows/maven-deploy-to-library.yml, .github/workflows/maven-deploy.yml, .github/workflows/maven-release.yml, .github/workflows/maven-test.yml, content/src/content/jcr_root/apps/core/wcm/components/commons/site/clientlibs/imageDynamicMedia/js/imageDynamicMedia.js, content/src/content/jcr_root/apps/core/wcm/components/commons/site/clientlibs/utils/js/utils.js, content/src/content/jcr_root/apps/core/wcm/components/image/v2/image/clientlibs/editor/js/image.js, content/src/content/jcr_root/apps/core/wcm/components/image/v3/image/clientlibs/editor/js/image.js
=> @releng: Remove JS Doc warnings

testing/it/http/src/test/java/com/adobe/cq/wcm/core/components/it/http/ComponentsIT.java, testing/it/http/src/test/resources/components/separator-v1-decorative.html, testing/it/http/src/test/resources/components/separator-v1-defaults.html, testing/it/it.ui.content/src/content/jcr_root/content/core-components/separator/.content.xml
| Fixed Issues?            | Fixes SITES-9646
Added integration tests for Separator component.
=> SITES-9646 - Add coverage for Separator Component

.github/codecov.yml
=> @releng: add config for codecov

parent/pom.xml, testing/it/e2e-selenium-utils/src/main/java/com/adobe/cq/wcm/core/components/it/seljup/util/components/accordion/AccordionEditDialog.java, testing/it/e2e-selenium-utils/src/main/java/com/adobe/cq/wcm/core/components/it/seljup/util/components/contentfragment/ContentFragmentEditDialog.java, testing/it/e2e-selenium-utils/src/main/java/com/adobe/cq/wcm/core/components/it/seljup/util/components/teaser/v1/TeaserEditDialog.java, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/accordion/v1/AccordionIT.java, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/image/ImageTests.java
fix broken selenium ITs for AEM 6.5
=> fix: selenium ui tests for aem 6.5

examples/ui.content/src/content/META-INF/vault/filter.xml, examples/ui.content/src/content/jcr_root/conf/core-components-examples/settings/wcm/templates/content-page/structure/.content.xml, examples/ui.content/src/content/jcr_root/content/core-components-examples/library/.content.xml
| Fixed Issues?            | `CQ-4351085` 
Filter exceptions for adaptive forms components, so that they are listed in aemcomponents.dev
=> CQ-4351085 Filter exceptions for adaptive form components

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v2/ImageImpl.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v3/ImageImplTest.java, bundles/core/src/test/resources/image/v3/exporter-image36-one-smart-size.json, bundles/core/src/test/resources/image/v3/exporter-image36-two-smart-sizes.json, bundles/core/src/test/resources/image/v3/exporter-image37.json, bundles/core/src/test/resources/image/v3/exporter-image38-one-smart-size.json, bundles/core/src/test/resources/image/v3/exporter-image38-two-smart-sizes.json, bundles/core/src/test/resources/image/v3/exporter-image38.json, bundles/core/src/test/resources/image/v3/exporter-image39.json, bundles/core/src/test/resources/image/v3/exporter-image42.json, content/src/content/jcr_root/apps/core/wcm/components/commons/site/clientlibs/imageDynamicMedia/js/imageDynamicMedia.js, content/src/content/jcr_root/apps/core/wcm/components/image/v3/image/clientlibs/editor/js/image.js
- removed the dpr placeholder from the image uri for dm
- add js logic to turn dpr mode on
- fix regression with image dialog when dm image is selected
SITES-11676
=> [Image] revert uri change for dm images in v3

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/contentfragment/ModelElementsDataSourceServlet.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/servlets/contentfragment/ModelElementsDataSourceServletTest.java, bundles/core/src/test/resources/com/adobe/cq/wcm/core/components/internal/servlets/contentfragment/test-content.json
| Fixed Issues?            | Fixes #2396
=> SITES-12327: allow number fields to be used to sort CF lists

all/pom.xml, parent/pom.xml
Revert accidental removal of #2219 and #2218
fixes #2212
=> Revert #2219 and #2218

content/src/content/jcr_root/apps/core/wcm/components/form/text/v2/text/text.html, extensions/amp/content/src/content/jcr_root/apps/core/wcm/extensions/amp/components/form/text/v1/text/amp.html
| Fixed Issues?            | https://jira.corp.adobe.com/browse/SITES-13777
| Documentation Provided   |
=> [SITES-13777] Added spellcheck to Form Text and Textarea

content/src/content/jcr_root/apps/core/wcm/components/commons/editor/dialog/childreneditor/v1/childreneditor/clientlibs/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/image/v3/image/clientlibs/ngdmsmartcrop/.content.xml
* fix clientlib compilation errors
| Fixed Issues?            | SITES-14549
=> SITES-14549 - Testing next release

README.md, VERSIONS.md, all/pom.xml, bundles/core/pom.xml, config/pom.xml, content/package-lock.json, content/package.json, content/pom.xml, examples/all/pom.xml, examples/pom.xml, examples/ui.apps/pom.xml, examples/ui.config/pom.xml, examples/ui.content/pom.xml, extensions/amp/bundle/pom.xml, extensions/amp/content/package-lock.json, extensions/amp/content/package.json, extensions/amp/content/pom.xml, extensions/amp/pom.xml, parent/pom.xml, pom.xml, testing/aem-mock-plugin/pom.xml, testing/it/e2e-selenium-utils/pom.xml, testing/it/e2e-selenium/pom.xml, testing/it/http/pom.xml, testing/it/it.ui.apps/package-lock.json, testing/it/it.ui.apps/package.json, testing/it/it.ui.apps/pom.xml, testing/it/it.ui.content/pom.xml, testing/junit/core/pom.xml
| Fixed Issues?            | SITES-14550
=> SITES-14550 - Release 2.23.2

parent/pom.xml
=> Update Maven Central repositories

content/src/content/jcr_root/apps/core/wcm/components/commons/site/clientlibs/link/js/link.js
Jira: https://jira.corp.adobe.com/browse/SITES-18005
=> [SITES-18005] Improve handling of link accessibility text

content/src/content/jcr_root/apps/core/wcm/components/list/v1/list/clientlibs/editor/js/list.js, content/src/content/jcr_root/apps/core/wcm/components/list/v2/list/clientlibs/editor/js/list.js
Improve list editor
[Ticket 1](https://jira.corp.adobe.com/browse/SITES-18842)
[Ticket 2](https://jira.corp.adobe.com/browse/SITES-18843)
=> [SITES-18842][SITES-18843] Improve list

content/src/content/jcr_root/apps/core/wcm/components/form/container/v1/container/clientlibs/editor/js/container.js, content/src/content/jcr_root/apps/core/wcm/components/form/container/v2/container/clientlibs/editor/js/container.js
Minor form container enhancements
[Ticket 1](https://jira.corp.adobe.com/browse/SITES-19118)
[Ticket 2](https://jira.corp.adobe.com/browse/SITES-19119)
=> [SITES-19118][SITES-19119] Form container enhancements

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/link/LinkBuilderImpl.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/link/LinkBuilderImplTest.java
* fixing IT failure in ComponentsIT.testList()
| Fixed Issues?            | SITES-16183
=> SITES-16183 - Testing before release of Core Components 2.24.0

parent/pom.xml
=> Update Sling i18n dependency for `test` scope

testing/it/e2e-selenium-utils/src/main/java/com/adobe/cq/wcm/core/components/it/seljup/util/components/accordion/v1/Accordion.java, testing/it/e2e-selenium-utils/src/main/java/com/adobe/cq/wcm/core/components/it/seljup/util/constant/Selectors.java, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/accordion/v1/AccordionIT.java
Jira: https://jira.corp.adobe.com/browse/SITES-19799
Rewriting the IT test for the **SITES-19799: fix for nested panel containers** issue
=> SITES-19799 - updated AccordionIT

testing/it/http/src/test/resources/components/embed-v1-url-trailing-whitespace.html, testing/it/http/src/test/resources/components/embed-v1-url-youtube.html, testing/it/http/src/test/resources/components/embed-v2-url-trailing-whitespace.html, testing/it/http/src/test/resources/components/embed-v2-url-youtube.html
* Updating test content to match what's returned by Youtube
Fixes #2703
=> SITES-20949 - ComponentsIT.testEmbed failing after Youtube added referrerpolicy="strict-origin-when-cross-origin"

content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion/clientlibs/site/js/accordion.js, content/src/content/jcr_root/apps/core/wcm/components/carousel/v1/carousel/clientlibs/site/js/carousel.js, content/src/content/jcr_root/apps/core/wcm/components/page/v3/page/page.html, content/src/content/jcr_root/apps/core/wcm/components/tabs/v1/tabs/clientlibs/site/js/tabs.js, content/src/content/jcr_root/apps/core/wcm/components/text/v2/text/clientlibs/site/js/text.js, content/src/scripts/datalayer/v1/datalayer.js
* Accounts for cases where the proxy components override HTML and do not carry over the existing initialization logic.
=> SITES-21233 - Improve datalayer initialization

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/PdfViewerImpl.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/PdfViewerImplTest.java
* Added extra field for full-window mode
* Updated unit test
=> SITES-21368 - [PDF Viewer] Disable full screen button in full window mode

content/src/content/jcr_root/apps/core/wcm/components/page/v3/page/page.html
* Removed global variable defined in page/document scope.
Fixes #2736
=> Tracking events intended for GTM datalayer are being intercepted

testing/it/http/src/test/resources/components/carousel-v1-accessibility.html
=> SITES-20678 - Testing Core Components 2.25.0 Release

testing/it/http/src/test/java/com/adobe/cq/wcm/core/components/it/http/ImageIT.java
=> @trivial Update the delivery API endpoint in test case.

content/src/content/jcr_root/apps/core/wcm/components/image/v2/image/clientlibs/editor/js/image.js, content/src/content/jcr_root/apps/core/wcm/components/image/v3/image/clientlibs/editor/js/image.js, testing/it/e2e-selenium-utils/src/main/java/com/adobe/cq/wcm/core/components/it/seljup/util/components/image/BaseImage.java, testing/it/e2e-selenium-utils/src/main/java/com/adobe/cq/wcm/core/components/it/seljup/util/components/image/ImageEditDialog.java, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/image/ImageTests.java, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/image/v3/ImageIT.java
| Fixed Issues?            | `SITES-9113, ASSETS-33747` 
Changelog:
- Fix smart crop test
- Fix alt text error message when seeded value is inexistent
- For remote assets, remove inherit alt text checkbox
- For remote assets, do not try to get and update seeded value
=> [SITES-22335] Fix smart crop test

testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/page/PageTests.java
=> [SITES-22335] Selenium flaky test fix - add timeout before rolling out

parent/pom.xml
=> [SITES-22335] Fix blueprint tests (after fixing rollout dialog selector)

content/src/content/jcr_root/apps/core/wcm/components/image/v3/image/clientlibs/editor/js/image.js
Changelog:
- require alt text after image is uploaded
- clear alt text requirement if the image is removed
- null check for imageFromPageImpl checkbox
- refactor alt text validity (did not change current behaviour)
=> [SITES-23452] Further alt text validation improvements for Image Component Alt Text

bundles/core/pom.xml, content/pom.xml, examples/ui.apps/pom.xml, examples/ui.content/pom.xml, extensions/amp/content/pom.xml, parent/pom.xml, pom.xml, testing/it/e2e-selenium-utils/pom.xml, testing/it/e2e-selenium/pom.xml, testing/it/http/pom.xml, testing/it/it.ui.apps/pom.xml, testing/junit/core/pom.xml
=> [SITES-22335] Increase apache rat plugin version and add exclusion

content/src/content/jcr_root/apps/core/wcm/components/commons/site/clientlibs/link/js/link.js
* Creating separate elements for each link
Fixes #2744, SITES-23879
=> Accessibility text missing for all but last link that opens in new tab

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/LayoutContainerImpl.java, bundles/core/src/test/resources/container/test-content.json
https://jira.corp.adobe.com/browse/SITES-19836
=> SITES-19836 Ghost component in container is displayed on publish and preview instances

README.md, VERSIONS.md
=> Update documentation regarding Java versions

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/CoreFormHandlingServlet.java
| Fixed Issues?            | [SITES-28193](https://jira.corp.adobe.com/browse/SITES-28193)
| Tests Added + Pass?      | Manual validation + Ran Jenkins Job with CQ versions SDK 6.5.0 and 6.5.2025, no extra failures
=> SITES-28193 Ensure consistent content type during form submission in Core WCM Components

.github/workflows/maven-deploy.yml, .github/workflows/maven-release.yml, .github/workflows/maven-test.yml
* Update checkout action version
=> Update Github actions versions

README.md
=> Add details on 6.5 LTS support

content/src/content/jcr_root/apps/core/wcm/components/search/v2/search/clientlibs/site/js/search.js
Fixes [SITES-30879](https://jira.corp.adobe.com/browse/SITES-30879)
Externalize unlocalized strings
=> SITES-30879: Unlocalized strings in Sites > Page Editor > Search component
