adobe/aem-core-wcm-components

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/impl/v1/ImageImpl.java
wcmmode should be made optional because it's not available when calling Sling Models exporter view with ".model.json". Otherwise ".mode.json" view fails with an error in the error.log.
=> Image component: wcmmode should be optional

config/src/content/jcr_root/apps/core/wcm/config.author/com.day.cq.wcm.mobile.core.impl.MobileEmulatorProvider-core-components.config
pages with page components derived from `core/wcm/components/page/v1/page` do not show the "Emulator" button in the page editor, some other features do not work as well then.
registering the resource type as mobile emulator provider fixes the problem.
=> Mobile Emulator Provider registration for page component

content/src/content/jcr_root/apps/core/wcm/components/image/v1/image/_cq_editConfig.xml
Image maps are currently not supported in the HTL markup and would
require some javascript to be usable in a responsive website, therefore
we should just disable them for now.
This fixes #35
=> Disable maintaining image maps in the IPE

.github/issue_template/bug_report.md, .github/issue_template/feature_request.md, .github/pull_request_template.md
The following templates should allow users to submit issues / PRs easier, by making sure that all required information is available from the beginning.
=> @trivial: added github templates for issues and PRs

content/src/content/jcr_root/apps/core/wcm/components/image/v2/image/image.html, testing/it/ui-js/src/content/jcr_root/apps/core/wcm/tests/test-cases/Image/v1/Image.js, testing/it/ui-js/src/content/jcr_root/apps/core/wcm/tests/test-cases/Image/v2/Image.js, testing/it/ui-js/src/content/jcr_root/apps/core/wcm/tests/test-suites/Image/v2/Image.js
- adds condition to noscript unwrap logic such that image map areas are responsively resized by the JS component even if there are no widths defined (as is the case for SVG images), and lazy loading is disabled (the default).
- updates ui-js test cases.
| Fixed Issues?            | `Fixes #35` 
=> [Image] Image map support for image component

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/form/FormStructureHelperImpl.java
Removed commit to current resource resolver as the updateFormStructure is used by a SlingPostProcessor and therefore the commit is handled automatically by the SlingPostProcessor.
fixes #206
=> NullPointerException prevents delete forms component from page

content/src/content/jcr_root/apps/core/wcm/components/search/v1/search/clientlibs/site/js/search.js
Currently onDocumentReady is called immediately without waiting for the DOMContentLoaded event.
=> Avoid calling onDocumentReady right away

content/src/content/jcr_root/apps/core/wcm/components/title/v1/title/_cq_editConfig.xml, content/src/content/jcr_root/apps/core/wcm/components/title/v2/title/_cq_editConfig.xml
| Fixed Issues?            | Fixes #231
| Any Dependency Changes?  |NO
Fixes the inlineEditing issue for H5 and H6 styles for title component
=> Issue #231 [Title] inplaceEditing doesn't work properly for H5 and H6 title types

content/src/content/jcr_root/apps/core/wcm/components/image/v2/image/image.html
Adds https://schema.org/ImageObject vocabulary for Image Component. Including:
* `contentUrl`
* `caption` (If the visible caption span is disabled, we provide a meta equivalent) 
we may also consider adding an additional meta tag for `description` derived from the alt text. Any other ideas welcome, there are for example properties for `dateCreated`, `dateModified`, `datePublished` and other metadata.
| Fixed Issues?            | `Fixes #221` 
=> [Image] Adding support for schema.org/ImageObject to the Image component

content/src/content/jcr_root/apps/core/wcm/sandbox/commons/ui/clientlibs/panelcontainer/js/PanelContainer.js, content/src/content/jcr_root/apps/core/wcm/sandbox/commons/ui/clientlibs/panelselect/js/panelselect.js, testing/it/ui-js/src/content/jcr_root/apps/core/wcm/sandbox/tests/test-cases/Carousel/v1/Carousel.js, testing/it/ui-js/src/content/jcr_root/apps/core/wcm/sandbox/tests/test-suites/Carousel/v1/Carousel.js
- fixes endpoint for panel select reorder action
- adds ui-js test for reordering
- moves panel select position to `before COPY`
| Fixed Issues?            | Fixes #265  
=> [Carousel] Carousel edit toolbar menu iteration 1

content/src/content/jcr_root/apps/core/wcm/sandbox/commons/ui/clientlibs/panelcontainer/js.txt, content/src/content/jcr_root/apps/core/wcm/sandbox/commons/ui/clientlibs/panelcontainer/js/PanelContainer.js, content/src/content/jcr_root/apps/core/wcm/sandbox/commons/ui/clientlibs/panelcontainer/js/contentTree.js
- introduces `cmp-panelcontainer-navigated` event.
- disables panel container item editable overlays that aren’t the active one.
- adds content tree listeners to navigate to and select panels on change.
| Fixed Issues?            | Fixes #285 
| Documentation Provided   |  (code comments and or markdown)
=> [Carousel] Navigation fails on a Carousel item selection from the Content Tree

testing/junit/core/pom.xml
We raise the dependency of
'org.apache.sling:org.apache.sling.testing.resourceresolver-mock' to
version 1.1.22 to be in sync with
'org.apache.sling:org.apache.sling.testing.sling-mock.core' which
requires it. This module will otherwise override the version with an
incompatible one.
NOTE: I ran into this issue because I wanted to add a test in module `com.adobe.cq:core.wcm.components.extension.contentfragment.bundle`utilizing Sling mocks. Above library pulls in an incompatible version of `org.apache.sling.testing.resourceresolver.MockResourceResolverFactoryOptions`resulting in 
```bash
java.lang.RuntimeException: Unable to initialize RESOURCERESOLVER_MOCK resource resolver factory: org.apache.sling.testing.resourceresolver.MockResourceResolverFactoryOptions.setMangleNamespacePrefixes(Z)Lorg …
```
=> Raise dependency of resourceresolver-mock to 1.1.22

extension/contentfragment/content/src/content/jcr_root/apps/core/wcm/extension/components/contentfragment/v1/contentfragment/clientlibs/editor/authoring/js/editAction.js
| Fixed Issues?            | Fixes #279 
| Patch: Bug Fix?          | Bug Fix
Updated the edit action for content fragment components to open the selected content fragment variation by populating the `variation` query parameter with the `variationName` value for the CF Editor URL
=> [Fixes #279] Edit action to open to the chosen variation of the content fragment

content/src/content/jcr_root/apps/core/wcm/components/teaser/v1/teaser/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/teaser/v1/teaser/clientlibs/editor/js/teaser.js, testing/it/ui-js/src/content/jcr_root/apps/core/wcm/tests/test-cases/FormOptions/v1/FormOptions.js, testing/it/ui-js/src/content/jcr_root/apps/core/wcm/tests/test-suites/Teaser/v1/Teaser.js
Fixed Issues? #296 
- The granite UI multifield component is going to change behavior in next release which will be backported to 6.3. and 6.4 as well.
- The change involves the value of the name attribute of all elements inside a multifield item. It its going to be fully expanded upon dialog rendering. E.g. instead of:
```name="text"```
it will be rendered as:
```name ="./items/item0/text"```
- A number of FormOptions UI tests will fail as they use the```name``` attribute and value to target elements.
- The teaser will no longer work properly since the teaser's editor clientlib also use the ```name``` attribute and value as selectors in the code. This also causes tests to fail.
- The fix for FormOption tests is to change the selector to search for ending substring.
- The fix for the …
=> Issue #296 [UI Tests] Tests fail for Form Options and Teaser

content/package.json
Adds an npm script to allow running aemfed, for live reload of content / clientlibs during development. See: https://github.com/abmaonline/aemfed.
Example commands (run from /content folder):
* Run: `npm run aemfed`
* Run for non-default target: `npm run aemfed -- -t "http://admin:admin@localhost:8080"`
fixes #300
=> [DevTools] Add aemfed script for live reload following local content changes

content/src/content/jcr_root/apps/core/wcm/components/image/v2/image/clientlibs/site/js/image.js
* Getting the width from the first visible parent in case the image is hidden
* Fixes #305
=> [Carousel][Image] Images don't get the proper size/width when they are selected into the view

content/src/content/jcr_root/apps/core/wcm/components/image/v2/image/_cq_editConfig.xml
to avoid overwriting project-specific resource type with core component resource type when dropping asset.
This was already fixed in rev cd5a7f404335dc988759d82241dde2f97cfbf6cc for v1 of the image component, but accidentally introduced again with v2 of it.
| Documentation Provided   | n/a
=> Image: Remove resourceType definition from dropTarget parameters 

bundles/core/pom.xml, extension/contentfragment/bundle/pom.xml, parent/pom.xml
eliminate some build warnings as some mocks now provide junit5 support.
=> switch to the junit4 artifacts

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/sandbox/internal/models/CarouselImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/sandbox/models/Carousel.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/sandbox/internal/models/CarouselImplTest.java, bundles/core/src/test/resources/carousel/test-content.json, content/src/content/jcr_root/apps/core/wcm/components/form/text/v2/text/clientlibs/site/js/text.js, content/src/content/jcr_root/apps/core/wcm/components/image/v2/image/clientlibs/site/js/image.js, content/src/content/jcr_root/apps/core/wcm/components/search/v1/search/clientlibs/site/js/search.js, content/src/content/jcr_root/apps/core/wcm/sandbox/components/carousel/v1/carousel/README.md, content/src/content/jcr_root/apps/core/wcm/sandbox/components/carousel/v1/carousel/_cq_design_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/sandbox/components/carousel/v1/carousel/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/sandbox/components/carousel/v1/carousel/carousel.html, content/src/content/jcr_root/apps/core/wcm/sandbox/components/carousel/v1/carousel/clientlibs/site/css/carousel.less, content/src/content/jcr_root/apps/core/wcm/sandbox/components/carousel/v1/carousel/clientlibs/site/js/carousel.js, content/src/content/jcr_root/apps/core/wcm/sandbox/components/tabs/v1/tabs/clientlibs/site/js/tabs.js
- adds `autoplay` and `delay` Java api for Carousel
- adds dialog properties for `autoplay` / `delay` feature
- adds site widget logic for auto rotating carousel
- updates property JSDocs for all site widgets
- prev -> previous naming
| Fixed Issues?            | `Fixes #315` 
=> [Carousel] Transition between slides with delay

content/src/content/jcr_root/apps/core/wcm/sandbox/components/carousel/v1/carousel/carousel.html, content/src/content/jcr_root/apps/core/wcm/sandbox/components/carousel/v1/carousel/clientlibs/site/js/carousel.js
Review feedback:
- binds keyboard navigation to carousel rather than indicators
- ensures first item and indicator are active in the carousel markup (prevents FOUC)
| Fixed Issues?            | `Fixes #309` 
| Documentation Provided   | NA (code comments and or markdown)
=> [Carousel] Add accessibility features to navigate through the slides

README.md, VERSIONS.md, content/src/content/jcr_root/apps/core/wcm/components/carousel/v1/carousel/README.md, content/src/content/jcr_root/apps/core/wcm/components/tabs/v1/tabs/README.md, content/src/content/jcr_root/apps/core/wcm/components/teaser/v1/teaser/README.md
- marks tabs, carousel production ready
- adds 2.2.0 release to system requirements
=> [Tabs][Carousel] Update documentation

content/src/content/jcr_root/apps/core/wcm/components/commons/editor/clientlibs/panelcontainer/v1/js/contentTree.js
ensures `overlay` object is available before disabling it
=> [PanelContainer] JS console error in preview mode

content/src/content/jcr_root/apps/core/wcm/components/teaser/v1/teaser/_cq_dialog/.content.xml
Swap default dialog values for fetching title and description from linked page to `false`.
The default state of the component is that no link is available and therefore the default of providing a title and description makes sense.
This also solves the reported issue of these values not aligning with the model implementation defaults for the teaser.
| Fixed Issues?            | `Fixes #268 ` 
=> #268 [Teaser] Title, description displayed even if "Get # from linked page" selected and no page is linked

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/ImageImpl.java
- `null` check on the image extension, use the default (JPG)
| Fixed Issues?            | `Fixes #163` 
=> [Image] Errors when using Design Importer with image (v1 and v2)

content/src/content/jcr_root/apps/core/wcm/components/image/v2/image/clientlibs/editor/js/image.js
`altTuple.update()`, `altTuple.reinitCheckbox()` cause a change in the disabled state of fields related to the tuple. These are called when we update the DAM file reference for the image in the dialog.
Here, we ensure we refresh the state of the alt fields following calls to these functions based on the `isDecorative` state.
| Fixed Issues?            | `Fixes #364` 
| Tests Added + Pass?      | Todo
=> #364 [Image] Alt text stays mandatory field even when 'decorative' flag is set on first save

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/CarouselImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Carousel.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/package-info.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/CarouselImplTest.java, bundles/core/src/test/resources/carousel/test-content.json, content/.stylelintrc.yaml, content/src/content/jcr_root/apps/core/wcm/components/carousel/v1/carousel/README.md, content/src/content/jcr_root/apps/core/wcm/components/carousel/v1/carousel/_cq_design_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/carousel/v1/carousel/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/carousel/v1/carousel/carousel.html, content/src/content/jcr_root/apps/core/wcm/components/carousel/v1/carousel/clientlibs/editor/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/carousel/v1/carousel/clientlibs/editor/js.txt, content/src/content/jcr_root/apps/core/wcm/components/carousel/v1/carousel/clientlibs/editor/js/carousel.js, content/src/content/jcr_root/apps/core/wcm/components/carousel/v1/carousel/clientlibs/site/css/carousel.less, content/src/content/jcr_root/apps/core/wcm/components/carousel/v1/carousel/clientlibs/site/js/carousel.js, testing/it/ui-js/src/content/jcr_root/apps/core/wcm/tests/test-cases/Carousel/v1/Carousel.js, testing/it/ui-js/src/content/jcr_root/apps/core/wcm/tests/test-suites/Carousel/v1/Carousel.js
This pull request addresses issues #326 #327 and #361 which are closely related to the autoplay and pause/play bug/features we would like to address for the [2.2.2 milestone](https://github.com/adobe/aem-core-wcm-components/milestone/9).
**General**
- documentation updates
- test case addition and updates
#326 Provide pause/play button when autoplay is enabled
- adds pause and play button markup
- adds JS handling for playing / pausing
- simplifies default site CSS
- adds ability to configure auto-pause on hover via the edit and policy dialogs. It may be a valid use-case for example to disable auto-pause on hover for a full screen Carousel.
#327 Pause carousel autoplay when carousel document is hidden
- uses the page visibility API …
=> #326 #327 #361 [Carousel] Pause/play enhancements

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/ImageImpl.java
- removes potential charset information from `jcr:mimeType` property
| Fixed Issues?            | `Fixes #163` 
=> #163 [Image] Errors when using Design Importer with image (v1 and v2)

content/src/content/jcr_root/apps/core/wcm/components/tabs/v1/tabs/clientlibs/site/js/tabs.js
- only shift tab focus on click and keyboard event handling
| Fixed Issues?            | `Fixes #369` 
=> #369 [Tabs] Tab focus behaviour too invasive

content/src/content/jcr_root/apps/core/wcm/components/carousel/v1/carousel/clientlibs/editor/js/carousel.js
Due to the default behaviour of the Granite `com.adobe.granite.ui.components.Value.val()` [0] method if the form isn't fresh, default values are ignored if a property isn't set. As we disable the autoplay fields (delay + disable autopause), they don't have a value set the first time and for subsequent dialog load they therefore aren't provided with a default.
Here we don't disable these so that their default is persisted and available on subsequent load.
[0] - https://helpx.adobe.com/experience-manager/6-4/sites/developing/using/reference-materials/javadoc/com/adobe/granite/ui/components/Value.html
| Fixed Issues?            | `Fixes #372` 
| Major: Breaking Change? …
=> #372 [Carousel] Saving dialog with autoplay unchecked, removes delay and disable on pause defaults

extension/contentfragment/bundle/src/main/java/com/adobe/cq/wcm/core/components/extension/contentfragment/internal/models/v1/ContentFragmentImpl.java
- moves `org.apache.commons.lang.*` reference to `org.apache.commons.lang3.*`
| Fixed Issues?            | `Fixes #389` 
=> #389 [Content Fragment] 1.0.8 unresolved dependencies with AEM 6.3.3.0

content/src/content/jcr_root/apps/core/wcm/components/carousel/v1/carousel/clientlibs/site/js/carousel.js, content/src/content/jcr_root/apps/core/wcm/components/tabs/v1/tabs/clientlibs/site/js/tabs.js
- fallback for unsupported `window.scrollX`, `window.scrollY` on IE11
| Fixed Issues?            | `Fixes #394 ` 
| Documentation Provided   |  (code comments and or markdown)
=> #394 [IE 11] [Tab/Carousel] clicking on Tab title, Carousel indicator makes page jump to the top

bundles/core/pom.xml, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/SocialMediaHelperImpl.java
- making the import of the commerce bundle optional
- catching NoClassDefFoundError in SocialMediaHelper in case the commerce API is not available and return the default page metadata in this case
fixes #423
=> Making the import of the commerce bundle optional

all/src/content/META-INF/vault/filter.xml
when (re)installing all package after extension package was installed.
steps to reproduce the problem:
1. Install "all" package from core components
2. Install "extension" package
3. Install "all" package again
expected: both core components bundle and content fragment extension bundle should be deployed in OSGi
actual: the content fragment extension bundle that was deployed with step 2 was deleted from repository in step 3
this PR adds an filter exclusion rule to avoid this.
| Documentation Provided   | n/a
| License                  | …
=> avoid removing extension bundles from install folder

examples/content/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-site/scripts/demo.js, examples/content/src/content/jcr_root/apps/core-components-examples/components/demo/component/component.html, examples/content/src/content/jcr_root/apps/core-components-examples/components/demo/component/json.html
Adds links to the component model JSON such that when the library is exported, the JSON resources are also scraped. The anchor hrefs are read for reference and removed on the client.
=> @refactor - adds JSON anchor link for scraping content for static export

content/src/content/jcr_root/apps/core/wcm/components/separator/v1/separator/README.md, content/src/content/jcr_root/apps/core/wcm/components/separator/v1/separator/separator.html
Ensures the separator BEM classes are aligned with the pattern used elsewhere.
=> @releng - align separator BEM naming with other components

content/package-lock.json, content/package.json
| Any Dependency Changes?  | aemfed, npm-run-all and stylelint
Update of the npm dependencies.
Mainly for update of aemfed with better Windows support and because npm doesn't automatically install patches and minor updates when module is still in 0.x.x version range (see [npm semver - Caret Ranges ^1.2.3 ^0.2.5 ^0.0.4](https://www.npmjs.com/package/semver#caret-ranges-123-025-004)).
Not sure what the policy on the package-lock is, so did check it in.
There is also an update for eslint, but it …
=> Update npm dependencies

examples/src/content/jcr_root/content/core-components-examples/library/tabs/.content.xml
- removes sample content from nested tabs as it doesn't add anything to the previewed feature and requires 9 permutations of sample content.
=> [Library] Nested tabs content

bundles/core/pom.xml, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/ContentFragmentUtils.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/contentfragment/ContentFragmentImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/contentfragment/DAMContentFragmentImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/contentfragment/ContentFragment.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/contentfragment/DAMContentFragment.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/ContentFragmentModelsCommonsTest.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/ContentFragmentUtilsTest.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/contentfragment/AbstractContentFragmentTest.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/contentfragment/ContentFragmentImplTest.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/contentfragment/ContentFragmentMockAdapter.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/contentfragment/MockElement.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/contentfragment/MockVariation.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/servlets/contentfragment/AbstractDataSourceServletTest.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/servlets/contentfragment/ElementNamesRenderConditionTest.java, bundles/core/src/test/resources/com/adobe/cq/wcm/core/components/internal/expectedJson.json, bundles/core/src/test/resources/com/adobe/cq/wcm/core/components/internal/foo.json, bundles/core/src/test/resources/contentfragment/test-content.json, bundles/core/src/test/resources/contentfragment/test-expected-content-export.json, bundles/core/src/test/resources/findbugs-exclude.xml, content/package-lock.json, content/src/content/jcr_root/apps/core/wcm/components/contentfragment/v1/contentfragment/clientlibs/editor/authoring/js/editAction.js, content/src/content/jcr_root/apps/core/wcm/components/contentfragment/v1/contentfragment/contentfragment.html, content/src/content/jcr_root/apps/core/wcm/components/contentfragment/v1/contentfragment/element.html, content/src/content/jcr_root/apps/core/wcm/components/contentfragment/v1/contentfragment/rawcontent.html, content/src/content/jcr_root/apps/core/wcm/components/contentfragment/v1/contentfragment/templates.html, parent/pom.xml, testing/it/ui-js/package-lock.json
This PR is based on https://github.com/adobe/aem-core-wcm-components/pull/498
It modifies the newly added content fragment component and
* Separates content fragment (exporter) model logic from component logic
* Extracts common logic into utility class and adds tests
* Refactors tests and mainly extract test classes to simplify
  maintenance
* Improves templates and HTML to reflect requirements from PM
Todos:
=> [ContentFragment] Refactor content fragment component (#360)

bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/contentfragment/ContentFragmentImplTest.java
- fix failing test with JDK 11
=> [ContentFragment] Move content fragment component from extension to core

content/src/content/jcr_root/apps/core/wcm/components/page/v1/page/.content.xml
| Fixed Issues?            | #428`
The designDialogPath property of the page V1 component was pointing to a non-existent design dialog location. removed it so it inherits the dialog from wcm/foundation/components/basicpage/v1/basicpage
=> [Page] Design Dialog missing for page component v1

.github/ISSUE_TEMPLATE/bug_report.md, CONTRIBUTING.md
Improve the contributing guidelines to include:
• more information on the different ways to contribute to the project
• more specific guidelines for ensuring bug reports, feature requests and contributions are successful
see: https://github.com/adobe/aem-core-wcm-components/blob/issue/contributing-guidelines/CONTRIBUTING.md
fixes #528
=> [Docs] Improve contributing guidelines

README.md, VERSIONS.md
- uses non-decimal java versions (8 rather than 1.8).
- adds java 11 note for 2.4.0.
- uses ranges rather than minimum requirements in versions table.
=> [Documentation] Document Java 11 support

README.md
Linking to the new location of the WKND tutorial: https://docs.adobe.com/content/help/en/experience-manager-learn/getting-started-wknd-tutorial-develop/overview.html
=> Updated link to WKND Tutorial

README.md
Closes #576 
With the new Maven Archetype having been released recently, they updated the file vault plugin. 
Because of this, projects using the latest Maven Archetype should be adding core components as a subpackage to filevault-package-maven-plugin instead of content-package-maven-plugin. 
I updated the README.md to reflect his change. 
Please check over my changes to ensure that I am correct about this configuration. 
Thanks!
=> Updated Readme to reflect Filevault plugin changes

content/src/content/jcr_root/apps/core/wcm/components/navigation/v1/navigation/navigation.html
Although this generates a warning in the HTML validator, we should still add it while we support IE11 for publish side code which still doesn't map roles to HTML5 element names.
| Fixed Issues?            | `Fixes #584` 
=> [Navigation] Navigation is missing the role attribute

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/contentfragment/ContentFragmentListImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/contentfragment/ContentFragmentList.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/contentfragment/package-info.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/contentfragment/ContentFragmentListImplTest.java, bundles/core/src/test/resources/contentfragmentlist/test-content.json, content/src/content/jcr_root/apps/core/wcm/components/contentfragmentlist/v1/contentfragmentlist/README.md, content/src/content/jcr_root/apps/core/wcm/components/contentfragmentlist/v1/contentfragmentlist/_cq_dialog/.content.xml
| Fixed Issues?            | Fixes #598 
| Patch: Bug Fix?          | Could be interpreted as an enhancement or bugfix (depending on perspective)
| Tests Added + Pass?      | No, initial PR to gather feedback
| Documentation Provided   | No, initial PR to gather feedback
| Any Dependency Changes?  | Yes incremented `com.adobe.cq.wcm.core.components.models.contentfragment` from 1.0.0 to 1.1.0
Currently, the CF List component appears to return a max number of 10 fragments, see issue #598. This PR adds a Result Limit to the Content Fragment List dialog. 
This allows a content author to:
* configure the max …
=> initial commit of result limit for Content fragment list component

config/src/content/jcr_root/apps/core/wcm/config/com.adobe.cq.dam.cfm.impl.component.ComponentConfigImpl-core-comp-v1.config
- add the config for the content fragment component (taken from the removed extension bundle)
=> [WCM Core Component] Fragment Editor no longer callable (CQ-4271675)

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Download.java, content/src/content/jcr_root/apps/core/wcm/components/download/v1/download/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/download/v1/download/README.md, content/src/content/jcr_root/apps/core/wcm/components/download/v1/download/_cq_design_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/download/v1/download/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/download/v1/download/clientlibs/editor/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/download/v1/download/download.html, content/src/content/jcr_root/apps/core/wcm/components/title/v2/title/_cq_design_dialog/.content.xml, examples/src/content/jcr_root/content/core-components-examples/library/download/.content.xml
- adds descriptions to component library examples.
- splits inline and direct upload examples in component library into separate examples.
- changes default title heading HTML element to `H3` from `H2`.
- fixes editor clientlib category name format.
- merges content policy `Download` and `Features` tabs into single `Properties` tab, as with other components, for simplicity:
- wraps metadata with `cmp-download__metadata` and orders metadata before the action in the markup. Allows easier control of metadata positioning in the card.
- fixes `hasContent` test in the template.
- improves README.md description, adding content policy parameters.
- removes references to preview image capability.
- removes unnecessary image resource type in download `content.xml`.
- consistently references …
=> [Download] General Review

content/src/content/jcr_root/apps/core/wcm/components/tabs/v1/tabs/clientlibs/editor/js/tabs.js
- ensure the children editor works if the properties tab and its elements aren't available
| Fixed Issues?            | `Fixes #618` 
=> [Tabs] Sling Resource Merger properties break item add button

content/src/content/jcr_root/apps/core/wcm/components/download/v1/download/README.md, content/src/content/jcr_root/apps/core/wcm/components/download/v1/download/download.html
@bpauli, some changes on top of your pull request. I wrapped each property, it allows us to add the modifier for the property type (`cmp-download__property--filename` etc.) as you initially had it, and is also consistent with the content fragment markup approach. divs wrapping dt, dd is valid.
=> [Download] Markup cleanup adjustments

content/src/content/jcr_root/apps/core/wcm/components/download/v1/download/README.md, content/src/content/jcr_root/apps/core/wcm/components/download/v1/download/download.html
- don't display action text markup if action text or download url is empty
- display metadata as description list element
- display download icon as part of the metadata
=> [Download] Clean up output markup

content/src/content/jcr_root/apps/core/wcm/components/breadcrumb/v2/breadcrumb/README.md, content/src/content/jcr_root/apps/core/wcm/components/download/v1/download/README.md, content/src/content/jcr_root/apps/core/wcm/components/download/v1/download/download.html, examples/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-themes/core-components-clean/styles/components/accordion/base.less, examples/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-themes/core-components-clean/styles/components/accordion/dark.skin.less, examples/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-themes/core-components-clean/styles/components/accordion/index.less, examples/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-themes/core-components-clean/styles/components/accordion/light.skin.less, examples/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-themes/core-components-clean/styles/components/breadcrumb/base.less, examples/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-themes/core-components-clean/styles/components/breadcrumb/dark.skin.less, examples/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-themes/core-components-clean/styles/components/breadcrumb/index.less, examples/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-themes/core-components-clean/styles/components/breadcrumb/light.skin.less, examples/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-themes/core-components-clean/styles/components/button/base.less, examples/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-themes/core-components-clean/styles/components/button/dark.skin.less, examples/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-themes/core-components-clean/styles/components/button/index.less, examples/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-themes/core-components-clean/styles/components/button/light.skin.less, examples/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-themes/core-components-clean/styles/components/download/base.less, examples/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-themes/core-components-clean/styles/components/download/index.less, examples/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-themes/core-components-clean/styles/components/download/light.skin.less, examples/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-themes/core-components-clean/styles/components/tabs/light.skin.less, examples/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-themes/core-components-clean/styles/components/teaser/base.less, examples/src/content/jcr_root/content/core-components-examples/library/accordion/.content.xml, examples/src/content/jcr_root/content/core-components-examples/library/download/.content.xml
- adds simple styling for accordion, breadcrumb, button and download components.
- adds cmp-download__title-link element to download component and documents it.
- adds missing BEM modifier to breadcrumb docs.
- fixes download direct upload example, removing `inline` property.
=> [Theme] Add simple accordion, breadcrumb, button, download styling.

README.md, VERSIONS.md, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Accordion.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Button.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Download.java, content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion/README.md, content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion/clientlibs/site/js/accordion.js, content/src/content/jcr_root/apps/core/wcm/components/breadcrumb/v2/breadcrumb/README.md, content/src/content/jcr_root/apps/core/wcm/components/languagenavigation/v1/languagenavigation/README.md, content/src/content/jcr_root/apps/core/wcm/components/navigation/v1/navigation/README.md, examples/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-site/styles/components/navigation.less, examples/src/content/jcr_root/conf/core-components-examples/settings/wcm/templates/content-page/structure/.content.xml, examples/src/content/jcr_root/content/core-components-examples/library/.content.xml, examples/src/content/jcr_root/content/core-components-examples/library/accordion/.content.xml, examples/src/content/jcr_root/content/core-components-examples/library/button/.content.xml, examples/src/content/jcr_root/content/core-components-examples/library/download/.content.xml
- adds 2.5.0 release to main readme and historical version documents.
- updates maven dependency version documentation for 2.5.0 release.
- updates component library versions.
- accordion - adds missing BEM modifier.
- accordion - minor readme fixes.
- accordion - clearer expanded items in library examples.
- accordion - minor JS docs fix.
- button - link to library home rather than adobe home.
- download - switch action text for inline example to “View”.
- adds component library links for new components in the library.
- improves JavaDocs.
- fixes spacing at base of the navigation in the component library.
=> @releng - Pre-release - Update documentation

content/src/content/jcr_root/apps/core/wcm/components/image/v1/image/_cq_editConfig.xml, content/src/content/jcr_root/apps/core/wcm/components/image/v2/image/_cq_editConfig.xml, content/src/content/jcr_root/apps/core/wcm/components/teaser/v1/teaser/_cq_editConfig.xml, content/src/content/jcr_root/apps/core/wcm/components/text/v1/text/_cq_editConfig.xml, content/src/content/jcr_root/apps/core/wcm/components/text/v2/text/_cq_editConfig.xml, content/src/content/jcr_root/apps/core/wcm/components/title/v1/title/_cq_editConfig.xml, content/src/content/jcr_root/apps/core/wcm/components/title/v2/title/_cq_editConfig.xml
* Moved `config` node to `inplaceEditingConfig`, referenced via `configPath` property
Fixes #657
=> [Text][Image][Teaser] In-place editing config path is not accessible for non-administrators #657

content/src/content/jcr_root/apps/core/wcm/components/breadcrumb/v2/breadcrumb/breadcrumb.html
| Fixed Issues?            |  Fixes #581
| Patch: Bug Fix?          | Bugfix
| Documentation Provided   | Yes
Added aria-label to breadcrumbs markup
=> [Breadcrumb] Missing aria-label="Breadcrumb" on nav element

content/src/content/jcr_root/apps/core/wcm/components/tabs/v1/tabs/tabs.html
| Fixed Issues?            | Fixes #591
| Patch: Bug Fix?          | Bugfix
| Minor: New Feature?      | 
| Documentation Provided   | Yes
Changed tabs component markup - added tabindex="0" on tabpanel and initial tabindex state for tab (0 or -1 depending on whether the items is active or not)
=> [Tabs] Can't focus tabpanel via keyboard if it doesn't contain focusable items 

parent/pom.xml
- update to latest version of the jackson artifacts that are available in CQ
Warning: don't merge this PR until the updated Jackson artifacts (2.9.5) are available in CQ 6.4 (NPR-27169)
Note: the updated Jackson artifacts (2.9.5) are available in CQ 6.3 and 6.5
=> [security] Remove jackson-databind security warning

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/CarouselImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/NavigationImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/TabsImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Carousel.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Navigation.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Tabs.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/package-info.java, content/src/content/jcr_root/apps/core/wcm/components/breadcrumb/v2/breadcrumb/breadcrumb.html, content/src/content/jcr_root/apps/core/wcm/components/carousel/v1/carousel/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/carousel/v1/carousel/carousel.html, content/src/content/jcr_root/apps/core/wcm/components/navigation/v1/navigation/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/navigation/v1/navigation/navigation.html, content/src/content/jcr_root/apps/core/wcm/components/tabs/v1/tabs/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/tabs/v1/tabs/tabs.html, parent/pom.xml
| Fixed Issues?            | Fixes: #586 
| Patch: Bug Fix?          | Bugfix
| Minor: New Feature?      | -
| Major: Breaking Change?  | -
| Documentation Provided   | Yes 
Added additional property in dialogs of Navigation, Tabs and Carousel components that allows author to specify aria-label for the component
=> [Navigation][Tabs][Carousel] There's no possibility to add labels to the components

examples/src/content/jcr_root/apps/core-components-examples/components/page/head.html
Avoid LinkChecker log warnings for Google Font URL:
```
15.08.2019 00:02:45.050 *WARN* [0:0:0:0:0:0:0:1 [1565820164860] GET /content/core-components-examples/library/button.html HTTP/1.1] com.day.cq.rewriter.linkchecker.impl.LinkCheckerImpl Ignoring malformed URI: java.net.URISyntaxException: Illegal character in query at index 46: https://fonts.googleapis.com/
```
by escaping it properly.
| Documentation Provided   | n/a
=> Ensure proper encoding of Google Font URL - avoid LinkChecker warning

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/NavigationImpl.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/NavigationImplTest.java, bundles/core/src/test/resources/navigation/test-content.json
| Fixed Issues?            | Fixes #703 
Fixed #703 wherein a NPE is thrown when a page - that is designated as the navigation root for Navigation component - does not have a jcr:content resource.
There is no need for the page to have a jcr:content resource to serve as the navigation root.
The NPE is caused in the LanguageManager (see #703 for stacktrace). 
Likely the content resource of the page was used because the LanguageManager API requires a resource, and using …
=> Issue/703: [Navigation] Fix NPE if navigation root page is missing jcr:content

content/src/content/jcr_root/apps/core/wcm/components/container/v1/container/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/image/v1/image/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/image/v1/image/_cq_editConfig.xml, content/src/content/jcr_root/apps/core/wcm/components/image/v2/image/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/image/v2/image/_cq_editConfig.xml, content/src/content/jcr_root/apps/core/wcm/components/teaser/v1/teaser/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/teaser/v1/teaser/_cq_editConfig.xml
it's supported neither by AEM Assets nor by the Core Component Image component.
i think this was introduced (probably accidentally) in #32 and copied from there to the other places.
=> Remove image/webp media type - 

content/src/content/jcr_root/apps/core/wcm/components/download/v1/download/download.html
evaluate if download has content by checking the "filename" property - it contains only a value if an asset reference or upload is present and valid
eliminate the checks for title, description and action text - a download component without any of these is fine, but any of these without a valid download does not make sense
| Q                        | A
=> Ensure download component has a valid asset reference or file upload

.circleci/config.yml
| Fixed Issues?            | -
| Patch: Bug Fix?          | -
| Minor: New Feature?      | -
| Major: Breaking Change?  | -
| Tests Added + Pass?      | -
| Documentation Provided   | Yes
Extending circleCI config.yaml to:
- store the junit test results as artifacts
- store an *.dump or *.dumpstream files in case of failure as artifacts
- create the test summary
=> @releng Save Test Results and Dumps, Create Test Summary in Circle CI

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/contentfragment/ContentFragmentImpl.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/contentfragment/ContentFragmentImplTest.java
- return an empty content fragment in case the path to the content fragment is empty or not valid.
fixes #720
=> Allow empty content fragment in JSON

content/src/content/jcr_root/apps/core/wcm/components/embed/v1/embed/processors/pinterest.html
- Adds Pinterest URL as anchor content by default, to ensure it still renders. Gets replaced by the Pinterest script for valid URLs.
=> [Embed] Invalid Pinterest ID makes component uneditable

README.md, VERSIONS.md, bundles/core/pom.xml, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/contentfragment/ContentFragmentImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServlet.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/DownloadServlet.java, content/src/content/jcr_root/apps/core/wcm/components/carousel/v1/carousel/README.md, content/src/content/jcr_root/apps/core/wcm/components/contentfragmentlist/v1/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/contentfragmentlist/v1/contentfragmentlist/README.md, content/src/content/jcr_root/apps/core/wcm/components/contentfragmentlist/v1/contentfragmentlist/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/embed/v1/embed/README.md, examples/src/content/jcr_root/conf/core-components-examples/settings/wcm/templates/content-page/structure/.content.xml, examples/src/content/jcr_root/content/core-components-examples/library/.content.xml, examples/src/content/jcr_root/content/core-components-examples/library/content-fragment-list/.content.xml, examples/src/content/jcr_root/content/core-components-examples/library/embed/.content.xml
- adds 2.7.0 to component library.
- adds 2.7.0 to README and VERSIONS.
- clarifies carousel automatic transitioning note.
- adds Order By and Sort Order Content Fragment List library example.
- adds Content Fragment List order feature to its README.
- adds missing .content.xml in Content Fragment List content.
- adds missing OOTB oEmbed providers to embed README.
- text improvements in Embed library page.
- removes unnecessary empty lines introduced.
- minor text improvements.
=> @releng - 2.7.0 Pre-release - Documentation

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/ListImpl.java
- checks for the `./currentPage` property also being blank, as well as missing
- in both cases use the current page path
=> [Maintenance] Fixes failing List UI tests

content/src/content/jcr_root/apps/core/wcm/components/container/v1/container/README.md
| Fixed Issues?            | `Fixes #771`
| Patch: Bug Fix?          | Documentation update
Updated documentation in the Container component README when setting up the proxy component user must add cq:isContainer="{Boolean}true" to enable full functionality.
=> [Container] Documentation: Add cq:isContainer="{Boolean}true" for proxy component in README

content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion/clientlibs/site/js/accordion.js
| Fixed Issues?            | String function use should be optimized for single characters
| Documentation Provided   | Yes 
An indexOf or lastIndexOf call with a single letter String can be made more performant by switching to a call with a char argument.
=> [Image v2] String function use should be optimized for single characters

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/ImageImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Image.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/package-info.java
| Fixed Issues?            | #686 
As discussed in the issue, this PR adds the isDecorative method to the Image interface.
=> Add isDecorative method to Image interface (Adobe#686)

bundles/core/pom.xml
| Fixed Issues?            | Fixes: #804
| Patch: Bug Fix?          | X
| Minor: New Feature?      | 
| Any Dependency Changes?  | Yes, see below
Minor fix to add junit-platform-commons version 1.5.2 to provide the missing dependency when running jUnit tests in Eclipse.
Replaces #805
=> Unable to Run Individual jUnit Tests in Eclipse

content/src/content/jcr_root/apps/core/wcm/components/commons/v1/clientlibs/editor/checkboxTextfieldTuple/checkboxTextfieldTuple.js
Checkbox Textfield Tuple - read the richtext value from the hidden input field rather than the html of the editable.
| Fixed Issues?            | `Fixes #788` 
=> [Teaser] Blank lines in teaser description when Link or CTA is filled

content/src/content/jcr_root/apps/core/wcm/components/teaser/v1/teaser/clientlibs/editor/js/teaser.js
- ensures teaser dialog is still operational if the linkURL or action related fields aren’t available / hidden.
=> [Teaser] Title editable even though "Get title from linked page" is checked

content/src/content/jcr_root/apps/core/wcm/components/container/v1/container/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/container/v1/container/clientlibs/editor/js/container.js
- switches background color swatches only field to `variant=swatch`
- adds workaround to ensure the color input overlay fits in the inline dialog context by aligning it bottom left
| Fixed Issues?            | Fixes #740 
| Documentation Provided   |  N/A
=> [Container] Author can choose whichever color even if swatches only option is enabled

content/src/content/jcr_root/apps/core/wcm/components/experiencefragment/v1/experiencefragment/_cq_editConfig.xml, content/src/content/jcr_root/apps/core/wcm/components/experiencefragment/v1/experiencefragment/clientlibs/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/experiencefragment/v1/experiencefragment/clientlibs/editor/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/experiencefragment/v1/experiencefragment/clientlibs/editor/js.txt, content/src/content/jcr_root/apps/core/wcm/components/experiencefragment/v1/experiencefragment/clientlibs/editor/js/experiencefragment.js, content/src/content/jcr_root/apps/core/wcm/components/experiencefragment/v1/experiencefragment/clientlibs/editor/js/namespace.js
| Fixed Issues?            | Fixes #815 
| Documentation Provided   | no
- created our own edit action, instead of using the one from Experience Fragment 
- instead of using variationPath returned by .json, using localizedVariationPath from .model.json
=> [ExperienceFragment] "Edit in New Tab" action does not work

content/src/content/jcr_root/apps/core/wcm/components/page/v1/page/README.md, content/src/content/jcr_root/apps/core/wcm/components/page/v2/page/README.md, content/src/content/jcr_root/apps/core/wcm/components/title/v1/title/README.md, content/src/content/jcr_root/apps/core/wcm/components/title/v2/title/README.md
- rewrites page property docs to include intention of title vs page title vs navigation title properties.
- general improvements to page property docs.
- adds note in the title component about automatic title generation.
=> [Page] Confusing page titles should be clarified

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/DownloadImpl.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/DownloadImplTest.java, bundles/core/src/test/resources/download/test-content-dam-without-size-prop.json, bundles/core/src/test/resources/download/test-content.json
| Fixed Issues?            | Fixes adobe#819 
| Patch:          | Yes - Download Component
| Minor:      | No
| Major:   | No
I added fallback for initialize size field if an asset does't contain `dam:size` property.
=> [Download] Size of asset is not visible #819

content/src/content/jcr_root/apps/core/wcm/components/teaser/v1/teaser/_cq_editConfig.xml
| Fixed Issues?            |Fixes #857  
| Patch: Bug Fix?          | Yes - Teaser Component
I added `image/svg\\+xml` to `accept` property in cq:editConfig for teaser component in order to fix drag & drop SVG images from content finder.
=> [Teaser] Drag & drop SVG on teaser component doesn't work #857

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/contentfragment/ElementsDataSourceServlet.java
| Fixed Issues?       | Fixes #849 
If the contentType cannot be retrieved from the ContentElement's value, it will try to get it from the ContentElement directly.
=> [Content Fragment] Fallback to retrieve correct content type within ElementDataSourceServlet #849

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/ExperienceFragmentImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/contentfragment/ContentFragmentImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/contentfragment/DAMContentFragmentImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/ExperienceFragment.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/contentfragment/DAMContentFragment.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/contentfragment/package-info.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/ExperienceFragmentImplTest.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/contentfragment/AbstractContentFragmentTest.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/contentfragment/ContentFragmentImplTest.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/contentfragment/ContentFragmentMockAdapter.java, content/src/content/jcr_root/apps/core/wcm/components/contentfragment/v1/contentfragment/README.md, content/src/content/jcr_root/apps/core/wcm/components/contentfragment/v1/contentfragment/templates.html, content/src/content/jcr_root/apps/core/wcm/components/experiencefragment/v1/experiencefragment/README.md, content/src/content/jcr_root/apps/core/wcm/components/experiencefragment/v1/experiencefragment/experiencefragment.html
* Adds `ContentFragment#getName` and applies the result in the markup as BEM modifier on the block.
* Adds `ExperienceFragment#getName` and applies the result in the markup as BEM modifier on the block.
* Updates READMEs.
* Updates test cases.
 
| Fixed Issues?            | `Fixes #860` 
=> [XF/CF] Add template/model class name to component

content/src/content/jcr_root/apps/core/wcm/components/image/v2/image/clientlibs/site/js/image.js
| Fixed Issues?            | Fixes #883 
| Tests Added + Pass?      | No (no idea where / how to add this test)
| Documentation Provided   | No (change is trivial and clear)
In order to solve the issue, the attribute value need to be decoded at initialization time, which is the purpose of the "transform" function.
=> #883 Image attribute not decoded with .atoffer.html extension

content/src/content/jcr_root/apps/core/wcm/components/teaser/v1/teaser/_cq_dialog/.content.xml
- enable SVG images
| Fixed Issues?            | `Fixes #892 ` 
=> [Teaser] unable to drag-n-drop an SVG image into the fileupload widget

content/src/content/jcr_root/apps/core/wcm/components/commons/editor/clientlibs/panelselect/js/panelselect.js
bugfix-901 show toggle select panel in editable template
https://github.com/adobe/aem-core-wcm-components/issues/901
The container components (Accordion/Tab/Carousel) does not provide option to toggle/select panel item(s) when component is authored directly in editable template (structure or initial). However, this works fine when we author the component on the page.
This PR fix addresses above issue by registering panel select option for layer structure and initial as well.
@richardhand and @rajeevyadav2  pls take a look at the PR.
=> bugfix-901 panelselect.js

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/NavigationImpl.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/NavigationImplTest.java, bundles/core/src/test/resources/navigation/test-content.json
| Fixed Issues?            |  Fixes #897
Ensure that by accessing the root page of a non-language live copy, the navigation items provided by the navigation component placed on the page should be the children of the actual live copy and not the children of the source of the live copy.
The solution is to make the condition comparing current page path to live copy path to be true when the two paths are equal, in NavigationImp.getItems().
=> #897 - Issue with Navigation.getItems() for non-language live copy

content/pom.xml, content/src/content/jcr_root/apps/core/wcm/components/form/hidden/v1/hidden/hidden.html, content/src/content/jcr_root/apps/core/wcm/components/form/hidden/v2/hidden/hidden.html, examples/ui.apps/pom.xml, parent/pom.xml
| Fixed Issues?            | Fixes #878
| Patch: Bug Fix?          | ✓
| Tests Added + Pass?      | No new tests; it's just a syntax improvement
| Any Dependency Changes?  | Updated `htl-maven-plugin` to `1.3.4-1.4.0`
=> fix #878: data-sly-test should not be used for concatenating Strings

examples/ui.apps/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-site/styles/components/accordion.less
- sets an explicit transparency for accordion buttons in the aside so the browser default isn't taken
| Fixed Issues?            | `Fixes #891` 
=> [Library] Visual bug on Firefox/Safari for categories in side navigation

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServlet.java
- when timestamp matching image suffixes, also check for a preceding forward slash to help prevent false matches.
The problem reported in #907 is related to all container components (accordion, tabs, carousel) where paths for items that are added via the dialog also contain a postfixed 13 digit timestamp in their path. In the adaptive image servlet the timestamp was matched based only on a 13 digit number, which resulted in an out of bounds exception in this case when determining a substring. This pull request makes the matching a little more robust by also expecting a preceding forward slash.
/conf/core-components-examples/settings/wcm/templates/content-page/structure.coreimg.jpeg/structure/_jcr_content/root/responsivegrid/accordion/item__**1581514061965**/1581514094392/mountain-range.jpe …
=> [Image] The image of the image component placed in the accordion of the template editor is not displayed.

content/src/content/jcr_root/apps/core/wcm/components/form/container/v1/container/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/form/container/v2/container/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/languagenavigation/v1/languagenavigation/_cq_design_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/languagenavigation/v1/languagenavigation/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/list/v1/list/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/list/v2/list/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/navigation/v1/navigation/_cq_design_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/navigation/v1/navigation/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/search/v1/search/_cq_design_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/search/v1/search/_cq_dialog/.content.xml
See #904
- replaces usages of path field with page field where picking a page is the intended use case.
- covers usages in form container, list, navigation, search and language navigation.
- removes properties not relevant to the page field.
=> Use page dialog fields over path fields where relevant.

content/src/content/jcr_root/apps/core/wcm/components/image/v1/image/image.html, content/src/content/jcr_root/apps/core/wcm/components/image/v2/image/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/image/v2/image/clientlibs/editor/js/image.js, content/src/content/jcr_root/apps/core/wcm/components/image/v2/image/image.html
- remove empty alt attribute in markup
- force validation of alt field in dialog as long the image is not decorative
fixes #922
=> [Image][Accessibility] Empty alt attribute for non-decorative images

parent/pom.xml
The core component core bundle is currently not started on AEM 6.3/6.4 and 6.5 because of the commons-codec dependency to 1.14 which can't be satisfied.
=> Decreasing commons-codec version to support AEM 6.3

content/src/content/jcr_root/apps/core/wcm/components/experiencefragment/v1/experiencefragment/experiencefragment.html
Add the moment the experience fragment is only included with the `content` selector`.
**Expected behaviour**
All selectors should be added to the existing `content` selector before including the experience fragment.
=> Pass selectors to experiencefragment

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/TeaserImpl.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/TeaserImplTest.java, bundles/core/src/test/resources/teaser/test-content.json
| Fixed Issues?            | Fixes #948
Title is now visible when the first call-to-action is an external link.
=> Title is not linked when external action

content/src/content/jcr_root/apps/core/wcm/components/image/v2/image/clientlibs/editor/js/image.js
| Fixed Issues?            | Fixes #1009
Adds a check that the $linkURLField jquery element is present in the dialog before trying to use the element properties (in this case the .setDisabled function). This way you can remove the linkURL from the dialog without breaking the functionality.
=> [Image] Javascript exception when linkURL is removed from the dialog

content/src/content/jcr_root/apps/core/wcm/components/commons/site/clientlibs/container/.content.xml
- make the utils clientlib available on publish instance
=> [Tabs][Library] JS errors thrown in console for aemcomponents.dev

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/AbstractContainerImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/AccordionImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/PanelContainerImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/PanelContainerItemImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/TabsImpl.java
| Fixed Issues?            | None filed
| Tests Added + Pass?      | None added
| Any Dependency Changes?  | N/A
Fixes possible NPEs introduced in the DataLayer.
Specifically:
1) in AccordionImpl `item.getData().getId()` introduces a possible NPE because getData() may return null.
2) in PanelContainerImpl `.findFirst().get();` introduces a possible NPE because findFirst() returns an Optional, Optional.get() causes a NPE if the Optional is empty. It does not return null if the Optional is empty. The null check following the …
=> Fix possible DataLayer NPEs

config/src/content/META-INF/vault/filter.xml
- prevent the core config to overwrite the AMP config
=> [AMP] AMP config is overwritten by the core config

bundles/core/pom.xml, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/DataLayerConfig.java
Fixes #1043
Ensure bundle header are set for caconfig configuration classes
Improve the title and description for DataLayerConfig
=> Fixes #1043 Context-Aware configuration for data layer is not registered as Sling-ContextAware-Configuration-Classes

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/ListImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v2/ListImpl.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/ListImplTest.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/contentfragment/ContentFragmentMockAdapter.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v2/ListImplTest.java, testing/junit/core/src/main/java/com/adobe/cq/wcm/core/components/testing/MockExternalizerFactory.java
| Fixed Issues?            | Fixes #1045
| Patch: Bug Fix?          |  yes
- Cleans up `ListImpl` tests
- Improves `ListImpl` tests to test the items and orders of results instead of just the number of results
- Removes/replaces use of deprecated `Matchers.any()` across the project
- Refactors `ListImpl` to eliminate "populate" methods and clarify the flow of how the `listItems` filed is initialized
- Refactors `ListItem` source result getters (previously the "populate" methods) so that they …
=> Issue/1045: Simplify and improve ListImpl performance

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/PdfViewerImpl.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/PdfViewerImplTest.java, bundles/core/src/test/resources/pdfviewer/test-content.json
| Fixed Issues?            | Fixed #1071 
| Tests Added + Pass?      | yes
Corrects a possible NPE in `PdfViewerImpl#getDocumentFileName()`
that occurs if the `documentPath` property is not set.
A unit test is added to cover this condition.
=> Fix possible NPE in `PdfViewerImpl#getDocumentFileName()`

content/src/content/jcr_root/apps/core/wcm/components/experiencefragment/v1/experiencefragment/_cq_editConfig.xml
| Fixed Issues?            | Fixes #1069 
Updated editconfig for experience fragment to stop page refresh on insert
=> [Experience Fragment] Edit Config REFRESH PAGE on insert (#1069)

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/ImageAreaImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v2/ImageImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Image.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v2/ImageImplTest.java, bundles/core/src/test/resources/image/v2/exporter-image0.json, bundles/core/src/test/resources/image/v2/exporter-image15.json, bundles/core/src/test/resources/image/v2/exporter-image16.json, bundles/core/src/test/resources/image/v2/exporter-image18.json, bundles/core/src/test/resources/image/v2/exporter-image24.json, bundles/core/src/test/resources/image/v2/exporter-image27.json, bundles/core/src/test/resources/image/v2/exporter-image3-with-lazy-threshold.json, bundles/core/src/test/resources/image/v2/exporter-image3-with-policy-delegate.json, bundles/core/src/test/resources/image/v2/exporter-image4.json, bundles/core/src/test/resources/image/v2/exporter-image_template.json, content/src/content/jcr_root/apps/core/wcm/components/image/v2/image/_cq_design_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/image/v2/image/clientlibs/site/js/image.js, content/src/content/jcr_root/apps/core/wcm/components/image/v2/image/image.html
| Fixed Issues?            | Fixes #1090 
Allows template author to set the lazy threshold value so that lazy-loading images can be loaded slightly in advance of being visible on the page in order to reduce delay and jarring image loads and give a more seamless/smooth experience.
Note: someone may want to review the wording of the dialog field name/description to make sure that it makes sense.
=> [Image] Allow lazy threshold to be set in design policy #1090

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/ListImpl.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/ListImplTest.java, bundles/core/src/test/resources/list/test-content.json
| Fixed Issues?            | Fixes #1055 
Updates the ListImpl to use a locale-sensitive collator when
sorting list items by title.
This corrects an issue where list items with accents are sorted
out of order.
=> [List] Use local-sensitive collator when sorting by title #1055

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/NavigationImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/PageListItemImpl.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/NavigationImplTest.java, bundles/core/src/test/resources/navigation/exporter-navigation18.json, bundles/core/src/test/resources/navigation/test-content.json
| Fixed Issues?            | Fixes #1079 
* Modifies `NavigationImpl` to reuse redirect target logic from `PageListItemImpl` to ensure consistent `isActive` behaviour, regardless of length of redirect chain.
* Adds javadoc comments to private members of `NavigationImpl` to aid future development (mostly for me :) )
* Reworks `NavigationImpl` to avoid the need for the inner class `NavigationImpl.NavigationRoot`
* Splits the logic for getting the effective …
=> [Navigation] Fix inconsistent `isActive` behaviour caused by redirect chains + cleanup

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/LayoutContainerImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/PanelContainerImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/PanelContainerItemImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/ResourceListItemImpl.java
| Fixed Issues?            | Fixes #1112 
| Tests Added + Pass?      | None added, all pass
- Fixes a possible NPE in the `LayoutContainerImpl.initModel()` method.
- Clean up `ResourceListItemImpl` by removing the unused `url` field and unused `request` constructor parameter.
- For classes that were touched in this PR, javadocs are added for any undocumented members.
=> [LayoutContainer] Fix possible NPE in `LayoutContainerImpl` + cleanup

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/TeaserImpl.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/TeaserImplTest.java, bundles/core/src/test/resources/teaser/exporter-teaser9.json
| Fixed Issues?            | Fixes #1102 
- Modifies the `TeaserImpl` class such that, when the title link is derived from the first CTA, it does not matter if the CTA link URL points to an internal or external page (alternative solution to PR #1103).
- Adds javadoc comments to private members of TeaserImpl.
- Significant rewrite of field initialization/getters so that the initialization logic for each field is contained within its own getter instead of all in …
=> [Teaser] Fix inconsistent `linkURL` behaviour + cleanup

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/PanelContainerImpl.java
| Fixed Issues?            | fixes #1139 
| Tests Added + Pass?      | no
| Documentation Provided   | no (code comments and or markdown)
The combination of [@JsonUnwrapped](https://github.com/adobe/aem-core-wcm-components/blob/7dc6c2dbe1d5efbf21a16973752bcd75fa2f4ca0/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/PanelContainerImpl.java#L93) and  [getExportedType](https://github.com/adobe/aem-core-wcm-components/blob/7dc6c2dbe1d5efbf21a16973752bcd75fa2f4ca0/bundles/core/src/main/java/com/adobe/cq/wcm/core/compo …
=> issue/1139 Duplicate ":type" keys

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/AbstractListItemImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/BreadcrumbImpl.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/BreadcrumbImplTest.java, bundles/core/src/test/resources/breadcrumb/exporter-breadcrumb-page-without-jcrcontent.json, bundles/core/src/test/resources/breadcrumb/test-content.json
- add null check
- don't create a breadcrumb item when the corresponding page does not have a jcr:content node
- add tests
=> GH-1146 - Breadcrumb component cannot be edited in page template editor

content/src/content/jcr_root/apps/core/wcm/components/container/v1/container/responsiveGrid.html
| Fixed Issues?            | Fixes #1151 
| Tests Added + Pass?      | New not yet added, but existing ones are passing
| Documentation Provided   | Not required here
* resource could be a wrapped one with resourceType=`core/wcm/components/container/v1/container`, so use resource.path for rendering it as `wcm/foundation/components/responsivegrid` so that it is re-resolved with the correct resourceType.
* With the fix provided in CQ-4294035, the responsiveGrid resource info is retained and re-resolving using path has been avoided. So, before that …
=> Container children are no longer rendered on the page when layout is responsiveGrid

content/src/content/jcr_root/apps/core/wcm/components/container/v1/container/responsiveGrid.html
* Reverts adobe/aem-core-wcm-components#1152
* The issue is now being fixed in CQ code through an alternate approach which seems more proper i.e. by adding support for `ResourceWrapper`  in the `ResponsiveGrid`
* This change done earlier in the Core components was against what is recommended in the HTL docs, hence reverting that. See - https://docs.adobe.com/content/help/en/experience-manager-htl/using/htl/block-statements.html#path-not-required
=> Revert "Container children are no longer rendered on the page when layout is responsiveGrid"

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/Utils.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/ClientLibrariesImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/ComponentFilesImpl.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/UtilsTest.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/ClientLibrariesImplTest.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/ComponentFilesImplTest.java
| Fixed Issues?            | Fixes #1118 
| Tests Added + Pass?      | none added
@vladbailescu Sorry I already had this staged when i saw you pushed #1120. I should have clarified that I would suggest a solution. I'll offer it up anyway if there is any interest in it.
- Removes utility for creating service resource resolvers with elevated permissions; requires caller to provide resource resolver
- Uses try-with-resource from caller (`ComponentFilesImpl` & `ClientLibrariesImpl`) to ensure that …
=> Ensure service resource resolvers are closed

content/src/content/jcr_root/apps/core/wcm/components/contentfragmentlist/v1/contentfragmentlist/clientlibs/editor/js/contentfragmentlist.js
| Fixed Issues?            | Fixes #1077  
| Tests Added + Pass?      | no
| Documentation Provided   | no (code comments and or markdown)
The fetchedState is missing the referenced items, causing an undefined error. We instead use jQuery to find the objects to compare. The orderBy list now properly updates.
=> issue/1077 Order By not updating on change

README.md, parent/pom.xml
fixed #1191 
- added link to external hosted javadoc 
- fixed styling issues for generated javadoc
- updated to lastest maven-javadoc-plugin version
=> Publish JavaDoc

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/AbstractContainerImpl.java
Fixes #1187
Adapt from current resource instead of current request to TemplatedResource, to avoid empty list of children when request.getResource() already returns a templated resource.
=> [Container] Fixes #1187 - Simple mode broken when using Sling Model Delegation Pattern

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/TeaserImpl.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/TeaserImplTest.java, bundles/core/src/test/resources/teaser/exporter-teaser13.json, bundles/core/src/test/resources/teaser/test-content.json, content/src/content/jcr_root/apps/core/wcm/components/teaser/v1/teaser/README.md, content/src/content/jcr_root/apps/core/wcm/components/teaser/v1/teaser/_cq_dialog/.content.xml
- add "titleType" property in component dialog so it's possible to override the default tag
| Fixed Issues?            | CIF-1660, #684
| Minor: New Feature?      | yes
This PR extends the component dialog of the Teaser component with the ability to select/override the tag for the title element. See the screenshot.
=> CIF-1660 - Configurable header tag for teaser component

content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion/clientlibs/site/js/accordion.js, content/src/content/jcr_root/apps/core/wcm/components/carousel/v1/carousel/clientlibs/site/js/carousel.js, content/src/content/jcr_root/apps/core/wcm/components/commons/editor/clientlibs/panelcontainer/v1/js/PanelContainer.js, content/src/content/jcr_root/apps/core/wcm/components/tabs/v1/tabs/clientlibs/site/js/tabs.js
* Using `MessageChannel` instead of `ContentFrame.postMessage`
Fixes #1226
=> Multi-panel container components should not directly use `ContentFrame` to send/receive messages between editor and content frames

examples/ui.apps/src/content/jcr_root/apps/core-components-examples/components/accordion/.content.xml, examples/ui.apps/src/content/jcr_root/apps/core-components-examples/components/carousel/.content.xml, examples/ui.apps/src/content/jcr_root/apps/core-components-examples/components/tabs/.content.xml, extensions/amp/content/src/content/jcr_root/apps/core/wcm/extensions/amp/components/carousel/v1/carousel/.content.xml, extensions/amp/content/src/content/jcr_root/apps/core/wcm/extensions/amp/components/tabs/v1/tabs/.content.xml
add missing `cq:isContainer` for example components as this property is not inherited in AEM 6.4
=> Add missing cq:isContainer property for example components

content/src/content/jcr_root/apps/core/wcm/components/page/v1/page/_cq_dialog/.content.xml
Updating value cq-msm-lockable to correct name i.e. "variantPath"
=> CQ-4309183 Inherited deep properties live copy content are not visible though the value shows in crx/de.

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/ListImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/PageListItemImpl.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/ListImplTest.java
| Fixed Issues?            | Fixes #1269 
- Changes the list item sorting of the `ListImpl` to match the titles produced by `PageListItemImpl` to ensure that the list items are sorted consistent with how they are presented.
- The comparator used for sorting the list pages is updated to prevent the construction of the title comparator unless sorting by titles is enabled.
- Additional JavaDoc comments are added to `PageListItemImpl`.
=> [List] Correct sort ordering not matching list item title (#1269)

content/src/content/jcr_root/apps/core/wcm/components/image/v2/image/clientlibs/site/js/image.js
Fixed image lazy loading loadImage so it doesn't replace dynamically swapped images on scroll event.  When custom javascript does an intentional swap on the img src attribute of a lazyloaded image, it swaps back to the original when the user scrolls the browser window.  Instead it should be compared to the placeholder.
| Fixed Issues?            | Fixes #1330
| Major: Breaking Change?  | 
Instead of comparing to URL of src, compare against EMPTY_PIXEL placeholder:
Before:
```
if …
```
=> Avoid swapping image back on scroll event

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/SearchResultServlet.java
| Fixed Issues?            |  #835
| Patch: Bug Fix?          | 👍 
| Minor: New Feature?      | 👍 
| Major: Breaking Change?  | 👍 
Extended the core Search component and authored the Search component in XF (Experience Fragment) configured the search component.
ex : 
Search Root * :  "/content/project/us/en/abc" 
Search component searches from "/Content/project/*"
Experience Fragment with Search component included in the page, Search results are different from configured "Search Root *".
Changes I have made in [0] finding the "fragmentPath" and …
=> [Search] Results are not limited to specified directory #835

content/src/content/jcr_root/apps/core/wcm/components/form/options/v2/options/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/form/text/v2/text/_cq_dialog/.content.xml
| Fixed Issues?            | Fixes #1259 
| Major: Breaking Change?  | Possibly, if customers are overriding form/text/v2/cq:dialog and expected the "About" section to be located inside `<properties>`
- Changes "Form Text Field"'s "Element Name" label to "Name" to be in line with "Form Options Text"
- Moves "Form Option Field"'s "About" section to a dedicated tab and removes the headings "Main" and "About"
=> [Form Text & Form Options] Fixes #1259: Streamline form text and form options dialog

content/src/content/jcr_root/apps/core/wcm/components/form/text/v2/text/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/form/text/v2/text/clientlibs/site/js/text.js
| Fixed Issues?         | Fixes #1257
Changes the wrapperClass to be in line with the clientlib so that the DOM node can be found and shown/hidden in `content/src/content/jcr_root/apps/core/wcm/components/form/text/v1/text/clientlibs/editor/js/editDialog.js` (`handleTextarea`)
=> [Form Text] Fixes #1257: Ensure "Text Lines" is shown/hidden based on the chosen Constraint

content/src/content/jcr_root/apps/core/wcm/components/form/options/v2/options/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/form/text/v2/text/_cq_dialog/.content.xml
Follow up for #1260 
Changes applied to original PR:
* removed about section
* added main and about headings back
All changes that updated PR provides:
* Changes "Form Text Field"'s "Element Name" label to "Name" to be in line with "Form Options Text"
=> [Form Text & Form Options] Fixes #1259: Streamline form text

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/AbstractContainerImpl.java
Fixes #1187 
the first PR that was included in 2.12.0 was reverted in 2.12.2 (see [here](https://github.com/adobe/aem-core-wcm-components/issues/1187#issuecomment-724828689)) - this is a new PR which should over all use cases.
=> Fixes #1187 (2nd try): try to get TemplatedResource from current resource, and fallback to current request's resource

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServlet.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServletMappingConfigurationConsumer.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServletMetrics.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServletMappingConfigurationConsumerTest.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServletMetricsTest.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServletTest.java
| Fixed Issues?            | Fixes #1292
| Patch: Bug Fix?          | 
| Documentation Provided   | Inline
The AdaptiveImageServlet now maintains statistics as Sling Metrics, which you can check via /system/console/slingmetrics.
| Name | Description
|--------|--------
|sling:com.adobe.cq.wcm.core.components.internal.servlets.AdaptiveImageServlet:invocations| Number of total invocations of the AdaptiveImageSerlvet (Counter)
|sling:com.adobe.cq.wcm.core.components.internal.servlets.AdaptiveImageServlet:rendition-rendered | counts how often a …
=> Add runtime statistics for the AdaptiveImageServlet 

content/src/content/jcr_root/apps/core/wcm/components/text/v2/text/_cq_design_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/text/v2/text/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/text/v2/text/_cq_editConfig.xml
| Fixed Issues?            | Fixes #1293 
In order to improve RTE usability in the Text Component the following changes are included:
1. Providing the possibility to enable anchor links via policies.
2. Adding the missed "justifyjustify" feature of the "justify" RTE plugin to the dialog compact toolbar.
3. Making RTE plugins/features set in the inline compact toolbar the same as in the dialog compact toolbar.
=> Improve RTE usability in the Text Component

content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion/accordion.html, content/src/content/jcr_root/apps/core/wcm/components/carousel/v1/carousel/carousel.html, content/src/content/jcr_root/apps/core/wcm/components/commons/editor/clientlibs/parsysplaceholder/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/commons/editor/clientlibs/parsysplaceholder/js.txt, content/src/content/jcr_root/apps/core/wcm/components/commons/editor/clientlibs/parsysplaceholder/js/parsys-placeholder.js, content/src/content/jcr_root/apps/core/wcm/components/tabs/v1/tabs/tabs.html
| Fixed Issues?            | `Fixes #1076
| Minor: New Feature?      | yes
| Tests Added + Pass?      | no
| Documentation Provided   | no
Resubmitted PR (original #1099), fixed some linting and jquery issues. Tested against cloud ready and 6.5.7.
Makes the placeholder text for adding new components to a container that is inside a Carousel, Tab or Accordion more specific to improve author experiences. E.g. instead of `Drag component here `it will say `Please add Carousel Components here`, and the strings are i18n.
=> Add specific placeholder text for container component inside Panel Containers

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServlet.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServletMappingConfigurationConsumer.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServletMetrics.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServletMappingConfigurationConsumerTest.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServletMetricsTest.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServletTest.java
| Fixed Issues?            | Fixes #1292
| Patch: Bug Fix?          | 
| Documentation Provided   | Inline
The AdaptiveImageServlet now maintains statistics as Sling Metrics, which you can check via /system/console/slingmetrics.
=> Add runtime statistics for the AdaptiveImageServlet (#1305)

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/ContentFragmentUtils.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/ExperienceFragmentImpl.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/ExperienceFragmentImplTest.java, bundles/core/src/test/resources/experiencefragment/exporter-xf70.json
| Q                        | A
| Fixed Issues?            | Fixes #1135 
- Fixes possibly incorrect exported items ordering by ensuring that the `children` models maintain the order that they are encountered in the repository.
- Corrects tests to match
- Replaces `Nonnull` annotations with `NotNull`
- Adds JavaDoc to previously undocumented members of `ExperienceFragmentImpl`, and correct several existing javadoc issues.
- Moves much of the model initializers to their respective getter methods …
=> [ExperienceFragment] Fix incorrect exported items order

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/config/AttributeConfig.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/config/HtmlPageItemConfig.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/config/HtmlPageItemsConfig.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v2/HtmlPageItemImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v2/PageImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/HtmlPageItem.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/package-info.java
Fixes #1234
| Fixed Issues?            | Fixes #1234
| Patch: Bug Fix?          | x
| Minor: New Feature?      | :+1: 
| Major: Breaking Change?  | :+1: 
| Tests Added + Pass?      | x
This PR adds two new Context-aware configurations:
- `com.adobe.cq.wcm.core.components.config.HtmlPageItemConfig`
- `com.adobe.cq.wcm.core.components.config.AttributeConfig`
They are used as child configurations in the already existing `com.adobe.cq.wcm.core.components.config.HtmlPageItemsConfig`.
This unfortunately implies a change in the config's structure as child configs are now stored under …
=> [HTML Page Items] Improve HtmlPageItemsConfig by exposing the whole config as API

examples/ui.apps/pom.xml, extensions/amp/content/pom.xml, parent/pom.xml
Add node type definitions for improved validation.
Add validator to check for /var nodes in packages
This closes #1368
| Fixed Issues?            | Fixes #1368
=> Update to filevault-package-maven-plugin 1.1.6

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/services/CaConfigReferenceProvider.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/services/CaConfigReferenceProviderTest.java
* Update reference provider to pick configurations dinamically
* Updated test
Fixes #1393
=> CaConfigReferenceProvider hardcodes references to specific Core Components context-aware configs #1393

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServlet.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/AbstractImageTest.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServletTest.java, bundles/core/src/test/resources/image/test-content.json
As described in the issue, requesting a core image component that has a file reference which points to a non existinga asset triggers several exceptions and results the request to be responded as a 500 instead of a 404.
I fixed this by simply null checking the imageResource before setting the source to Source.ASSET. The source will remain to be set to Source.NONEXISTING and the therefore correctly be treated as nonexisting (404)
There is a description on how to reproduce this as well as an example har file attached to the ticket. 
I added an unit-test to ensure the HttpServletResponse code to be correct.
Fixes #1414
=> nullcheck to avoid 500 if asset does not exist #1414

testing/it/http/pom.xml
| Fixed Issues?            | Fixes #1438
| Patch: Bug Fix?          | bug
| Documentation Provided   | not needed
removed `<systemPropertyVariables>` set for `granite.it.author.url` and `granite.it.publish.url` as this can lead to miss-configured instances if used together with `sling.it.instances.*` properties
=> IT HTTP tests fail when defined to run with random AEM Ports

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/ComponentImpl.java
| Fixed Issues?            |  Fixes #1447 
Adds the resource type "cq:Component" to the model definition for
the default Component implementation (`ComponentImpl`).
This change allows other models to indicate `Component.class` as an
adapter, and have those models take precedence based on resource type
hierarchy, without interfering with `ComponentImpl` being used as the
default fallback for any component that does not have a model with
a more specific resource …
=> Specify "cq:Component" as model resource type for `ComponentImpl`

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/LayoutContainerImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/LayoutContainer.java, content/src/content/jcr_root/apps/core/wcm/components/container/v1/container/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/container/v1/container/responsiveGrid.html, content/src/content/jcr_root/apps/core/wcm/components/container/v1/container/simple.html
- allow authors to define the aria-label attribute on the same tab of the edit dialog, for the container component.
Fixes #1469
=> [Accessibility][Container] Allow to define ARIA labels on the container 

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/link/LinkHandler.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/AbstractContainerImpl.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/DownloadImplTest.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/LayoutContainerImplTest.java, bundles/core/src/test/resources/container/test-content.json, bundles/core/src/test/resources/download/exporter-download-fully-configured-file.json, bundles/core/src/test/resources/download/exporter-download-fully-configured.json, bundles/core/src/test/resources/download/exporter-download-with-dam-properties.json, bundles/core/src/test/resources/download/exporter-download-with-title-type.json, bundles/core/src/test/resources/download/exporter-download-without-action-text.json
* Updated background image URL to use LinkHandler logic
* Updated LinkHandler to also try to map non-page links
* Updated Download component tests and test content to account for the fact that now asset links get mapped
Fixes #1468
=> [Container] Background image with whitespace do not work

content/src/content/jcr_root/apps/core/wcm/components/commons/editor/dialog/childreneditor/v1/childreneditor/clientlibs/js/childreneditor.js
- use correct event for unbinding select list changes
fixes #1489
| Fixed Issues?            | Fixes #1489 
=> Creation of multiple items throw JS error

content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion/clientlibs/editor/js/accordion.js
* Added check to prevent throwing an exception for undefined/null overlays.
Closes #1510
=> [Accordion] Style System selection is being ignored for accordion

examples/ui.apps/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-site/styles/base/base.less, examples/ui.apps/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-site/styles/components/accordion.less, examples/ui.apps/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-site/styles/components/button.less, examples/ui.apps/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-site/styles/components/demo.less, examples/ui.apps/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-site/styles/components/form-text.less, examples/ui.apps/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-site/styles/components/teaser.less, examples/ui.apps/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-themes/core-components-clean/styles/components/carousel/base.less, examples/ui.apps/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-themes/core-components-clean/styles/components/tabs/base.less
- brings back focus indicator as a css outline in components library clientlibs (clientlib-site + core-components-clean)
| Fixed Issues?            | fixes #1470
| Patch: Bug Fix?          | 
| Documentation Provided   |
=> [Accessibility] css outline as a focus indicator (#1470)

content/src/content/jcr_root/apps/core/wcm/components/breadcrumb/v2/breadcrumb/breadcrumb.html, content/src/content/jcr_root/apps/core/wcm/components/languagenavigation/v1/languagenavigation/itemContent.html
- add aria-current to breadcrumb and language navigation component
| Fixed Issues?            | Fixes #688 
=> [Navigation][Accessibility] Inconsistent isActive behavior (#1519)

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/ImageImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/ListImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v2/PageListItemImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v3/ImageImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v3/ListImpl.java, bundles/core/src/test/resources/image/v3/exporter-image50.json, bundles/core/src/test/resources/list/v3/exporter-listRenderedAsTeaserItems.json, bundles/core/src/test/resources/list/v3/test-content.json
- Image: when the image has no content (neither DAM reference nor uploaded file), get the DAM reference or uploaded file from the featured image and do not inherit other properties from the featured image
- List: support setting the Item Settings of the dialo (link items, show description) when displaying items as teasers
| Fixed Issues?            | `Fixes #1592`
=> GH-1592 - [FeaturedImage][Image][List] Improve inheritance of properties

content/src/content/jcr_root/apps/core/wcm/components/image/v2/image/clientlibs/site/js/image.js
Fixes #1581
The fix for issue #1330 introduced a regression in that the image component is no longer selecting the proper rendition on events like resize etc.
=> [IMG] Image Rendition Selection not working properly

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/link/DefaultPathProcessor.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/services/CaConfigReferenceProvider.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/services/CaConfigReferenceProviderTest.java, bundles/core/src/test/resources/com/adobe/cq/wcm/core/components/internal/services/CaConfigReferenceProvider/test-sling-configs.json, testing/it/e2e-selenium/pom.xml, testing/it/http/pom.xml
- check last modified time of page content if config is a Page
- provide OSGi config to disable reference provider, default is enabled
- adapt unit tests
fixes #1558
| Fixed Issues?            | Fixes #1558 
| Any Dependency Changes?  | 👎
=> Add support for CA configs stored as Pages

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/ImageImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServlet.java
- get the mime type of an uploaded image from its jcr:mimeType property
- uploaded image: add a default (white) background to a transparent JPG (same behaviour when the image is a DAM asset)
| Fixed Issues?            | Fixes #1615
| Documentation Provided   | NA
=> GH-1615 - [Image] a black background is added when uploading a PNG image

content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion/clientlibs/site/js/accordion.js, content/src/content/jcr_root/apps/core/wcm/components/commons/site/clientlibs/container/js/containerUtils.js, content/src/content/jcr_root/apps/core/wcm/components/tabs/v1/tabs/clientlibs/site/js/tabs.js
- fixes the issue existent with Chrome and related browsers, which are not implementing as expected the deep linking for the item of the container (Tabs, Accordion) component, when the URI fragment is changed. In the current behaviour, the browser scrolls to the item, but don't expand its content. This behaviour is fixed in this PR and the content is also displayed, without having to reload the page.
- fixes the issue existent with Chrome and related browsers, which are not scrolling on page reload (if URL contains URI fragment) to the item of the container component (Tabs, Accordion) component that corresponds to the deep link in the URL fragment.
Fixes #1614, #1432
=> SITES-1051-Avoid page reload when hash location changes

examples/ui.apps/src/content/jcr_root/apps/core-components-examples/components/demo/properties/list.html
In the Component Library, hide the AEM properties like jcr:primaryType, jcr:createdBy, jcr:lastModified and jcr:lastModifiedBy.
This makes that the demo component filters out these properties that are mostly ignored by the Core Components.
=> Hide the AEM system properties

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/datalayer/EmbeddableDataImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/datalayer/builder/DataLayerSupplierImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/embeddable/YouTubeImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/datalayer/EmbeddableData.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/datalayer/builder/ComponentDataLayerExtender.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/datalayer/builder/DataLayerBuilder.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/datalayer/builder/DataLayerSupplier.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/datalayer/builder/EmbeddableDataBuilder.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/datalayer/builder/package-info.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/embeddable/Embeddable.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/embeddable/YouTube.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/embeddable/package-info.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/embeddable/YouTubeImplTest.java, content/src/content/jcr_root/apps/core/wcm/components/embed/v1/embed/embed.html, content/src/content/jcr_root/apps/core/wcm/components/embed/v1/embed/embeddable/youtube/youtube.html, content/src/content/jcr_root/apps/core/wcm/components/embed/v2/embed/embed.html
- add DataBuilder for Embeddable
- add DataLayer support to youtube embeddable as an example to provide the videoId
fixes #1638
| Fixed Issues?            | Fixes #1638 
| Patch: Bug Fix?          | 👎
=> [Embed] Add Data Layer support

bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/AbstractImageTest.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/ImageImplTest.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v2/ImageImplTest.java, bundles/core/src/test/resources/image/exporter-image_template_no_date.json, bundles/core/src/test/resources/image/test-conf.json, bundles/core/src/test/resources/image/test-content-dam.json, bundles/core/src/test/resources/image/v2/exporter-image_template_no_date.json, bundles/core/src/test/resources/image/v2/test-conf.json, bundles/core/src/test/resources/image/v3/exporter-image_template_no_date.json, bundles/core/src/test/resources/image/v3/test-conf.json, testing/it/it-content/package-lock.json, testing/it/it-content/package.json
* Added unit tests for changes in #1651
=> Components Library logo does not show up on publish instances after release 2.17.0 #1650

content/src/content/jcr_root/apps/core/wcm/components/image/v2/image/clientlibs/site/js/image.js
| Fixed Issues?            | Fixes #1662 
| Documentation Provided   | n/a
Updates the V2 Image JS to prevent replacing the image `src` attribute with the same value.
=> [Image V2] Don't update image `src` with same value

content/src/content/jcr_root/apps/core/wcm/components/image/v2/image/clientlibs/editor/js/image.js
- add check for null pointer if no asset is drag'n dropped
| Fixed Issues?            | Fixes #1635 
=> Fix JS error if asset tab is hidden

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/form/ContainerImpl.java
- always init formid request attribute even an ID is given
fixes #1687
| Fixed Issues?            | Fixes #1687 
=> Enforce init formid request attribute

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v2/PageImpl.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v2/PageImplTest.java
| Fixed Issues?            | CIF-2249
In order to handle the existence of multiple `PathProcessor` services consistently the `PageImpl` must use the `LinkHandler` when falling back on getting the canonical url and the sites-seo api/implementation is missing.
=> CIF-2249: Use LinkHandler for PageImpl#getCanonicalLink() fallback

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/link/DefaultPathProcessor.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/link/LinkHandler.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/services/link/PathProcessor.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/services/link/package-info.java
- extend PathProcessor interface to process html attributes
- add default handling to the DefaultPathProcessor
| Fixed Issues?            | Fixes #1702 
=> Add process html attributes to the PathProcessor interface

content/src/content/jcr_root/apps/core/wcm/components/page/v2/page/body.skiptomaincontent.html
Remove alt attribute on "skip to main content"-link since it's invalid HTML.
Using the [title attribute is discouraged](https://html.spec.whatwg.org/multipage/dom.html#attr-title). In my opinion, the link label should be sufficient, therefore I'd suggest to remove the alt-attribute without replacing it.
| Fixed Issues?            | #1532
| Tests Added + Pass?      | No tests required
| Documentation Provided   | No update needed
=> fix(page): skiptomain invalid markup

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/commons/editor/dialog/inherited/PageImageThumbnail.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/Utils.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/ImageImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/TeaserImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v2/TeaserImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v3/ImageImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/resource/CoreResourceWrapper.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServlet.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Image.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/commons/editor/dialog/PageImageThumbnailTest.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v2/TeaserImplTest.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/resource/CoreResourceWrapperTest.java, bundles/core/src/test/resources/commons/editor/dialog/pageimagethumbnail/test-content.json, bundles/core/src/test/resources/teaser/v2/exporter-teaser12.json, bundles/core/src/test/resources/teaser/v2/exporter-teaser20.json, content/package-lock.json, content/src/content/jcr_root/apps/core/wcm/components/commons/editor/dialog/pageimagethumbnail/v1/pageimagethumbnail/clientlibs/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/commons/editor/dialog/pageimagethumbnail/v1/pageimagethumbnail/clientlibs/css.txt, content/src/content/jcr_root/apps/core/wcm/components/commons/editor/dialog/pageimagethumbnail/v1/pageimagethumbnail/clientlibs/css/pageimagethumbnail.less, content/src/content/jcr_root/apps/core/wcm/components/commons/editor/dialog/pageimagethumbnail/v1/pageimagethumbnail/pageimagethumbnail.html, content/src/content/jcr_root/apps/core/wcm/components/image/v3/image/README.md, content/src/content/jcr_root/apps/core/wcm/components/image/v3/image/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/image/v3/image/clientlibs/editor/js/image.js, content/src/content/jcr_root/apps/core/wcm/components/teaser/v2/teaser/README.md, content/src/content/jcr_root/apps/core/wcm/components/teaser/v2/teaser/_cq_dialog/.content.xml, extensions/amp/content/package-lock.json
- support inheriting the image and the alternative text from the featured image of the linked page if defined or from the current page
- share the same logic and UI between the Image v3 and Teaser v2
- update current tests
| Fixed Issues?            | Fixes #1710
Unit and Selenium tests are currently being worked on and will be added later: tracked with https://github.com/adobe/aem-core-wcm-components/issues/1722
=> GH-1710 - [Teaser] Inherit page image

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/PageImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Page.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/PageImplTest.java, bundles/core/src/test/resources/page/exporter-templated-page.json, bundles/core/src/test/resources/page/v2/exporter-templated-page.json, bundles/core/src/test/resources/page/v3/exporter-templated-page.json, content/src/content/jcr_root/apps/core/wcm/components/page/v1/page/head.html, content/src/content/jcr_root/apps/core/wcm/components/page/v2/page/head.html, content/src/content/jcr_root/apps/core/wcm/components/page/v3/page/head.html
The page's `head.html` renders the page description using `${properties[jcr:description]}` which does not allow any pages to overwrite the description without overwriting the head.html. For CIF we did this in our own page component but now have additional efforts to keep track on the latest features of the WCM Core Components Page. 
In this PR I added a `getDescription()` to the `Page` model which custom …
=> CIF-2293: get page description from page model

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/HtmlPageItem.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v2/PageImplTest.java, bundles/core/src/test/resources/page/v2/exporter-templated-page.json, bundles/core/src/test/resources/page/v2/test-sling-configs-deprecated-caconfig.json, bundles/core/src/test/resources/page/v2/test-sling-configs.json, bundles/core/src/test/resources/page/v3/exporter-templated-page.json, bundles/core/src/test/resources/page/v3/test-sling-configs-deprecated-caconfig.json, bundles/core/src/test/resources/page/v3/test-sling-configs.json
- adds the missing `as` attribute
- updates test cases to check for this attribute
| Fixed Issues?            | `Fixes #1823` 
=> Allow <link rel="preload" as="style"..> for links injected with HtmlPageItemsConfig

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/link/LinkHandler.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/servlets/SearchResultServletTest.java, bundles/core/src/test/resources/search/test-content.json
* Use page manager from page to prevent NPE
* Updated test content and expected results to include a redirect page
Fixes #1848
=> [Search v1] The searching is breaking when some of the page found has a redirect link

content/src/content/jcr_root/apps/core/wcm/components/commons/v1/templates/clientlib.html, content/src/content/jcr_root/apps/core/wcm/components/page/v3/page/body.skiptomaincontent.html, content/src/content/jcr_root/apps/core/wcm/components/page/v3/page/body.socialmedia_begin.html, content/src/content/jcr_root/apps/core/wcm/components/page/v3/page/footer.html, content/src/content/jcr_root/apps/core/wcm/components/page/v3/page/head.html, content/src/content/jcr_root/apps/core/wcm/components/page/v3/page/headlibs.html, testing/it/http/src/test/java/com/adobe/cq/wcm/core/components/it/http/ClientlibsIncludeIT.java, testing/it/ui-js/src/content/jcr_root/apps/core/wcm/tests/components/clientlibs-include/.content.xml, testing/it/ui-js/src/content/jcr_root/apps/core/wcm/tests/components/clientlibs-include/clientlibs/.content.xml, testing/it/ui-js/src/content/jcr_root/apps/core/wcm/tests/components/clientlibs-include/clientlibs/site/.content.xml, testing/it/ui-js/src/content/jcr_root/apps/core/wcm/tests/components/clientlibs-include/clientlibs/site/css.txt, testing/it/ui-js/src/content/jcr_root/apps/core/wcm/tests/components/clientlibs-include/clientlibs/site/css/test.less, testing/it/ui-js/src/content/jcr_root/apps/core/wcm/tests/components/clientlibs-include/clientlibs/site/js.txt, testing/it/ui-js/src/content/jcr_root/apps/core/wcm/tests/components/clientlibs-include/clientlibs/site/js/test.js, testing/it/ui-js/src/content/jcr_root/apps/core/wcm/tests/components/clientlibs-include/includeall.html, testing/it/ui-js/src/content/jcr_root/apps/core/wcm/tests/components/clientlibs-include/includecss.html, testing/it/ui-js/src/content/jcr_root/apps/core/wcm/tests/components/clientlibs-include/includejs.html, testing/it/ui-js/src/content/jcr_root/content/core-components/clientlibs-include-page/.content.xml
- introduce a template in commons to include clientlibs with specific attributes (e.g. async, defer, …) based on the `com.adobe.cq.wcm.core.components.models.ClientLibraries` model
- page v3: use this template to include all the client libraries
- page v3: include the JS libraries with the `async` attribute
| Fixed Issues?            | Fixes #1880 
=> GH-1880 - [Page] Load all clienlibs with async

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/TeaserImpl.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/TeaserImplTest.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v2/TeaserImplTest.java, bundles/core/src/test/resources/teaser/exporter-teaser11.json, bundles/core/src/test/resources/teaser/test-content.json, bundles/core/src/test/resources/teaser/v2/exporter-teaser11.json, bundles/core/src/test/resources/teaser/v2/test-content.json
Fixes #1882 
It would be nicer to use StringEscapeUtils.escapeHtml, but this method is deprecated in commons-lang, and common-text is not shipped by default in AEM.
=> #1882 [Teaser] Teaser description inherited from page properties needs to be HTML-escaped

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Component.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/contentfragment/package-info.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/datalayer/jackson/ComponentDataModelSerializer.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/datalayer/jackson/package-info.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/embeddable/Embeddable.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/package-info.java
- move ComponentDataModelSerializer to an exported package as it is used by the Component interface
fixes #1834
| Fixed Issues?            | Fixes #1834 
=> Cannot mock some models with mockito

content/src/content/jcr_root/apps/core/wcm/components/commons/site/clientlibs/container/js/containerUtils.js
- uses getElementById, which is more forgiving - it returns null if the passed ID is non-conforming to the standard
| Fixed Issues?            | `Fixes #1900` 
=> [ContainerUtils] Scroll to anchor logic fails for invalid ID hashes

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v2/ImageImpl.java
Fixes the Issue mentioned on : https://github.com/adobe/aem-core-wcm-components/issues/1884
"If content is transferred to other AEM environments all those properties might need to be updated because the target environment might be configured to a different DM catalog using a different host name. Additionally, this host name is already stored in each DM asset itself and can just be read from there (also on publish instances)."
| Fixed Issues?            | Fixes https://github.com/adobe/aem-core-wcm-components/issues/1884 
| Any Dependency …
=> Updated Image component DM url creation logic to get rid of the 'imageServerUrl' property dependency generated by DMAssetPostProcessor

examples/ui.content/src/content/jcr_root/content/core-components-examples/library/core-content/button/.content.xml, examples/ui.content/src/content/jcr_root/content/core-components-examples/library/core-content/image/.content.xml, examples/ui.content/src/content/jcr_root/content/core-components-examples/library/core-content/list/.content.xml, examples/ui.content/src/content/jcr_root/content/core-components-examples/library/core-content/teaser/.content.xml, examples/ui.content/src/content/jcr_root/content/core-components-examples/library/core-content/title/.content.xml, examples/ui.content/src/content/jcr_root/content/core-components-examples/library/core-structure/breadcrumb/hidden/.content.xml, examples/ui.content/src/content/jcr_root/content/core-components-examples/library/core-structure/breadcrumb/hidden/level-1/.content.xml, examples/ui.content/src/content/jcr_root/content/core-components-examples/library/core-structure/breadcrumb/hidden/level-1/level-2/.content.xml, examples/ui.content/src/content/jcr_root/content/core-components-examples/library/core-structure/language-navigation/language-structure/de/.content.xml, examples/ui.content/src/content/jcr_root/content/core-components-examples/library/core-structure/language-navigation/language-structure/de/de/.content.xml, examples/ui.content/src/content/jcr_root/content/core-components-examples/library/core-structure/language-navigation/language-structure/de/de/language-navigation/.content.xml, examples/ui.content/src/content/jcr_root/content/core-components-examples/library/core-structure/language-navigation/language-structure/fr/.content.xml, examples/ui.content/src/content/jcr_root/content/core-components-examples/library/core-structure/language-navigation/language-structure/fr/fr/.content.xml, examples/ui.content/src/content/jcr_root/content/core-components-examples/library/core-structure/language-navigation/language-structure/fr/fr/language-navigation/.content.xml, examples/ui.content/src/content/jcr_root/content/core-components-examples/library/core-structure/language-navigation/language-structure/us/.content.xml, examples/ui.content/src/content/jcr_root/content/core-components-examples/library/core-structure/language-navigation/language-structure/us/en/.content.xml, examples/ui.content/src/content/jcr_root/content/core-components-examples/library/core-structure/language-navigation/language-structure/us/en/language-navigation/.content.xml, examples/ui.content/src/content/jcr_root/content/core-components-examples/library/core-structure/language-navigation/language-structure/us/es/.content.xml, examples/ui.content/src/content/jcr_root/content/core-components-examples/library/core-structure/language-navigation/language-structure/us/es/language-navigation/.content.xml, examples/ui.content/src/content/jcr_root/content/core-components-examples/library/core-structure/navigation/.content.xml
| Fixed Issues?            | Fixes #1955
=> [ComponentLibrary][Regression] Fix broken internal links

content/src/content/jcr_root/apps/core/wcm/components/breadcrumb/v3/breadcrumb/breadcrumb.html
- add aria-current="page" for the active breadcrumb item
| Fixed Issues?            | Fixes #1966 
=> GH-1966 - [Accessibility] Extend Breadcrumb component with Aria-current attribute for better accessibility

examples/ui.apps/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-site/scripts/demo.js
* Trigger the processing function even if the DOM was loaded before JS is executed
Fixes #1998
=> [Library] Demo component sometimes does not show the markup and JSON of the inner component

content/src/content/jcr_root/apps/core/wcm/components/title/v3/title/_cq_dialog/.content.xml
=> [Title V3]: Link input field still visible/active after disabling it in the policy

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v3/ListImpl.java, content/src/content/jcr_root/apps/core/wcm/components/list/v3/list/teaser.html
* Always include the link for teaser list items (is needed for inheritance)
* Disable WCM editing for embedded teaser components
Fixes #2000
=> [List] wrong title and link when rendering as teasers #2000

content/src/content/jcr_root/apps/core/wcm/components/title/v3/title/title.html
* Updated HTL markup to avoid spaces and new lines as it confuses the inline editor
* Added clickable data attribute back (needed for datalayer integration)
Fixes #2010
=> [Title V3] inline editing adds whitespaces in front in dialog input field

examples/ui.apps/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-base-amp/styles/base/teaser.less, examples/ui.apps/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-site/styles/components/teaser.less
In the teaser v2 removes styling that makes image overlap the title. Due to that issue it was impossible to click on the link in the title of teaser.
=> Teaser v2 fix for image overlapping link from the title (#2012)

content/src/content/jcr_root/apps/core/wcm/components/page/v3/page/body.html, testing/it/http/src/test/java/com/adobe/cq/wcm/core/components/it/http/page/v2/PageIT.java, testing/it/http/src/test/java/com/adobe/cq/wcm/core/components/it/http/page/v3/PageIT.java, testing/it/it.ui.content/src/content/jcr_root/conf/core-components/settings/wcm/template-types/.content.xml, testing/it/it.ui.content/src/content/jcr_root/conf/core-components/settings/wcm/template-types/test-page-v3/.content.xml, testing/it/it.ui.content/src/content/jcr_root/conf/core-components/settings/wcm/template-types/test-page-v3/initial/.content.xml, testing/it/it.ui.content/src/content/jcr_root/conf/core-components/settings/wcm/template-types/test-page-v3/policies/.content.xml, testing/it/it.ui.content/src/content/jcr_root/conf/core-components/settings/wcm/template-types/test-page-v3/structure/.content.xml, testing/it/it.ui.content/src/content/jcr_root/conf/core-components/settings/wcm/templates/simple-template-v3/.content.xml, testing/it/it.ui.content/src/content/jcr_root/conf/core-components/settings/wcm/templates/simple-template-v3/initial/.content.xml, testing/it/it.ui.content/src/content/jcr_root/conf/core-components/settings/wcm/templates/simple-template-v3/policies/.content.xml, testing/it/it.ui.content/src/content/jcr_root/conf/core-components/settings/wcm/templates/simple-template-v3/structure/.content.xml, testing/it/it.ui.content/src/content/jcr_root/content/core-components/simple-page/.content.xml, testing/it/it.ui.content/src/content/jcr_root/content/core-components/simple-page/simple-page-v3/.content.xml
- change body of pageV3 to render path of child resource so structured resources gets rendered in AEM 6.5
- add IT for PageV3 and a test for structure support
fixes #2039
| Fixed Issues?            | Fixes #2039 
=> Page V3 body htl is not rendering structure resources

content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/breadcrumb/v2/breadcrumb/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/button/v1/button/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/carousel/v1/carousel/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/container/v1/container/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/contentfragment/v1/contentfragment/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/contentfragmentlist/v1/contentfragmentlist/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/download/v1/download/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/embed/v1/embed/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/experiencefragment/v1/experiencefragment/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/form/button/v2/button/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/form/container/v2/container/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/form/hidden/v2/hidden/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/form/options/v2/options/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/form/text/v1/text/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/form/text/v2/text/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/image/v2/image/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/languagenavigation/v1/languagenavigation/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/list/v1/list/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/list/v2/list/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/navigation/v1/navigation/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/pdfviewer/v1/pdfviewer/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/progressbar/v1/progressbar/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/search/v1/search/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/separator/v1/separator/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/sharing/v1/sharing/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/tabs/v1/tabs/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/teaser/v1/teaser/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/text/v1/text/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/title/v2/title/_cq_dialog/.content.xml
- add styles tab with ns to old components
fixes #2045
| Fixed Issues?            | Fixes #2045 
=> Style tab is blank on components without styles / policies

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/ImageDelegateRenderCondition.java, content/src/content/jcr_root/apps/core/wcm/components/teaser/v1/teaser/_cq_design_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/teaser/v2/teaser/_cq_design_dialog/.content.xml
- set i18n expression for the image delegation in render condition
- use expression in the design dialog of the teaser component
| Fixed Issues?            | Fixes #2085 
=> [Teaser] Image delegation description is not internationalised

examples/ui.apps/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-themes/core-components-clean/styles/components/breadcrumb/base.less, examples/ui.apps/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-themes/core-components-clean/styles/components/breadcrumb/dark.skin.less, examples/ui.apps/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-themes/core-components-clean/styles/components/breadcrumb/light.skin.less
Fixes #1672
Uses` content: url(../../../resources/images/...)` CSS property for Component Library ->  Breadcrumb's decorative icons.
=> SITES-1858 [Accessibility][Breadcrumb][Sample CSS] Right chevron icons CSS "content" property value is read by NVDA

content/src/content/jcr_root/apps/core/wcm/components/navigation/v2/navigation/itemContent.html
| Fixed Issues?            | Fixes #2105
Fixes `aria-current` being set to `page` for all navigation links
that point to the current page _or_ an ancestor page. Navigation
links will now only have `aria-current` set to `page` if they point
to the current page (i.e. `current` instead of `active`)
=> [Navigation:V2][Accessibility] Fix improper `aria-current` attribute

examples/ui.apps/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-site/scripts/aside.js
Components Library provides additional aria attributes for main navigation on mobile:
- `aria-hidden` for button when it is disabled / when menu aside is visible
- `aria-expanded` for main navigation container to indicate its state
=> Main navigation on mobile with aria attributes in components library

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServlet.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/DownloadServlet.java, testing/it/e2e-selenium-utils/src/main/java/com/adobe/cq/wcm/core/components/it/seljup/util/Commons.java, testing/it/e2e-selenium-utils/src/main/java/com/adobe/cq/wcm/core/components/it/seljup/util/components/download/DownloadEditDialog.java, testing/it/e2e-selenium-utils/src/main/java/com/adobe/cq/wcm/core/components/it/seljup/util/components/download/v1/Download.java, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/download/v1/DownloadIT.java, testing/it/it.ui.apps/src/content/jcr_root/apps/core-component/components/download-v1/.content.xml
- revert changes from #1932
- add e2e test to prevent future regressions
fixes #2161
| Fixed Issues?            | Fixes #2161 
=> [Download] Wrong download filename on AEMaaCS environments

content/src/content/jcr_root/apps/core/wcm/components/image/v2/image/clientlibs/editor/js/image.js, content/src/content/jcr_root/apps/core/wcm/components/image/v3/image/clientlibs/editor/js/image.js, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/image/ImageTests.java, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/image/v2/ImageIT.java, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/image/v3/ImageIT.java, testing/it/it.ui.apps/package-lock.json, testing/it/it.ui.apps/package.json
=> SITES-6256 [Image] Improve error message when "Get alternative text from DAM" is used on an image bound to an asset not having a description

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v2/TeaserImpl.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v2/TeaserImplTest.java
| Fixed Issues?            | Fixes #2164
Changes the ID for the teaser image to be `<teaser_id>-image`.
By doing this there will never be a conflict between the teaser ID and the ID used on the teaser image, regardless of if the teaser's ID is set manually by the author or is generated automatically. 
----
refs #2164
=> [Teaser] Prevent same ID for teaser and teaser image (#2164)

content/src/content/jcr_root/apps/core/wcm/components/page/v3/page/_cq_dialog/.content.xml
- adding absolute cq-msm-lockable to featured image file and alt text widget
fixes #2166
| Fixed Issues?            | Fixes #12166
=> [Page][v3] Featured Image properties are overwritten after rollout

content/src/content/jcr_root/apps/core/wcm/components/image/v2/image/clientlibs/editor/js/image.js, content/src/content/jcr_root/apps/core/wcm/components/image/v3/image/clientlibs/editor/js/image.js
Fixes the following error introduced by this [PR](https://github.com/adobe/aem-core-wcm-components/pull/2188) in the  Page Properties of a Page.
```
Uncaught TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
at improveAltTextValidation (editor.lc-0ffd9019bdf8ca41494ce305191bd7ca-lc.js:553:18)
at HTMLDocument.<anonymous> (editor.lc-0ffd9019bdf8ca41494ce305191bd7ca-lc.js:156:9)
at HTMLDocument.dispatch (jquery.lc-676f843463ac676e1918c97ea7dc1a20-lc.js:5232:27)
at HTMLDocument.elemData.handle (jquery.lc-676f843463ac676e1918c97ea7dc1a20-lc.js:4884:28)
at Object.trigger (jquery.lc-676f843463ac676e1918c97ea7dc1a20-lc.js:5136:12)
at HTMLDocument.<anonymous> (jquery.lc-676f843463ac676e1918c97ea7dc1a20-lc.js:5866:17)
at Function.each …
```
=> Fix console error when accessing the Page Properties of a Page

README.md, all/pom.xml
A newer version is already shipped with the minimally required AEM
version
This closes #212
| Fixed Issues?            | Fixes #212
=> Remove embedded Sling Models Impl 1.4.12

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/TableOfContentsFilter.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/servlets/TableOfContentsFilterTest.java
| Fixed Issues?            | fixes #2229 ([SITES-6826](https://jira.corp.adobe.com/browse/SITES-6826))
If pages do not have contentType set a NPE can be caused on line 89:
https://github.com/adobe/aem-core-wcm-components/blob/main/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/TableOfContentsFilter.java#L89
=> [TOC] TableOfContentsFilter causing NPE

content/src/content/jcr_root/apps/core/wcm/components/teaser/v1/teaser/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/teaser/v2/teaser/_cq_dialog/.content.xml, parent/pom.xml, testing/it/e2e-selenium-utils/pom.xml, testing/it/e2e-selenium-utils/src/main/java/com/adobe/cq/wcm/core/components/it/seljup/util/components/teaser/v1/TeaserEditDialog.java, testing/it/e2e-selenium/pom.xml, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/teaser/v1/TeaserIT.java
* Added backwards compatibility fallback to old title type selection in case there are no configured allowed types/headings.
* Updated selenium base and fixed previously failing tests
* Added new IT
Fixes #2266
=> [Teaser] The setting of "Title Type" disappeared from Configure Dialog of Teaser component after #2142

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/link/LinkBuilderImpl.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/link/LinkBuilderImplTest.java
| Fixed Issues?            | Fixes #2271
| Documentation Provided   | Yes 
With #2196 urls get decoded before they are passed to the `PathProcessor`. This fails for links that are not well formed with an `IllegalArgumentException`, for example when they contain Adobe Campaign expressions. While it makes sense to decode urls before processing them, this may be a regression for email components.
With this PR all Adobe Campaign expressions in an url are replaced with placeholders before the url gets decoded. …
=> SITES-7428: mask Adobe Campaign expression before decoding URLs

content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion/README.md, content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion/clientlibs/editor/js/accordion.js, content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion/clientlibs/site/js/accordion.js
| Fixed Issues?            | Fixes #1256 
| Patch: Bug Fix?          | Y
| Minor: New Feature?      | Y
| Documentation Provided   | Yes (Updated readme)
Allows a single-expansion accordion to be configured to start with
all panels closed by default. Previously, this could only be done
in multi-expansion accordions.
This is accomplished by manually adding a "None" option to the initial
open panel dropdown in the edit dialog. Additionally, the code that
automatically opens the first panel if none is set as open (for single
expansion accordions) is removed from the site …
=> [Accordion] Allow single expansion to start with all closed

content/src/content/jcr_root/apps/core/wcm/components/image/v2/image/clientlibs/site/js/image.js
- add IntersectionObserver to trigger update and check if image is getting visible\
fixes #2291
| Fixed Issues?            | Fixes #2291
=> [ImageV2] Lazy loading image isn't getting visible inside of a Carousel

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/TableOfContentsFilter.java
- exit early when the page doesn't contain a TOC component
- exist early when the page is not of content type text/html
| Fixed Issues?            | Fixes #2300 
=> [TOC] Improve exit condition for TableOfContentsFilter

content/src/content/jcr_root/apps/core/wcm/components/image/v3/image/_cq_dialog/.content.xml
| Fixed Issues?            | Fixes #2311 
| Patch: Bug Fix?          | Y
----
- Changes the V3 dialog such that the "Disable lazy loading" option is hidden if "Disable lazy loading" is set in the policy (and thus lazy loading does not need to be disabled on individual component instances).
- Clarifies the field description to make it clear that the checkbox only applies to the image component instance currently being edited.
- Adds `@deleteHint=true` to the "Disable lazy loading" dialog option because …
=> [Image V3] Hide "Disable lazy loading" if disabled by policy

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/ContainerServlet.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/servlets/ContainerServletTest.java
- get forced resourceType from request parameter
-->
The container servlet is also used by the segmenteditor of the core email components project. As the segmenteditor relies on a different multifield item structure the container servlet needs to get the resource Type from the request parameter to render the correct output. Related issue of the core email components is …
=> [PanelContainer] Make container servlet resourceType aware

bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/servlets/TableOfContentsFilterTest.java
| Fixed Issues?            |  Fixes #2322
| Patch: Bug Fix?          | N
| Tests Added + Pass?      | No tests added - tests failing on Windows now pass
Normalizes the line endings in the `TableOfContentsFilterTest` to prevent spurious failures on some systems (i.e. windows).
This is accomplished by replacing all line separators in both the filter content and reference file with the system line seperator.
=> [ToC] Normalize line endings in tests

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/PageListItemImpl.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/ListImplTest.java, bundles/core/src/test/resources/list/test-content.json, bundles/core/src/test/resources/list/v3/test-content.json
| Fixed Issues?            |  Fixes #2316
| Patch: Bug Fix?          | Y
| Documentation Provided   | Yes (updated JavaDoc)
Updates the `PageListItemImpl` so that blank page titles are treated the same as null page titles. This prevents an empty title from being shown in lists if the title contains only whitespace.
Adds a test to verify the sorting of list items that have a whitespace-only title (sorts based on name instead of blank title).
----
Fixes #2316
=> [List] Prevent blank page titles

bundles/core/pom.xml, bundles/core/src/test/resources/tableofcontents/exporter-duplicate-ids-content.html, bundles/core/src/test/resources/tableofcontents/exporter-include-ignore-content.html, bundles/core/src/test/resources/tableofcontents/exporter-invalid-toc-content.html, bundles/core/src/test/resources/tableofcontents/exporter-nesting-content.html, bundles/core/src/test/resources/tableofcontents/exporter-no-heading-content.html, bundles/core/src/test/resources/tableofcontents/exporter-template-placeholder-content.html, bundles/core/src/test/resources/tableofcontents/test-duplicate-ids-content.html, bundles/core/src/test/resources/tableofcontents/test-nesting-content.html
| Fixed Issues?            | Fixes #2365
| Patch: Bug Fix?          | Y
| Tests Added + Pass?      | Yes (updated)
| Any Dependency Changes?  | Yes (embedded `jsoup` 1.14.3 -> 1.15.3)
Jsoup is upgraded to the latest version to rectify CVE-2022-36033.
Additionally, Jsoup 1.5.2+ trims whitespace during prettying; therefore, the output golden files to reflect this change.
See [Jsoup changelog](https://github.com/jhy/jsoup/blob/master/CHANGES) for version 1.5.2 for details.
=> Upgrade `org.jsoup:jsoup` -> 1.15.3

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/SeparatorImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Separator.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/SeparatorImplTest.java, bundles/core/src/test/resources/separator/test-content.json, content/src/content/jcr_root/apps/core/wcm/components/separator/v1/separator/README.md, content/src/content/jcr_root/apps/core/wcm/components/separator/v1/separator/_cq_design_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/separator/v1/separator/_cq_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/separator/v1/separator/separator.html, examples/ui.content/src/content/jcr_root/content/core-components-examples/library/core-content/separator/.content.xml, testing/it/e2e-selenium-utils/src/main/java/com/adobe/cq/wcm/core/components/it/seljup/util/Commons.java, testing/it/e2e-selenium-utils/src/main/java/com/adobe/cq/wcm/core/components/it/seljup/util/components/separator/SeparatorEditDialog.java, testing/it/e2e-selenium-utils/src/main/java/com/adobe/cq/wcm/core/components/it/seljup/util/components/separator/v1/Separator.java, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/separator/v1/SeparatorIT.java, testing/it/it.ui.apps/src/content/jcr_root/apps/core-component/components/separator-v1/.content.xml
| Fixed Issues?            | Fixes #2334 
| Any Dependency Changes?  | 
* implemented support for decorative separator adding isDecorative property in edit dialog and config dialog
* updated component readme
* added unit tests and UI tests
* updated examples library
=> SITES-9357 - [Accessibility][Core Separator] Missing method to make it decorative

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/PageImpl.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/PageImplTest.java, bundles/core/src/test/resources/page/exporter-templated-page.json, bundles/core/src/test/resources/page/v2/exporter-templated-page.json, bundles/core/src/test/resources/page/v3/exporter-templated-page.json
- add page specific behaviour to get correct last modified date from the page properties
- extend unit test fixes #2384
| Fixed Issues?            | Fixes #2384 
| Documentation Provided   | No, not needed.
| Any Dependency Changes?  | 👎
=> fix: return cq:lastModified Date in data layer for pages

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/AbstractListItemImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/ListItem.java, content/src/content/jcr_root/apps/core/wcm/components/container/v1/container/simple.html, testing/it/http/pom.xml, testing/it/http/src/test/java/com/adobe/cq/wcm/core/components/it/http/ContainerIT.java, testing/it/http/src/test/resources/structure-layout-page.txt, testing/it/it.ui.apps/src/content/jcr_root/apps/core-component/components/container-v1/.content.xml, testing/it/it.ui.content/src/content/jcr_root/conf/core-components/settings/wcm/policies/.content.xml, testing/it/it.ui.content/src/content/jcr_root/conf/core-components/settings/wcm/templates/structure-layout-template/.content.xml, testing/it/it.ui.content/src/content/jcr_root/conf/core-components/settings/wcm/templates/structure-layout-template/initial/.content.xml, testing/it/it.ui.content/src/content/jcr_root/conf/core-components/settings/wcm/templates/structure-layout-template/policies/.content.xml, testing/it/it.ui.content/src/content/jcr_root/conf/core-components/settings/wcm/templates/structure-layout-template/structure/.content.xml, testing/it/it.ui.content/src/content/jcr_root/content/core-components/simple-page/.content.xml, testing/it/it.ui.content/src/content/jcr_root/content/core-components/simple-page/structure-layout-page/.content.xml
- Call resource of child items instead of path to render child item with correct resource type
- extend ListItem API with getResource method
- provide http test to validate changes
fixes #2394
| Fixed Issues?            | Fixes #2394 
=> [Container] Fix simple layout mode

content/src/content/jcr_root/apps/core/wcm/components/commons/editor/clientlibs/panelcontainer/v1/js/PanelContainer.js
* Added parent accordion id to active selector, otherwise the first panel in nested accordion will always be returned active (since it's already in an active panel in the parent accordion)
Fixes #2285
=> Cannot edit components in nested Accordion

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/link/DefaultPathProcessor.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/link/LinkBuilderImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/link/LinkUtil.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/link/DefaultPathProcessorTest.java
* Added escaping during link sanitization
* Preserves Adobe Campaign expressions
=> URLs with escaped characters are being removed by XSS because of decoding during link building

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/ResourceListItemImpl.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/LayoutContainerImplTest.java, content/src/content/jcr_root/apps/core/wcm/components/container/v1/container/simple.html
| Patch: Bug Fix?          | 👍 
With #2416 and #2409 we implemented a new way to include container children. This change was breaking for custom LayoutContainer implementations that do not (a) implement the new `getChildren()` method and (b) return items that do not have a `resource` field. 
With this change we added the necessary fallbacks:
a) add a `getResource()` (internal but public API) for the deprecated ListItem implementation of the …
=> SITES-12966: restore backwards compatibility of container/simple.html

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/ContainerItemImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/ContainerItem.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/package-info.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/AbstractContainerImplTest.java
- add support for getPath to the ContainerItem
| Fixed Issues?            | SITES-13253
=> SITES-13253: fix RecursionTooDeepException in custom container HTL

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/link/DefaultPathProcessor.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/link/LinkUtil.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/link/DefaultPathProcessorTest.java
Since the change in #2456 links which contains a fragment before the query parameter like https://test.com/#/downloads/file.html?name=/content/file.zip for example will produce a StringIndexOutOfBoundsException.
This PR add a special handing for such URLs.
| Fixed Issues?            | SITES-13256
=> SITES-13256: fix StringIndexOutOfBoundsException in DefaultPathProcessor

content/src/content/jcr_root/apps/core/wcm/components/commons/editor/clientlibs/panelcontainer/v1/js/PanelContainer.js
Components which got inherit from a panel container but hasn't set the id of a panel container items are currently facing an issue with the change in #2408.
In this PR I added a check if the id is present before using it as part of the selector.
| Fixed Issues?            | SITES-13592, SITES-13475
=> Add check if id of tab item is available

.github/workflows/codeql.yml, content/src/content/jcr_root/apps/core/wcm/components/image/v3/image/clientlibs/editor/js/image.js
* use a selector for fileupload which works for Teaser component too where the fileupload is not visible initially when the edit dialog is opened
| Fixed Issues?            | `SITES-14355` 
=> SITES-14355 - CISCO | Teaser core component - Smart crop issues

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/contentfragment/ModelElementsDataSourceServlet.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/servlets/contentfragment/ModelElementsDataSourceServletTest.java, bundles/core/src/test/resources/com/adobe/cq/wcm/core/components/internal/servlets/contentfragment/test-content.json
| Fixed Issues?            | Fixes https://jira.corp.adobe.com/browse/SITES-13771,  
| Patch: Bug Fix?          | Bug fix
Tries to get the multi text field from "cfm-element" key rather than from the fieldLabel key and falls back on the default value in case is doesn't find anything.
=> SITES-13771 Content Fragment List component : Property Name is getting displayed to users rather than Field Label

README.md, content/src/content/jcr_root/apps/core/wcm/components/commons/editor/dialog/childreneditor/v1/childreneditor/clientlibs/js/childreneditor.js
| Fixed Issues?            | https://jira.corp.adobe.com/browse/SITES-13898
| Patch: Bug Fix?          | Bug Fix
=> [SITES-13898] Fixed moved item deletion for the Accordion/Carousel/Tabs components

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/commons/editor/nextgendm/NextGenDMThumbnail.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/commons/editor/nextgendm/package-info.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v3/NextGenDMThumbnailImpl.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/commons/editor/dialog/nextgendm/NextGenDMThumbnailTest.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v3/NextGenDMThumbnailImplTest.java, content/src/content/jcr_root/apps/core/wcm/components/image/v3/image/nextgendmthumbnail/nextgendmthumbnail.html
| Fixed Issues?            | SITES-13120
=> SITES-13120 : move interface to new location.

content/src/content/jcr_root/apps/core/wcm/components/commons/editor/clientlibs/htmlidvalidator/js/htmlIdValidation.js
| Fixed Issues?            | https://jira.corp.adobe.com/browse/SITES-15335
=> SITES-15335: handle id empty values input

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/ClientLibrariesImpl.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/ClientLibrariesImplTest.java
* added request attribute based injection for categories and resourceTypes fields as a safety mechanism to reduce the risk of unintended injections on these two fields
* updated unit tests
| Fixed Issues?            | SITES-15109 , #1808
=> SITES-15109 - RFH - Applying Async in clientlibraries not working on customer instance

bundles/core/pom.xml, parent/pom.xml, pom.xml
| Fixed Issues?            | Fixes SITES-15835
| Any Dependency Changes?  | **org.apache.httpcomponents:httpclient-osgi:4.5.13** changed to **com.day.commons.osgi.wrapper:com.day.commons.osgi.wrapper.commons-httpclient:3.1.0.018**
Changed **httpclient-osgi** dependency to **com.day.commons.osgi.wrapper.commons-httpclient** and added a target folder exclusion to apache-rat-plugin configuration
=> SITES-15835 -httpclient-osgi dependency change

content/src/content/jcr_root/apps/core/wcm/components/page/v3/page/_cq_dialog/.content.xml
=> [SITES-15716] Broken inheritance of thumbnail - page property of a live copy is being overwritten by a rollout of blueprint

content/src/content/jcr_root/apps/core/wcm/components/pdfviewer/v1/pdfviewer/clientlibs/site/js/pdfviewer.js
The documentservices.adobe.com url was marked as a tracker by the microsoft edge browser.
The acrobatservices.adobe.com url is one of their approved ones.
See: https://learn.microsoft.com/en-us/microsoft-edge/web-platform/tracking-prevention
=> [SITES-16477] Update SDK_URL from documentservices to acrobatservices

content/src/content/jcr_root/apps/core/wcm/components/image/v3/image/clientlibs/ngdmsmartcrop/js/smartcropaction.js
Jira: https://jira.corp.adobe.com/browse/SITES-16761
Added two null pointer checks since `authorNs` is usually undefined.
Since [smartcropaction.js](https://github.com/adobe/aem-core-wcm-components/blob/main/content/src/content/jcr_root/apps/core/wcm/components/image/v3/image/clientlibs/ngdmsmartcrop/js/smartcropaction.js) was added with https://github.com/adobe/aem-core-wcm-components/commit/b49e22c80a42b8db9c4804b8fe0b72e684cc48df I assume that the focus was NGDM and that's the case when `authorNs` should be defined. Hence this is a fix for non-NGDM case.
=> [SITES-16761] Fixed missing toolbar for image component

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/util/LocalizationUtils.java
| Fixed Issues?   Error thrown by LiveRelationshipManagerImpl 
=> Adding check for hasNext 

content/clientlib.config.js, content/pom.xml, content/src/content/jcr_root/apps/core/wcm/components/page/v2/page/footer.html, content/src/content/jcr_root/apps/core/wcm/components/page/v3/page/headlibs.html
Contextualised components.
| Fixed Issues?            |  Fixes #2620
| Documentation Provided   | N
The fix separates the ACDL library from the file datalayer.js and thereby allows the exclusion of the ACDL while retaining the datalayer.js logic (assuming datalayer is enabled).  
These were previously handled as a single clientlib, core.wcm.components.commons.datalayer.v1 and this could be removed by setting the property skipClientlibInclude in the DataLayerConfig CAC to true.  
With this fix the skipClientlibInclude …
=> [2620] fix datalayer ACDL inclusion logic issue

testing/aem-mock-plugin/src/main/java/com/adobe/cq/wcm/core/components/testing/mock/ContextPlugins.java
aem-mock-plugin should register by default the Sling Models implementation picker `com.adobe.cq.wcm.core.components.internal.services.LatestVersionImplementationPicker`, which implements a specific behavior for preferring latest versions and customer implementations of models.
this can be relevant for unit tests if this logic which is in place by default at runtime is expected in the unit test as well.
=> aem-mock-plugin: Register LatestVersionImplementationPicker by default for unit tests

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/ClientLibrariesImpl.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/ClientLibrariesImplTest.java
| Fixed Issues?            | Fixes [`#2606`](https://github.com/adobe/aem-core-wcm-components/issues/2606)
| Tests Added + Pass?      | Tests Pass
- Since the non-deterministic order of `HashSet` causes the issue, we need to make it deterministic.
- This is done by changing the implementation of `categories` from `HashSet` to `LinkedHashSet`. 
- This ensures that the order of elements is maintained in their order of insertion similar to
https://github.com/adobe/aem-core-wcm-components/blob/0efca91f4b7b5f56a02fef …
=> [2606] Fixed Non-deterministic behavior of HashSet that might fail the test ClientLibrariesImplTest

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v3/NextGenDMImageURIBuilder.java
| Fixed Issues?            | Fixes [`#2619`](https://github.com/adobe/aem-core-wcm-components/issues/2619)
| Tests Added + Pass?      | Not Applicable
- As mentioned in the 'Proposed Solution' section of the [issue #2619](https://github.com/adobe/aem-core-wcm-components/issues/2619), the implementation of `params` Map is changed from `HashMap` to `LinkedHashMap`.
- This ensures that the order of parameters in the URI will be maintained in the order of insertion, which remains constant over time.
=> [2619] Fixed Non-deterministic behavior of HashMap that might fail tests using NextGenDMImageURIBuilder

bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/contentfragment/ContentFragmentMockAdapter.java
| Fixed Issues?            | Fixes [`#2608`](https://github.com/adobe/aem-core-wcm-components/issues/2608)
| Tests Added + Pass?      | Tests Pass
| Documentation Provided   | No (Added Code Comments)
- Since the change in ordering of elements loaded by `resource.getChild()` when mocking the `ContentFragment` causes the issue, sorting the elements loaded by the resource will solve the issue. 
- Sorting the elements based on the property name ensures that the elements are always returned in a deterministic order.
- I have used …
=> [2608] Fixed Non-deterministic behavior of HashMap that might fail tests using ContentFragment.getExportedElements()

bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/servlets/embed/EmbedUrlProcessorServletTest.java
| Fixed Issues?            | Fixes [`#2611`](https://github.com/adobe/aem-core-wcm-components/issues/2611)
| Tests Added + Pass?      | Tests Pass
- This fix implements the 1st proposed solution mentioned in the [issue](https://github.com/adobe/aem-core-wcm-components/issues/2611).
- The json strings to be compared are converted to `JsonNode` using `ObjectMapper`.
- Comparing with JsonNodes instead of hardcoded strings make sure the correct key value pair are present, even though the order of keys might change.
=> [2611] Fixed Non-deterministic behavior of Class.getDeclaredFields() that might fail test in EmbedUrlProcessorServletTest

testing/it/http/pom.xml
There are 1 security vulnerabilities found in com.google.guava:guava 31.1-jre
- [CVE-2023-2976](https://www.oscs1024.com/hd/CVE-2023-2976)
Upgrade com.google.guava:guava from 31.1-jre to 32.0.0-jre for vulnerability fix
Ideally, no insecure libs should be used.
By using the [GitHub Actions](https://github.com/murphysecurity/actions) configurations provided by murphysec, we can conduct automatic code security checks in our CI pipeline.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS
=> fix(sec): upgrade com.google.guava:guava to 32.0.0-jre

content/src/content/jcr_root/apps/core/wcm/components/list/v4/list/README.md
The ordered list markup in the README on this page is broken:
https://github.com/adobe/aem-core-wcm-components/tree/main/content/src/content/jcr_root/apps/core/wcm/components/list/v4/list
This PR fixes the markdown markup.
=> Fix ordered list markup in README for list v4

bundles/core/pom.xml, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/Utils.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/helper/image/AdaptiveImageHelper.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/jackson/LinkHtmlAttributesSerializer.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/link/LinkImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/link/LinkManagerImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/link/LinkUtil.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/embeddable/YouTubeImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v2/ImageImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/services/seo/LanguageNavigationSiteRootSelectionStrategy.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServlet.java, parent/pom.xml
Resolves #2639 
Added compile dependency to core.wcm.components.core: org.apache.commons:commons-collections4-4.4 
Replaced non-test usages of Guava with JavaSE and Apache Commons.
=> SITES-18137: core.wcm.components.core: remove non-test use of Guava

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/ContentFragmentUtils.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/contentfragment/DAMContentFragmentImpl.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/ContentFragmentUtilsTest.java
* fixed selenium test ContentFragmentIT.testSetSingleElement , where DAMContentFragmentImpl.isMultiline() returned wrong value due to changed underlying CF implementation behaviour
The test ContentFragmentIT.testSetSingleElement() failed with the message:
Content Fragment first element title should be correctly displayed ==> expected: <true> but was: <false>
The content fragment element title was not displayed for a single line text element representing a title because isMultiline() was incorrectly returning true for this element. In that case the component renders the element not as an element but as a paragraph which doesn't display the element title.
| Fixed Issues?            | SITES-16183 …
=> SITES-16183 - Testing Release Core Components 2.24.0

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/services/seo/LanguageNavigationSiteRootSelectionStrategy.java
| Fixed Issues?            | SITES-19937
| Minor: New Feature?      | 
The weak hash map cache causes a flaky behaviour eventually leading to accessing a repository object which's session has already been closed.
=> SITES-19937: remove caching in LanguageNavigationSiteRootSelectionStrategy.java

content/src/content/jcr_root/apps/core/wcm/components/form/container/v1/container/_cq_design_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/form/container/v2/container/_cq_design_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/image/v1/image/_cq_design_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/image/v2/image/_cq_design_dialog/.content.xml, content/src/content/jcr_root/apps/core/wcm/components/image/v3/image/_cq_design_dialog/.content.xml
* remove defaultValue of granite/ui/components/coral/foundation/form/numberfield in component dialogs
| Fixed Issues?            | SITES-20101
| Major: Breaking Change?  | 
=> SITES-20101 - Ignored defaultValue in numberfield of component dialogs

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/ClientLibrariesImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/ComponentFilesImpl.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/ComponentFilesImplTest.java, extensions/amp/content/src/content/jcr_root/apps/core/wcm/extensions/amp/components/page/v1/page/head.socialmedia.html, testing/it/http/src/test/java/com/adobe/cq/wcm/core/components/it/http/page/amp/v1/AmpPageIT.java, testing/it/it.ui.content/src/content/jcr_root/content/core-components/simple-page/amp-page-v1/.content.xml
* Replaced injector annotations
* Added test and test content for AMP page rendering
* Cleanup unused import
* Added empty head.socialmedia.html to avoid error logging in case the custom components do not provide one
=> SITES-20993 - Identifier com.adobe.cq.wcm.core.components.models.ComponentFiles cannot be correctly instantiated by the Use API

content/src/content/jcr_root/apps/core/wcm/components/tabs/v1/tabs/tabs.html
Updating tab panel id value, to have connection with tab item aria-controls value, for passing lighthouse report accessibility successfully  
=> [SITES-21038] Core Tabs Component Accessibility Issue - Invalid ARIA attribute value

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/form/FormHandlerImpl.java
=> Changing Log level to info for tracking form usage and successfull submission

bundles/core/pom.xml, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/contentfragment/DAMContentFragmentImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/contentfragment/ElementsDataSourceServlet.java, parent/pom.xml
* Replaced Commons Collections 3 with 4
=> SITES-21127 - [Core Components] Remove usages of Commons Collections 3

content/src/content/jcr_root/apps/core/wcm/components/carousel/v1/carousel/controls.html
Bug Report
**Current Behavior :** 
In the carousel component, we can define a label and an aria-label attribute on carousel control buttons.
It work well on the "Next" button.
On the "Previous" button, we can change only the label, its aria-label attribut isn't customizable. 
This causes restitution differences for people using assistive tool (like the NVDA screen reader).
**Expected behavior/code :** 
Keep the same behavior for both "Next" and "Previous" control button.
**Environment :**
- AEM 6.5.19
- Core Components version 2.23.4
**Possible Solution :**
Removing the aria-label attribut duplication solve the issue.
=> [Carousel] Remove attribut duplication on "previous" button

content/src/content/jcr_root/apps/core/wcm/components/button/v2/button/button.html
**Current Behavior** : 
In button component with svg only content, on mousehover there are no way to get a visible label. 
It's ok for known icons like the "burger menu" or the "magnifying glass", but it can be difficult for little-recognized icons.
It's also ok for people using screen reader because an aria-label attribute can be specified on the <button> element.
**Expected behavior/code** : 
To get a visible indication on hover (like the browser hover tooltip) for icon only button.
**Environment**
- AEM 6.5.19
- Core Components version 2.23.4 - [Button composant v2](https://github.com/adobe/aem-core-wcm-components/blob/main/content/src/content/jcr_root/apps/core/wcm/components/button/v2/button/button.html)
**Possible Solution** :
Add a title attribute on the <button> element. It have …
=> [Button] Improve icon-only button

content/src/content/jcr_root/apps/core/wcm/components/breadcrumb/v3/breadcrumb/breadcrumb.html
**Current Behavior** : 
In the breadcrumb, the title of pages written in a foreign language (with a custom language defined in advanced properties) are not well rendered to assistive tool (like the NVDA screen reader)
**Expected behavior/code** : 
Each page title in the breadcrumb should be vocalized in its appropriate language.
**Environment**
- AEM 6.5.19
- Core Components version 2.23.4 - [breadcrumb component v3](https://github.com/adobe/aem-core-wcm-components/blob/main/content/src/content/jcr_root/apps/core/wcm/components/breadcrumb/v3/breadcrumb/breadcrumb.html)
**Possible Solution** :
Get the language of each destination page in the properties using
<sly data-sly-set.lang="${navItem.page.properties.contentLang}"/>
Add a conditional lang attribute on the <a> or <span> element when …
=> [Breadcrumb] Add lang attribute to foreign language breadcrumb links

content/src/content/jcr_root/apps/core/wcm/components/breadcrumb/v3/breadcrumb/breadcrumb.html, content/src/content/jcr_root/apps/core/wcm/components/languagenavigation/v2/languagenavigation/languagenavigation.html, content/src/content/jcr_root/apps/core/wcm/components/navigation/v2/navigation/navigation.html
**Current Behavior** : 
In european countries using the French Accessibility Guidelines (RGAA) or the Luxembourg guideline (RAWeb1), a role attribute is mandatory on each landmark.
The reason is to keep a compatibility with old browser (that don't support HTML5) or old version of assistive tools.
**Expected behavior/code** : 
Navigation menu should have an ARIA nav with attribute role="navigation"
**Environment**
- AEM 6.5.19
- Core Components version 2.23.4 ( [Breadcrumb component v3](https://github.com/adobe/aem-core-wcm-components/blob/main/content/src/content/jcr_root/apps/core/wcm/components/breadcrumb/v3/breadcrumb/breadcrumb.html), [Language navigation v2](https://github.com/adobe/aem-core-wcm-components/blob/main/content/src/content/jcr_root/apps/core/wcm/components/languagenavigat …
=> [Navigation] Add role attribute on navigation

content/src/content/jcr_root/apps/core/wcm/components/image/v3/image/clientlibs/editor/js/image.js
Adding additional check, in case we are opening dialog for Page component image section and in that case updating value of remoteFileReference in order to execute retrieveInstanceInfo correctly for page component and update alt text field in dialog 
| Fixed Issues?            | https://jira.corp.adobe.com/browse/SITES-22145 
=> [SITES-21939] Alt Text not persisting in Page Properties for Featured Image

content/src/content/jcr_root/apps/core/wcm/components/image/v2/image/clientlibs/editor/js/image.js, content/src/content/jcr_root/apps/core/wcm/components/image/v3/image/clientlibs/editor/js/image.js, testing/it/e2e-selenium-utils/src/main/java/com/adobe/cq/wcm/core/components/it/seljup/util/components/image/ImageEditDialog.java, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/image/ImageTests.java, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/image/v2/ImageIT.java, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/image/v3/ImageIT.java
disabling checkboxes in case image is deleted from drop section
| Fixed Issues?            | https://jira.corp.adobe.com/browse/SITES-22027 
=> [SITES-22027] Issue with Image Component Get caption from DAM field persistence

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/LanguageNavigationImpl.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/LanguageNavigationImplTest.java, bundles/core/src/test/resources/languagenavigation/test-content-country.json, bundles/core/src/test/resources/languagenavigation/v2/test-content-country.json
(https://jira.corp.adobe.com/browse/SITES-22419) Jira issue.
Adding this check, in order to get false result, when we have current page language code longer then from another list of pages (for example because of previous implementation when we have 2 under root with names zh and zh_cm component wont be able to show link to second one)
=> [SITES-22419] Follow up on SITES-19714 Fix Release

testing/it/e2e-selenium-utils/src/main/java/com/adobe/cq/wcm/core/components/it/seljup/util/components/image/ImageEditDialog.java, testing/it/e2e-selenium-utils/src/main/java/com/adobe/cq/wcm/core/components/it/seljup/util/components/teaser/v1/TeaserEditDialog.java, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/image/ImageTests.java, testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/teaser/v2/TeaserIT.java
| Fixed Issues?            | https://jira.corp.adobe.com/browse/SITES-22335 
=> [SITES-22335] fix e2e tests for 6.5 and SDK

content/src/content/jcr_root/apps/core/wcm/components/image/v3/image/clientlibs/editor/js/image.js
The ?? operator was included in ES2020, which is supported by Node 14 (released in April 2020). But we are currently using ES2015 (see content.xml)
| Fixed Issues?            | SITES-22335 
=> [SITES-22335] js parse error fix

content/src/content/jcr_root/apps/core/wcm/components/image/v3/image/clientlibs/editor/js/image.js
The ?. operator was included in ES2020, which is supported by Node 14 (released in April 2020). But we are currently using ES2015 (see content.xml)
| Fixed Issues?            | SITES-22335 
=> [SITES-22335] js parse error fix 2

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/contentfragment/ContentFragmentListImpl.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/contentfragment/AbstractContentFragmentTest.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/contentfragment/ContentFragmentListImplTest.java
* added collator based sorting on the query for content fragments
* extended unit tests
| Fixed Issues?            | SITES-24155
=> SITES-24155 - Content fragment list order by error

content/src/content/jcr_root/apps/core/wcm/components/search/v1/search/clientlibs/site/js/search.js, content/src/content/jcr_root/apps/core/wcm/components/search/v2/search/clientlibs/site/js/search.js
* protecting href in search component search.js against XSS
| Fixed Issues?            | SITES-24380
=> SITES-24380 - Checkmarx Vulnerability - OOTB Search.js

examples/ui.config/pom.xml
* updated examples ui.config with newer version of io.wcm.caconfig.editor and io.wcm.caconfig.extensions which are compatible with AEM 6.6
| Fixed Issues?            | `SITES-26627` 
=> SITES-26627 - WCM components examples are not compatible with AEM 6.6

content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion/clientlibs/editor/js/accordion.js
Steps to reproduce bug:
1. Add an accordion component and include three items, such as text components.
2. Navigate to the properties tab and select the "Single item expansion" checkbox.
3. Open the dropdown menu, which displays all three items along with an extra "None" option.
4. Go to the Items tab and delete one item, for example, item 2.
5. Return to the properties tab and open the dropdown …
=> SITES-26750 Accordion : Content editor dialog is adding "None" twice in Expanded Items field

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v3/ImageImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v3/NextGenDMImageURIBuilder.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v3/ImageImplTest.java, bundles/core/src/test/resources/image/v3/exporter-ngdm_test_page_modifiers_image.json, bundles/core/src/test/resources/image/v3/test-content.json
| Fixed Issues?            | `Fixes ASSETS-44583` 
=> ASSETS-44583 : Add  Image modifier support in site editor page

content/src/content/jcr_root/apps/core/wcm/components/form/text/v2/text/clientlibs/site/js/text.js
* fixed JS syntax
* fixing issue reported at https://github.com/adobe/aem-core-wcm-components/pull/2913/files#r1963206030
=> SITES-26450 - Accessibility Issues with AEM Core Components (Form) - WCAG 2.1 Compliance

bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v2/TeaserImpl.java, bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v2/TeaserImplTest.java, bundles/core/src/test/resources/teaser/v2/exporter-teaser27.json, bundles/core/src/test/resources/teaser/v2/exporter-teaser28.json, bundles/core/src/test/resources/teaser/v2/test-content.json, content/src/content/jcr_root/apps/core/wcm/components/teaser/v2/teaser/teaser.html, testing/it/http/src/test/java/com/adobe/cq/wcm/core/components/it/http/TeaserIT.java, testing/it/it.ui.content/src/content/jcr_root/content/core-components/teaser/teaser-links/.content.xml
* Updated teaser to only allow image to render links if all other elements are empty (pre-title, title, description, actions), in which case it will unwrap the general link on the teaser content.
Fixes #2660
=> SITES-28693 - Teaser Component Renders Broken HTML When Title is Empty

content/src/content/jcr_root/apps/core/wcm/components/image/v3/image/clientlibs/editor/js/image.js
| Fixed Issues?            | `SITES-30116` 
| Tests Added + Pass?      | Yes (existing)
Jira [SITES-30116](https://jira.corp.adobe.com/browse/SITES-30116)
Fixes alt text from page image not being shown inside image / teaser components on initial load.
Steps to reproduce:
0. Add a page image with alt text to a page inside WKND content, such as /content/wknd/es/es
1. Drag and drop an image or teaser component.
2. Select the "Inherit alternative text from page" checkbox in the …
=> SITES-30116 AEM Teaser/Image Core Component Alternative Text Field Issue

content/src/content/jcr_root/apps/core/wcm/components/image/v2/image/image.html
Jira: https://jira.corp.adobe.com/browse/SITES-30372
Previously, the code assumed that no client-side processing is needed for named renditions such as `Large` or `Medium`
But these do include the `dpr` wildcard and it needs to be set client-side since the url below
> https://smartimagingbfc3.scene7.com/is/image/TechSupport/large-wallpaper%3ASmall?ts=1743424872455&amp;dpr=on,{dpr}
is not valid and is cut off from image `SRC` by the HTL XSS protection
=> [SITES-30372] Fixed Smart Crop with named renditions for Image(V2)

examples/ui.config/pom.xml
in #2888 the deployment of the examples was fixed for AEM 6.5 by updating the libraries `io.wcm.caconfig.editor` and `io.wcm.caconfig.extensions`.
however, with this update, it's not longer possible to deploy to AEM 6.5.22 as those updated libraries depend on more recent version of `org.apache.sling.caconfig.spi` and `org.apache.sling.caconfig.impl`. those version are are included in AEM 6.6 and AEMaaCS SDK, but not in AEM 6.5 and it's lastest service packs.
this PR adds the three relevant Sling Context-Aware Context libraries and updates them to the versions contained in AEM 6.6, thus being compatible to be deployed to AEM 6.5.22, AEM 6.6 and AEMaaCS SDK.
=> WCM components examples are not compatible with AEM 6.5

bundles/core/pom.xml, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/services/embed/OEmbedXMLResponseImpl.java, bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/embed/EmbedUrlProcessorServlet.java, bundles/core/src/test/resources/findbugs-exclude.xml
Jira [SITES-33527](https://jira.corp.adobe.com/browse/SITES-33527)
Remove unneeded and barely used dependency, for which an alternative exists.
`spotbugs-annotations` provided a set of Java annotations used in static code scans at build time via Maven plugin. They were previously only used to exclude 2 fields from this scanning. This exclusion is now done in `findbugs-exclude.xml`, in the same manner as other preexisting exclusion rules
| License                  | …
=> SITES-33527 remove Spotbugs Annotations Dependency in AEM Core WCM Components

examples/ui.apps/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-site/styles/components/progressbar.less
Fixes [SITES-23664](https://jira.corp.adobe.com/browse/SITES-23664)
Change format for specific locales
=> SITES-23664: Incorrect percentage format in Template Editor > "Progress Bar" components
